invenio_opendata/base/templates/search/collection_atlas_higgs_challenge_2014.html
=> templates: fix for typo in ATLAS Higgs Challenge

invenio_opendata/base/templates/about_atlas.html
* Updates "About ATLAS" page as suggested by David Rousseau.
=> templates: update to About ATLAS page

invenio_opendata/base/templates/data/news_db.html
=> templates: production date for ATLAS news item

invenio_opendata/base/templates/data/news_db.html
=> templates: ATLAS news headline typo fix

invenio_opendata/base/templates/data/news_db.html
=> templates: ALICE news item title change

setup.py
* Amends requirements on include also Invenio v2.0.x versions.
=> installation: dependency upgrade on Invenio v2.0

invenio_opendata/base/recordext/fields/opendata.cfg
=> records: fix for 110__g/710__g in data model

invenio_opendata/base/recordext/fields/opendata.cfg, invenio_opendata/base/templates/records/macros.html
- 4b3914e2fd7cb28aeb1a811bb3f1265674f0cfe6 templates: documentation note link printing
- b5847d8d3895268ac598e41cb51f0f74bcfff343 templates: untabify record macros
- e8595cd159fc04ba155608648265c4fd1cd153c4 records: new data model fields 556__u and 556__y
=> templates: documentation note link printing

invenio_opendata/base/fixtures/websearch.py, invenio_opendata/base/templates/helpers/collections_educate.html
- f0024d2e9fe79f4f14d68a314e655e5a6487b41e templates: CMS Run2011A collections in educate
- eaf4a765970e1b639978de3dc831df09ec3797f2 templates: reindenting `collections_educate`
- 352e70ec4bf22c1bd3ab52da7967e14e279f170e fixtures: new CMS Run2011A collections
=> fixtures: new CMS Run2011A collections

invenio_opendata/base/recordext/fields/opendata.cfg
=> records: fix 772 in data model

DEVELOPING.rst, invenio_opendata/base/fixtures/websearch.py, invenio_opendata/testsuite/data/cms/cms-condition-data-Run2010B.xml, invenio_opendata/testsuite/data/cms/cms-condition-data-Run2011A.xml
- f57928c5f9f43f19aee19f81121dee43d99460f7 CMS: condition data collection
- 321bb715c1597032195e7ca98a4ce2bc79e1f480 CMS: condition data record description
- 53be40af0885f6616695336e0b6e0285b6acbe2f CMS: condition data records
=> CMS Condition Data

invenio_opendata/testsuite/data/atlas/atlas-tools.xml
=> ATLAS: Tools XML file syntax fix

invenio_opendata/base/fixtures/websearch.py
* Adds new CMS Configuration Files collection. (addresses #935)
=> CMS: new Configuration Files collection

invenio_opendata/testsuite/data/cms/cms-tools-vm-image-Run2011A.xml, scripts/populate-fft-file-cache.sh
* Adds CMS VM image 2011 file. (closes #906)
=> CMS: addition of VM image 2011 file

invenio_opendata/testsuite/data/cms/cms-configuration-files-Run2011A.xml
* Enhances metadata of the CMS Configuration Files. (closes #957)
=> CMS: configuration files enhancement

README.rst
=> docs: chatroom badge

invenio_opendata/testsuite/data/cms/cms-trigger-path-Run2011A.xml
=> CMS: fix XML of trigger path Run2011A file

run-tests.sh
* Enhances Travis CI configuration to test for unique record
IDs. (addresses #947)
=> travis: test for unique record IDs

invenio_opendata/base/static/css/general.css, invenio_opendata/base/static/css/search.css, invenio_opendata/base/templates/about_physics_objects_overview.html, invenio_opendata/base/templates/helpers/text/about_CMS_physics_objects_2010.html, invenio_opendata/base/templates/helpers/text/about_CMS_physics_objects_2011.html, invenio_opendata/base/templates/helpers/text/about_CMS_physics_objects_overview.html, invenio_opendata/base/templates/page.html, invenio_opendata/base/views.py
* UI: fixes bug in "things to remember"
* UI: updates styling in focused links
* global: updates URL and anchoring issues and functionality
* search: updates briefs styling for blockquotes
=> General updates

invenio_opendata/testsuite/data/cms/cms-hlt-2011-configuration-files.xml
* Updates description of HLT cdaq configuration files. (closes #1039)
=> CMS: cdaq configuration file description update

invenio_opendata/testsuite/data/cms/cms-configuration-files/2e0a80c07f23808d4b75c974eaf57bbc.configFile, invenio_opendata/testsuite/data/cms/cms-configuration-files/a3e9a49adb11d7079eda533cfa1f9ee3.configFile, invenio_opendata/testsuite/data/cms/cms-configuration-files/e057b5071cdc2df588be80e24a11fb92.configFile, invenio_opendata/testsuite/data/cms/cms-configuration-files/e057b5071cdc2df588be80e24a131404.configFile
* Adds four missing configuration files, fixing upload problems for CMS
Run2011A configuration file records.
=> CMS: more configuration files

invenio_opendata/testsuite/data/cms/cms-configuration-files-Run2011A.xml, invenio_opendata/testsuite/data/cms/cms-hlt-2011-configuration-files.xml, invenio_opendata/testsuite/data/cms/cms-pileup-configuration-files.xml
* Adds Issues and Limitations text for all configuration file records.
(closes #1038)
=> CMS: issues and limitations for config files

invenio_opendata/base/static/css/general.css, invenio_opendata/base/templates/CMS_VM_validation.html, invenio_opendata/base/views.py
* global: fixes endpoint issues in views
* UI: adds general CSS helper classes
=> global: UI and endpoint updates

invenio_opendata/testsuite/data/cms/cms-tools-vm-image-Run2011A.xml, invenio_opendata/testsuite/data/cms/cms-vm-contextualisation-scripts-Run2011A/cernvm-script, invenio_opendata/testsuite/data/cms/cms-vm-contextualisation-scripts-Run2011A/cms-user-data.txt, invenio_opendata/testsuite/data/cms/cms-vm-contextualisation-scripts-Run2011A/opendata-desktop-settings, scripts/populate-fft-file-cache.sh
* Adds contextualisation scripts for the new CMS 2011 VM image.
(closes #815)
=> CMS: new VM image contextualisation scripts

invenio_opendata/testsuite/data/cms/cms-condition-data-Run2011A.xml, invenio_opendata/testsuite/data/cms/eos-file-indexes/CMS_Run2011A_db_FT_53_LV5_AN1_file_index.txt, invenio_opendata/testsuite/data/cms/eos-file-indexes/CMS_Run2011A_db_START53_LV6A1_file_index.txt
* Adds information about condition database files on EOS. (closes #901)
=> CMS: condition data file information

invenio_opendata/testsuite/data/cms/cms-hlt-2011-configuration-files.xml
* Adds run number and CMSSW version to the HLT cdaq configuration file
records. (closes #982)
=> CMS: richer HLT cdaq description

.kwalitee.yml, .travis.yml
* Adds `kwalitee` commit message check to the Travis CI process.
=> kwalitee: initial configuration

invenio_opendata/testsuite/data/atlas/atlas-derived-datasets.xml
* New Data Samples records. (addresses #1140) (closes #1141)
=> ATLAS: new Data Samples records

invenio_opendata/testsuite/data/atlas/atlas-simulated-datasets.xml
- 81365c14a101ebb1205494629446d2d4f88f59eb ATLAS: record IDs in Simulated Datasets
- 680224731749978055667b2190ca35dc97f62081 ATLAS: new Simulated Datasets
=> ATLAS: new Simulated Datasets

.kwalitee.yml, DEVELOPING.rst, invenio_opendata/base/fixtures/websearch.py
* Adds new collection for ATLAS Simulated Datasets. (closes #1151)
=> fixtures: new collection ATLAS Simulated Datasets

invenio_opendata/testsuite/data/atlas/atlas-tools.xml
* Adds new VM records for 2016 open data release.
(addresses #1146) (closes #1147)
Signed-off-by: Anxhela Dani anxhela.dani@cern.ch
=> ATLAS: new VM records for 2016 open data release

invenio_opendata/testsuite/data/atlas/atlas-simulated-datasets.xml
* Corrects HTML in title fields.  (addresses #1143) (closes #1158)
Signed-off-by: Anxhela Dani <anxhela.dani@cern.ch>
=> ATLAS: correction of title fields

invenio_opendata/testsuite/data/atlas/atlas-tools.xml, invenio_opendata/testsuite/data/atlas/eos-file-indexes/atlas-outreach-data-tools-framework-1.1_file_index.txt
* Adds EOS files for Run2012D SW record. (closes #1144)
=> ATLAS: EOS files for Run2012D SW record

invenio_opendata/base/templates/data/news_db.html
* Adds news item about ATLAS Open Data July 2016 release. (closes #1171)
Signed-off-by:  Sunje Dallmeier-Tiessen <sunje.dallmeier-tiessen@cern.ch>
=> templates: addition of ATLAS news item

invenio_opendata/testsuite/data/atlas/atlas-derived-datasets.xml, invenio_opendata/testsuite/data/atlas/atlas-simulated-datasets.xml
- 6e88722c4a1ef5a5448685384b589569cd3045b6 ATLAS: link record and correct SW in Data
- 7b28dda71111b2a8ff06743e32fb7824839e5164 ATLAS: link record and correction of SW in MC
=> ATLAS: link record and correct SW in Data and MC

invenio_opendata/testsuite/data/atlas/atlas-tools.xml
=> ATLAS: Run2012D SW record version V1.1

invenio_opendata/testsuite/data/atlas/atlas-simulated-datasets.xml
Signed-off-by: Anxhela Dani anxhela.dani@cern.ch
=> ATLAS: title adjustment

.travis.yml
* Switches off failing kwalitee commit log message test until the issue fixed in
the upstream kwalitee package.
=> travis: switch off kwalitee message checking

invenio_opendata/base/templates/records/CMS-Simulated-Datasets_dedicated.html, invenio_opendata/base/templates/records/metadata_base.html
- 93d3f242fb1b359e4670831b523c7d092a64a386 templates: display of data_source_entry
- a0b983ec35f6045c95d02cab342c8a13072363fc templates: display of supplement_special_issue_entry.displaytext
- aa327cacb65c7e936aa9591852da794900e4aa44 templates: display of system_details.url
- d884839f19607a552a46c623b73d7e2b415b3336 templates: display of abstract.recid
- 28f2f412df5d4952c00f2ebe854f008bc9a28cf7 templates: display of abstract.url
=> templates: display new fields

invenio_opendata/base/fixtures/websearch.py
=> fixtures: OPERA collections plugged under Home

invenio_opendata/testsuite/data/cms/cms-tools-cmssw-Run2011A.xml, invenio_opendata/testsuite/data/cms/cms-tools-cmssw.xml
* Addition of 856 to link to the CMSSW source repositories.
(closes #1225) (PR #1240)
=> CMS: addition of links to CMSSW records

invenio_opendata/testsuite/data/cms/cms-validated-runs.xml
* Updates information in the list of validated runs.
(addresses #1138) (PR #1241)
=> CMS: updates to list of validated runs

invenio_opendata/testsuite/data/cms/cms-luminosity-information.xml
* Improves formatting and verbiage in luminosity records. (closes #1138)
=> CMS: better verbiage in luminosity records

invenio_opendata/base/templates/about_opera.html
* Updates the "About OPERA" information based on feedback received.
(closes #1260) (PR #1261)
=> templates: update to About OPERA

invenio_opendata/base/fixtures/websearch.py
=> fixtures: intro text update for /collections/OPERA

invenio_opendata/testsuite/data/opera/opera-author-list.xml
* Amends names of some authors that were incomplete. (PR #1291)
=> OPERA: author name updates

cernopendata/cli.py, setup.py
=> setup: cli simplification

cernopendata/modules/pages/views.py, cernopendata/modules/theme/bundles.py, cernopendata/static/js/glossary/jquery.zglossary.css, cernopendata/static/js/glossary/jquery.zglossary.js, cernopendata/templates/cernopendata_theme/page.html, setup.py
=> glossary: adds tootip for terms

cernopendata/modules/pages/views.py, cernopendata/modules/theme/bundles.py, cernopendata/templates/cernopendata_pages/visualise_events_opera.html, setup.py
=> opera: adds opera previewer

cernopendata/config.py, cernopendata/templates/cernopendata_records_ui/terms/detail.html, cernopendata/templates/cernopendata_theme/page.html
=> glossary: adds links and sorting

cernopendata/modules/pages/views.py, cernopendata/modules/theme/static/scss/footer.scss, cernopendata/templates/cernopendata_pages/visualise_events_opera.html, cernopendata/templates/cernopendata_theme/footer.html
=> opera: fixes 3d tracks in opera previewer

cernopendata/modules/pages/views.py, cernopendata/templates/cernopendata_pages/index.html, cernopendata/templates/cernopendata_pages/visualise_events.html
=> templates: visualise link on homepage

cernopendata/config.py, cernopendata/templates/cernopendata_records_ui/terms/detail.html
=> templates: brings back glossary detail

cernopendata/config.py, cernopendata/jsonschemas/records/data-policies-v1.0.0.json, cernopendata/modules/fixtures/cli.py, cernopendata/modules/fixtures/data/data-policies-v1.0.0.json, cernopendata/modules/records/links.py, cernopendata/modules/xrootd/__init__.py, cernopendata/modules/xrootd/ext.py, requirements-devel-cernopendata.txt, scripts/create-instance.sh, setup.py
* uses EOS as Storage
* ~~for this PR to work changes need to be done in https://github.com/inveniosoftware/invenio-files-rest/blob/aa90e5e995527262eb559c89c5676b324d9ea9ab/invenio_files_rest/storage/pyfs.py#L177 to accept kwargs~~
* ~~workaround is commenting out following lines https://github.com/inveniosoftware/invenio-xrootd/blob/master/invenio_xrootd/storage.py#L71-L72\~~
=> files: introduces files in records

cernopendata/config.py, cernopendata/static/templates/resources/results.html, cernopendata/templates/cernopendata_pages/resources.html
=> templates: adds resources template

cernopendata/config.py, cernopendata/modules/records/serializers/__init__.py, cernopendata/modules/records/serializers/basic_json.py, cernopendata/templates/cernopendata_records_ui/articles/detail.html, cernopendata/templates/cernopendata_records_ui/default_export.html, cernopendata/templates/cernopendata_records_ui/records/detail.html
=> records: add export to raw JSON

cernopendata/mappings/records/data-policies-v1.0.0.json, cernopendata/templates/cernopendata_pages/index.html, cernopendata/templates/cernopendata_pages/visualise_events_opera.html, cernopendata/templates/cernopendata_records_ui/articles/detail.html, cernopendata/templates/cernopendata_records_ui/terms/detail.html, scripts/populate-instance.sh
=> global: multiple updates

cernopendata/config.py, cernopendata/mappings/records/article-v1.0.0.json, cernopendata/mappings/records/data-policies-v1.0.0.json, cernopendata/mappings/records/datasets-v1.0.0.json, cernopendata/mappings/records/software-v1.0.0.json, cernopendata/mappings/records/term-v1.0.0.json
* Closes #1426 
* Closes #1418
=> Add type facet instead of collections

cernopendata/templates/cernopendata_records_ui/records/detail.html
=> templates: improve datacite records ui

cernopendata/config.py, cernopendata/static/js/components/resultsBrief.js, cernopendata/static/templates/search/briefs/dataset.html, cernopendata/static/templates/search/briefs/software.html, cernopendata/templates/cernopendata_records_ui/records/dataset_detail.html, cernopendata/templates/cernopendata_records_ui/records/software_detail.html
* add detail tempates and briefs for ‘datasets’, ‘software’
=> records: update detail and briefs

cernopendata/config.py, cernopendata/jsonschemas/records/glossary-term-v1.0.0.json, cernopendata/mappings/records/glossary-term-v1.0.0.json, cernopendata/modules/fixtures/cli.py, cernopendata/modules/pages/views.py, cernopendata/static/js/components/resultsBrief.js, cernopendata/static/templates/cernopendata_terms_ui/brief.html, cernopendata/static/templates/search/briefs/terms.html, cernopendata/templates/cernopendata/glossary_terms.html, cernopendata/templates/cernopendata_records_ui/terms/detail.html, cernopendata/templates/cernopendata_theme/header.html, scripts/populate-instance.sh
=> glossary: renames 'terms' to 'glossary'

cernopendata/templates/cernopendata_records_ui/records/dataset_detail.html, cernopendata/templates/cernopendata_records_ui/records/detail.html, cernopendata/templates/cernopendata_records_ui/records/macros/files_box.html
=> records: fix file size, add caution modal

cernopendata/modules/fixtures/cli.py, scripts/populate-instance.sh, setup.py
=> global: drop invenio collections

cernopendata/templates/cernopendata_records_ui/records/dataset_detail.html, cernopendata/templates/cernopendata_records_ui/records/detail.html
=> templates: nice dataset detail record

Dockerfile, docker-compose.yml, nginx/cernopendata.conf, scripts/docker-entrypoint.sh, scripts/provision-web.sh
=> docker: OpenShift compatible setup

cernopendata/config.py, cernopendata/modules/fixtures/cli.py, cernopendata/modules/records/utils.py, cernopendata/modules/xrootd/ext.py, cernopendata/templates/cernopendata_records_ui/records/components/previewer.html, cernopendata/templates/cernopendata_records_ui/records/detail.html, cernopendata/templates/cernopendata_records_ui/records/macros/files_box.html, cernopendata/templates/cernopendata_records_ui/records/software_detail.html, setup.py
for example check ```http://localhost:5000/records/410```
=>  records: introduces previewer

cernopendata/cli.py, cernopendata/config.py, cernopendata/modules/datacite/__init__.py, cernopendata/modules/datacite/cli.py, cernopendata/modules/datacite/client.py, cernopendata/modules/datacite/providers.py, cernopendata/modules/datacite/serializers.py, cernopendata/modules/datacite/utils.py, docker-compose.yml, setup.py, tests/conftest.py, tests/test_datacite_cli.py
=> datacite: add basic cli for datacite DOIs

cernopendata/config.py, cernopendata/modules/fixtures/cli.py, cernopendata/modules/records/fetchers/datasetid.py, cernopendata/modules/records/minters/datasetid.py, cernopendata/modules/records/providers/artid.py, cernopendata/modules/records/providers/datasetid.py, cernopendata/modules/records/providers/termid.py, cernopendata/static/templates/search/briefs/dataset.html, cernopendata/templates/cernopendata_records_ui/records/dataset_detail.html, setup.py
=> datasets: use doi in url as identifier

cernopendata/config.py, cernopendata/static/templates/cernopendata_search_ui/facets.html, cernopendata/static/templates/faceted_results.html, cernopendata/static/templates/search/briefs/articles.html, cernopendata/static/templates/search/briefs/dataset.html, cernopendata/static/templates/search/briefs/default.html, cernopendata/static/templates/search/briefs/software.html, cernopendata/static/templates/search/briefs/terms.html, cernopendata/templates/cernopendata_pages/index.html
=> facets: fix facets and urls after clicking labels

cernopendata/modules/collections/descriptions.py, cernopendata/modules/pages/views.py, cernopendata/static/templates/faceted_results.html, cernopendata/templates/cernopendata_pages/faceted_page.html
adds all basic collection pages, described in #1384 
=> templates: adds more collection pages urls

cernopendata/modules/theme/static/scss/styles.scss, cernopendata/static/templates/cernopendata_search_ui/facets.html, cernopendata/static/templates/cernopendata_terms_ui/results.html, cernopendata/static/templates/faceted_results.html, cernopendata/static/templates/search/briefs/articles.html, cernopendata/static/templates/search/briefs/dataset.html, cernopendata/static/templates/search/briefs/default.html, cernopendata/static/templates/search/briefs/software.html, cernopendata/static/templates/search/briefs/terms.html, cernopendata/templates/cernopendata/glossary_terms.html, cernopendata/templates/cernopendata_pages/faceted_page.html, cernopendata/templates/cernopendata_theme/breadcrumbs.html, cernopendata/templates/cernopendata_theme/header.html, cernopendata/templates/cernopendata_theme/page.html, setup.py
=> UI: css enhancements in search results

cernopendata/modules/theme/static/scss/styles.scss, cernopendata/static/js/components/resultsBrief.js, cernopendata/static/templates/cernopendata_search_ui/facets.html, cernopendata/static/templates/cernopendata_terms_ui/results.html, cernopendata/static/templates/faceted_results.html, cernopendata/static/templates/search/briefs/dataset.html, cernopendata/static/templates/search/briefs/software.html, cernopendata/templates/cernopendata/glossary_terms.html, cernopendata/templates/cernopendata/search.html
=> UI: removes inline css

cernopendata/modules/pages/views.py, cernopendata/static/templates/faceted_results.html, cernopendata/templates/cernopendata_theme/header.html
* add /datasets page
* add /resources/articles page
=> templates: add datasets and resources/articles links

cernopendata/templates/cernopendata_records_ui/terms/detail.html, cernopendata/templates/cernopendata_theme/footer.html
=> UI: fixes logos in footer

cernopendata/static/js/visualise/visualise_histograms.js, cernopendata/templates/cernopendata_pages/visualise_events_opera.html
* Fixes help text in visualise histo.
* Closes #1541.
=> UI: fixes opera previewer

cernopendata/config.py, cernopendata/modules/fixtures/cli.py, cernopendata/modules/records/fetchers/softid.py, cernopendata/modules/records/minters/softid.py, cernopendata/modules/records/providers/softid.py, cernopendata/templates/cernopendata_records_ui/records/dataset_detail.html, cernopendata/templates/cernopendata_records_ui/records/detail.html, cernopendata/templates/cernopendata_records_ui/records/macros/files_box.html, cernopendata/templates/cernopendata_records_ui/records/software_detail.html, setup.py
* Adds software record.
* Fixes download warning behavior.
* Closes #1451.
=> files: fixes file download for all records

setup.py
=> setup: pins invenio-jsonschemas

cernopendata/config.py, cernopendata/static/templates/cernopendata_search_ui/condensed_results.html, cernopendata/templates/cernopendata/search.html
=> search: introduces condensed format

cernopendata/modules/theme/bundles.py, cernopendata/modules/theme/static/scss/styles.scss, cernopendata/templates/cernopendata_pages/index.html, cernopendata/templates/cernopendata_pages/visualise_events_cms.html, setup.py
=> ispy: integrate ispy previewer

cernopendata/modules/fixtures/data/records/lhcb-antimatter-matters-2017.json
* Adds data, software and documentation records for the release of materials from the LHCb Open Data Portal Project (closes #1236)
=> LHCb: new records for open data project

cernopendata/modules/fixtures/data/records/cms-eventdisplay-files-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-eventdisplay-files.json
* Fixes detection of file formats AOD, AODSIM and RAW. (closes #1589)
=> records: distribution.formats detection fix

cernopendata/views.py
=> search: accept p parameter in search query

cernopendata/templates/cernopendata_theme/header.html
=> search: display searched parameter

cernopendata/modules/fixtures/cli.py
=> cli: add option to load specific files

cernopendata/static/templates/search/briefs/default.html, cernopendata/templates/cernopendata_records_ui/records/detail.html, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
=> detail: updates record detail pages

cernopendata/modules/theme/views.py, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
=> global: adds filter to fetch record title

cernopendata/modules/theme/views.py, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
=> detail: fixes more detail pages

cernopendata/templates/cernopendata_theme/header.html
=> header: fixes links

cernopendata/templates/cernopendata_records_ui/records/detail.html, cernopendata/templates/cernopendata_records_ui/records/record_detail.html, cernopendata/templates/cernopendata_records_ui/terms/detail.html
* Closes #1627.
* Closes #1628.
=> detail: fixes more detailed pages

cernopendata/modules/fixtures/data/records/atlas-all-samples.json, cernopendata/modules/fixtures/data/records/atlas-derived-datasets.json, cernopendata/modules/fixtures/data/records/atlas-simulated-datasets.json, cernopendata/modules/fixtures/data/records/atlas-tools.json
* Updates external links to the new ATLAS Open Data web site. (closes #1684)
=> records: external ATLAS links

cernopendata/modules/fixtures/data/records/alice-derived-datasets.json, cernopendata/modules/fixtures/data/records/alice-learning-resources.json, cernopendata/modules/fixtures/data/records/atlas-all-samples.json, cernopendata/modules/fixtures/data/records/atlas-derived-datasets.json, cernopendata/modules/fixtures/data/records/atlas-learning-resources.json, cernopendata/modules/fixtures/data/records/atlas-simulated-datasets.json, cernopendata/modules/fixtures/data/records/atlas-tools.json, cernopendata/modules/fixtures/data/records/lhcb-derived-datasets.json, cernopendata/modules/fixtures/data/records/lhcb-learning-resources.json, cernopendata/modules/fixtures/data/records/lhcb-tools.json
* Removes keyword values that are identical with experiment names.
(closes #1599)
=> records: remove experiment keyword values

requirements-production.txt, scripts/create-instance.sh
=> installation: install forked requirements first

cernopendata/config.py, cernopendata/modules/pages/views.py, cernopendata/static/templates/cernopendata_search_ui/facets.html, cernopendata/templates/cernopendata/search.html, cernopendata/templates/cernopendata_pages/faceted_page.html
* closes #1659
* closes #1660 
* recalculating facets is temporary solution for alpha release (references #1685)
=> Fixes to facets

cernopendata/modules/fixtures/cli.py, docker-compose.yml, scripts/populate-instance.sh
=> scripts: call fixtures records for every record

cernopendata/modules/fixtures/data/articles/cms-guide-for-education/cms.json, cernopendata/modules/fixtures/data/articles/cms-guide-for-education/education.md, cernopendata/modules/fixtures/data/articles/cms-guide-for-research/cms.json, cernopendata/modules/fixtures/data/articles/cms-guide-for-research/research.md, cernopendata/modules/fixtures/data/articles/cms-guide-troubleshooting/cms.json, cernopendata/modules/fixtures/data/articles/cms-guide-troubleshooting/errors.md
=> templates: new cms content

cernopendata/modules/fixtures/cli.py
=> fixtures: display verbose log messages correctly

cernopendata/templates/cernopendata_records_ui/records/record_detail.html
=> templates: show files box on detailed record pages

cernopendata/templates/cernopendata_records_ui/records/detail.html, cernopendata/templates/cernopendata_records_ui/records/macros/files_box.html, cernopendata/templates/cernopendata_records_ui/records/record_detail.html, cernopendata/templates/cernopendata_theme/page.html
=> files: pagination in record page

cernopendata/modules/fixtures/cli.py, cernopendata/templates/cernopendata_records_ui/records/macros/files_box.html
As discussed in #1759 . This is option 2
#1759 should be closed after we merge this one
=> files: adds file metadata to record

cernopendata/modules/pages/views.py
* Closes #1383.
* Closes #1382.
* Closes #1381.
* Closes #1380.
* Closes #1379.
* Closes #1375.
=> templates: adds research and education

cernopendata/modules/fixtures/data/articles/cms-virtual-machines-2010/cms-virtual-machines-2010.json, cernopendata/modules/fixtures/data/articles/cms-virtual-machines-2010/cms-virtual-machines-2010.md
=> templates: port CMS VM 2010 docs

cernopendata/static/templates/search/briefs/articles.html, cernopendata/static/templates/search/briefs/dataset.html, cernopendata/static/templates/search/briefs/default.html, cernopendata/static/templates/search/briefs/record.html, cernopendata/static/templates/search/briefs/software.html, cernopendata/static/templates/search/briefs/terms.html, cernopendata/templates/cernopendata/search.html, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
=> templates: fixes parent dataset

cernopendata/modules/pages/views.py
=> views: redirect /vm/<experiment> to search

cernopendata/config.py, cernopendata/modules/records/utils.py, cernopendata/templates/cernopendata_records_ui/records/detail.html, cernopendata/templates/cernopendata_records_ui/records/macros/files_box.html, cernopendata/templates/cernopendata_records_ui/records/record_detail_Author-Lists.html
* closes #1651
* closes #1644
* closes #1624
=> records: Author-Lists rich metadata display

cernopendata/modules/fixtures/data/articles/cms-guide-for-education/education.md
* Updates CMS Guide for Education. (closes #1767)
=> articles: cms-guide-for-education updates

cernopendata/modules/theme/static/scss/footer.scss, cernopendata/modules/theme/static/scss/styles.scss
=> UI: fixes sticky-footer

cernopendata/modules/pages/views.py, cernopendata/templates/cernopendata_pages/about/about_alice.html, cernopendata/templates/cernopendata_pages/about/about_atlas.html, cernopendata/templates/cernopendata_pages/about/about_cms.html, cernopendata/templates/cernopendata_pages/about/about_lhcb.html, cernopendata/templates/cernopendata_pages/about/about_opera.html, cernopendata/templates/cernopendata_pages/about/index.html, cernopendata/templates/cernopendata_pages/privacy_policy.html
* fix datasets page
* prettify about pages
=> templates: Fix datasets page

cernopendata/modules/pages/views.py, cernopendata/modules/theme/bundles.py, cernopendata/static/js/visualise/visualise_histograms.js, cernopendata/templates/cernopendata_theme/page.html, setup.py
=> UI: adds missing breadcrumbs

cernopendata/modules/fixtures/data/records/alice-analysis-modules.json, cernopendata/modules/fixtures/data/records/alice-learning-resources.json, cernopendata/modules/fixtures/data/records/atlas-learning-resources.json, cernopendata/modules/fixtures/data/records/cms-learning-resources.json, cernopendata/modules/fixtures/data/records/cms-open-data-instructions.json, cernopendata/modules/fixtures/data/records/lhcb-learning-resources.json
* Standardises keyword values regarding to "masterclass" and enriches existing
values with "education" and "school".  (addresses #1790)
=> records: keyword standardisation and enrichment

cernopendata/modules/fixtures/data/records/cms-learning-resources.json
=> templates: Fix IPPOG link to new website

cernopendata/modules/fixtures/data/records/cms-dimuon-spectrum-2011.json, cernopendata/modules/fixtures/data/records/cms-validation-code-ttbar.json
* Adds two new validation records (closes #1552) (closes #1556)
=> CMS: new validation records

cernopendata/modules/theme/bundles.py, cernopendata/static/js/glossary/jquery.zglossary.js, cernopendata/templates/cernopendata/search.html, cernopendata/templates/cernopendata_pages/index.html, cernopendata/templates/cernopendata_theme/page.html
* cleans assets and dependencies
* closes #1469
=> UI: fixes JS deps + glossary

cernopendata/modules/fixtures/data/articles/cms-guide-for-education/education.md, cernopendata/modules/fixtures/data/articles/cms-guide-for-research/research.md
If you want to see what these look like, I've taken screenshots of the full pages. Feedback welcome. Let me know if I should make any changes and push to this branch.
**Education**:
**Research**:
=> templates: Update CMS Guides for Education and Research

cernopendata/modules/records/minters/artid.py
=> articles: minter takes slug or title

cernopendata/modules/records/utils.py
* fix for "/record/NNN/files/configFile.py"
* closes #1316
=> system: ensure old /record/NNN links

cernopendata/modules/fixtures/data/articles/cms-guide-for-education/education.md, cernopendata/modules/fixtures/data/articles/cms-guide-for-research/research.md
=> templates: Replace TOBEFIXED with FIXME in Guides (Closes #1860)

cernopendata/modules/theme/static/scss/styles.scss, cernopendata/templates/cernopendata_pages/index.html, cernopendata/templates/cernopendata_theme/header.html
=> UI: improves mobile version

cernopendata/static/js/visualise/visualise_histograms.js
=> preview: fixes visualise histograms

cernopendata/config.py, cernopendata/mappings/records/glossary-term-v1.0.0.json, cernopendata/modules/theme/static/scss/styles.scss, cernopendata/static/templates/cernopendata_search_ui/facets.html
* references #1685
* fix year sorting problem
* fix by title sorting problem
* add possibility to clear chosen facets (needs fix for nested ones)
=> search: Facet fixes

cernopendata/config.py, cernopendata/modules/records/utils.py, cernopendata/modules/theme/bundles.py, cernopendata/modules/theme/static/scss/styles.scss, cernopendata/static/templates/downloadModal.html, cernopendata/templates/cernopendata_records_ui/records/detail.html, cernopendata/templates/cernopendata_records_ui/records/macros/files_box.html, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
* fetches files from server ( not with template rendering )
* fixes file modal - close on download click
=> records: adds view for file pagination

cernopendata/modules/fixtures/data/articles/welcome/welcome.md
Happy to accept any comments before we merge this.
=> templates: Edit welcome.md (Addresses #1732)

cernopendata/modules/fixtures/data/articles/cms-guide-for-research/research.md
Adresses part of the topics in https://github.com/cernopendata/opendata.cern.ch/issues/1518#issuecomment-346834340
=> templates: CMS: updates to research guide

cernopendata/templates/cernopendata_records_ui/terms/detail.html
=> glossary: fix title capitalisation

cernopendata/templates/cernopendata_pages/about/about_opera.html
=> about: updates About OPERA

cernopendata/modules/fixtures/data/articles/cms-guide-troubleshooting/errors.md, cernopendata/modules/fixtures/data/articles/cms-virtual-machines-2010/cms-virtual-machines-2010.md, cernopendata/modules/pages/views.py
=> templates: CMS: addition to troubleshooting

.travis.yml, run-tests.sh
* Adds tests to check whether the JSON fixtures are well formatted and whether
the record IDs are unique. (closes #1851)
=> tests: recid uniqueness in fixtures

cernopendata/config.py, cernopendata/modules/theme/static/scss/styles.scss, cernopendata/static/templates/cernopendata_search_ui/facets.html
=> search: show more facet values

cernopendata/modules/theme/bundles.py, cernopendata/modules/theme/static/scss/styles.scss, cernopendata/templates/cernopendata_theme/page.html
=> UI: removes open iconic from cdn

cernopendata/static/templates/cernopendata_search_ui/facets.html
=> search: improve expand/collapse facet buttons

cernopendata/modules/fixtures/data/articles/about-cms/cms.md
* Addresses #1787 and #1937.
Signed-off-by:  Kati Lassila-Perini <k.lassila-perini@cern.ch>
=> CMS: Updates cms.md

cernopendata/modules/fixtures/data/records/cms-luminosity-information.json
* Attaches one new file to record 1050, adds text in the description.
(closes #1286) (PR #1294)
Co-authored-by: Tibor Simko <tibor.simko@cern.ch>
=> CMS: 2010 luminosity record update

cernopendata/modules/fixtures/data/docs/cms-guide-for-research/research.md, cernopendata/modules/fixtures/data/docs/opera-news/opera-news.json, cernopendata/modules/fixtures/data/docs/opera-news/opera-news.md
* Closes: #1248 
* Closes: #1954
* Closes: #1953
=> templates: opera news

cernopendata/modules/fixtures/data/records/cms-trigger-examples.json
* Adds two new trigger software records (closes #1300)
=> CMS: adds trigger examples

cernopendata/modules/fixtures/data/docs/cms-guide-trigger-system/cms-guide-trigger-system.md
=> CMS: Templates: add links to SW in trigger guide

cernopendata/modules/fixtures/data/docs/about-cms/cms.md
=> CMS: templates: fix one link in About CMS

cernopendata/modules/fixtures/data/records/cms-tools-cmssw-Run2011A.json
* Updates information of CMSSW record regarding years. (closes #1933)
=> records: CMSSW 2011 record usage update

cernopendata/modules/fixtures/data/records/cms-author-list-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-author-list.json, cernopendata/modules/fixtures/data/records/opera-author-list.json
* Adds `experiment` field in Author-Lists records. (closes #1962)
=> records: experiment field in Author-Lists

cernopendata/templates/cernopendata_pages/index.html
* Changes Visualise header text. (closes #1912)
=> templates: VIsualise header text

cernopendata/templates/cernopendata/glossary_terms.html, cernopendata/templates/cernopendata/search.html, cernopendata/templates/cernopendata_records_ui/docs/detail.html, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
=> templates: makes labels clickable

cernopendata/modules/fixtures/data/records/cms-tools-reco.json
=> records: fix for record 464

cernopendata/modules/theme/static/scss/styles.scss, cernopendata/static/templates/cernopendata_search_ui/facets.html
=> search: subfacets visible by deafult; no bullets

cernopendata/modules/fixtures/data/docs/cms-guide-for-research/cms-guide-for-research.md
This addresses #1994, but does not address corrections depending on #1888,  #1996, #1956
=> CMS: templates: correctionto research guide

cernopendata/modules/fixtures/data/docs/cms-virtual-machine-2011/cms-virtual-machine-2011.md, cernopendata/static/templates/cernopendata_search_ui/condensed_results.html
=> search: fix links in condensed view

cernopendata/modules/theme/bundles.py
* increment version of ispy-webgl in bundles
* the new version applies the record ids found in #1404
=> CMS event display files

cernopendata/templates/cernopendata/search.html
=> search: keep results options in url

cernopendata/modules/fixtures/data/docs/cms-guide-for-education/cms-guide-for-education.md
Addresses #1998
@tiborsimko does the Higgs example already have a record number?
=> CMS: Templates. Update links in CMS education guide

cernopendata/modules/fixtures/data/records/cms-validation-code-jet-tuple.json
* Adds one new CMS validation code record. (closes #1830)
=> CMS: adds jet tuple software record

cernopendata/modules/fixtures/data/records/cms-validation-code-Run2010B.json
=> records: add link to readme.txt and Github repo

cernopendata/templates/cernopendata_pages/front/news.html
=> templates: News & Updates links to docs

cernopendata/modules/theme/static/scss/styles.scss, cernopendata/templates/cernopendata/search.html
=> search: add loading bar for search page

cernopendata/modules/fixtures/data/records/cms-dimuon-spectrum-2011.json, cernopendata/modules/fixtures/data/records/cms-learning-resources.json, cernopendata/modules/fixtures/data/records/cms-open-data-instructions.json, cernopendata/modules/fixtures/data/records/cms-tools-ispy.json, cernopendata/modules/fixtures/data/records/cms-tools-reco.json
* Adds/updates the secondary type categories in various CMS records.
(closes #1956)
=> records: secondary type updates for CMS records

cernopendata/modules/fixtures/data/records/cms-csv-files.json, cernopendata/modules/fixtures/data/records/cms-derived-csv-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-masterclass-files.json
* Updates for the `usage` property in CMS csv records. (closes #2032)
=> records: updates usage information for CMS

cernopendata/templates/cernopendata_records_ui/records/dataset_detail.html, cernopendata/templates/cernopendata_records_ui/records/detail.html, cernopendata/templates/cernopendata_records_ui/records/macros/links.html, cernopendata/templates/cernopendata_records_ui/records/record_detail.html, cernopendata/templates/cernopendata_records_ui/records/software_detail.html
* Refactors link list generation (closes #1888).
=> templates: add macro for links objects

cernopendata/modules/theme/views.py, cernopendata/static/templates/search/briefs/dataset.html, cernopendata/static/templates/search/briefs/default.html, cernopendata/static/templates/search/briefs/docs.html, cernopendata/static/templates/search/briefs/record.html, cernopendata/static/templates/search/briefs/software.html, cernopendata/static/templates/search/briefs/terms.html, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
=> UI: fixes badges in search results

cernopendata/templates/cernopendata_records_ui/docs/detail.html
=> UI: adds date in news

cernopendata/modules/theme/static/scss/styles.scss, cernopendata/templates/cernopendata_records_ui/records/dataset_detail.html, cernopendata/templates/cernopendata_records_ui/records/detail.html, cernopendata/templates/cernopendata_records_ui/records/macros/files_box.html, cernopendata/templates/cernopendata_records_ui/records/record_detail.html, cernopendata/templates/cernopendata_records_ui/records/record_detail_Author-Lists.html, cernopendata/templates/cernopendata_records_ui/records/software_detail.html
* Make subtitles clearly distinguished visually from rest of the text.
(closes #1547)
=> UI: fix visual issues with dataset record

Dockerfile, cernopendata/uwsgi.ini, docker-compose.yml, requirements-production.txt, setup.py
* Adds simple uWSGI configuration, later number of processes and
threads might be tunned as well as the protocol (HTTP vs uwsgi)
(closes #2053).
=> installation: add uWSGI simple configuration

cernopendata/modules/fixtures/data/docs/cms-guide-troubleshooting/cms-guide-troubleshooting.md
Updates addressing and closing #2061
=> CMS: docs: updates to the troubleshooting guide

cernopendata/modules/fixtures/data/docs/cms-getting-started-2011/cms-getting-started-2011.md, cernopendata/modules/fixtures/data/docs/cms-guide-for-conddb/cms-guide-for-conddb.md, cernopendata/modules/fixtures/data/docs/cms-guide-for-research/cms-guide-for-research.md
Added text to the condition guide and corresponding change to 2011 getting started
=> CMS: templates: adding content to condition guide

cernopendata/modules/fixtures/data/records/cms-author-list-2012.json
* Adds one new record for the CMS 2012 author list. (closes #1963)
=> CMS: adds 2012 author list

cernopendata/modules/fixtures/data/records/cms-tools-ana-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-tools-ana.json
* Replace text "The files created are:" with just "-" in favor of list
like syntax.
(closes #1928)
=> records: remove double text in records 233 and 200

cernopendata/modules/fixtures/data/docs/cod-terms-of-use/cod-terms-of-use.md, cernopendata/modules/pages/views.py
=> views: terms of use fix

cernopendata/modules/fixtures/data/docs/cms-about/cms-about.md, cernopendata/modules/fixtures/data/docs/cms-guide-for-conddb/cms-guide-for-conddb.md, cernopendata/modules/fixtures/data/docs/cms-guide-for-education/cms-guide-for-education.md, cernopendata/modules/fixtures/data/docs/cms-guide-for-research/cms-guide-for-research.md, cernopendata/modules/fixtures/data/docs/cms-guide-troubleshooting/cms-guide-troubleshooting.md, cernopendata/modules/fixtures/data/docs/cms-virtual-machine-2010/cms-virtual-machine-2010.md, cernopendata/modules/fixtures/data/docs/cms-virtual-machine-2011/cms-virtual-machine-2011.md
* Closes #2069.
* Closes #2063.
Signed-off-by: Kati Lassila-Perini <k.lassila-perini@cern.ch>
=> CMS: docs: update list format

cernopendata/modules/fixtures/cli.py, cernopendata/templates/cernopendata_pages/front/lva.html, cernopendata/templates/cernopendata_pages/front/main.html, cernopendata/templates/cernopendata_theme/header.html
=> global: hides opera

cernopendata/config.py
=> system: FILES_REST_FILE_URI_MAX_LEN in `config.py`

cernopendata/modules/theme/views.py, cernopendata/templates/cernopendata_records_ui/records/macros/files_box.html, cernopendata/templates/cernopendata_records_ui/records/record_detail_Author-Lists.html
=> templates: updates author list

cernopendata/config.py, cernopendata/mappings/records/data-policies-v1.0.0.json, cernopendata/mappings/records/datasets-v1.0.0.json, cernopendata/mappings/records/docs-v1.0.0.json, cernopendata/mappings/records/glossary-term-v1.0.0.json, cernopendata/mappings/records/record-v1.0.0.json, cernopendata/mappings/records/software-v1.0.0.json, cernopendata/modules/records/search/__init__.py, cernopendata/modules/records/search/facets.py, cernopendata/modules/records/search/query.py, cernopendata/modules/theme/bundles.py, cernopendata/static/js/controllers/facetCtrl.js, cernopendata/static/templates/cernopendata_search_ui/facets.html, cernopendata/templates/cernopendata/search.html, requirements-devel-invenio.txt, requirements-production.txt, setup.py
* new faceting implementation with logical OR within one aggregation type, and AND for others
* add clear facet option for subaggregations
* when parent aggregation checked, check all subaggregations
* checking subaggregation automatically checks parent aggregation
* adjust mappings for Elasticsearch 5.x
=> search: New facets implementation

cernopendata/modules/fixtures/data/records/cms-dimuon-spectrum-2011.json
* Updates usage instructions and makes further smaller additions/corrections to the metadata. (closes #2052)
=> records: enriches record 5001

DEVELOPING.rst
=> docs: clarifications to Docker-based PROD and DEV workflows

cernopendata/config.py, cernopendata/templates/cernopendata_records_ui/records/macros/files_box.html
=> global: adds threshold for file download

cernopendata/modules/theme/bundles.py
* Upgrade version of ispy-webgl in bundles
* New version uses "HiggsCandidates" in file menu
* closes #534
=> CMS event display file menu

cernopendata/static/js/visualise/visualise_histograms.js, cernopendata/templates/cernopendata_pages/visualise_histograms.html
* Change button class from btn-default to btn-secondary
* Toggle behavior now behaves as expected
* btn-secondary is gray rather than btn-primary's garish blue
* closes #1890
=> Histogram buttons

Dockerfile, cernopendata/config.py, cernopendata/jsonschemas/records/docs-v1.0.0.json, cernopendata/modules/fixtures/cli.py, cernopendata/modules/fixtures/data/terms/terms.json, docker-compose-dev.yml, elasticsearch-proxy/nginx.conf, requirements-dev.txt, scripts/reindex-instance.sh
* Fix reindexing of records (`cernopendata index reindex ...`)
Co-authored-by: Alexander Ioannidis <a.ioannidis@cern.ch>
=> elasticsearch: fix reindexing of records

cernopendata/modules/fixtures/data/docs/cms-virtual-machine-2010/cms-virtual-machine-2010.md, cernopendata/modules/fixtures/data/docs/cms-virtual-machine-2011/cms-virtual-machine-2011.md
=> Kati link fixes

cernopendata/modules/fixtures/data/records/lhcb-antimatter-matters-2017.json
* Minor fix in the abstract to make the record look better.
=> records: fix for LHCb Matter Antimatter record

cernopendata/modules/theme/views.py, cernopendata/templates/cernopendata_pages/front/lva.html, cernopendata/templates/cernopendata_theme/footer.html
=> UI: small ui fixes

cernopendata/modules/fixtures/data/records/cms-tools-higgsexample20112012.json
* Adds metadata for one new file and updates `usage`. (closes #2154)
=> records: update for CMS record 5501

cernopendata/config.py, cernopendata/mappings/records/datasets-v1.0.0.json, cernopendata/mappings/records/docs-v1.0.0.json, cernopendata/mappings/records/glossary-term-v1.0.0.json, cernopendata/mappings/records/record-v1.0.0.json, cernopendata/mappings/records/software-v1.0.0.json
=> search: fix sort by title for ES5

cernopendata/modules/fixtures/data/docs/cod-about/cod-about.md
=> docs: update about COD

cernopendata/modules/fixtures/data/docs/cms-vm-validation-2010/cms-vm-validation-2010.json, cernopendata/modules/fixtures/data/docs/cms-vm-validation-2010/cms-vm-validation-2010.md, cernopendata/modules/pages/views.py
=> docs: cms vm validation report

cernopendata/modules/theme/bundles.py, cernopendata/templates/cernopendata_pages/visualise_events_cms.html, cernopendata/templates/cernopendata_pages/visualise_events_cms_standalone.html
* add missing quote for class in div
* use more space for file and event info
* changes to modals for bootstrap4
* increment version of ispy-webgl to fetch glyphicon fix
* closes #1885
* apply the above changes to non-standalone version
=> CMS event display fixes

cernopendata/modules/pages/views.py, cernopendata/templates/cernopendata_pages/visualise_events_cms_standalone.html, cernopendata/templates/cernopendata_theme/header.html
* Removes unused bundle in event display.
=> global: removes breadcrumbs

cernopendata/modules/fixtures/data/records/cms-tools-higgsexample20112012.json
=> records: fix for HTML tag in 5501

cernopendata/config.py, cernopendata/modules/fixtures/cli.py, cernopendata/modules/records/utils.py, cernopendata/modules/theme/static/scss/styles.scss, cernopendata/static/templates/downloadModal.html, cernopendata/static/templates/indexFileListModal.html, cernopendata/templates/cernopendata_records_ui/records/detail.html, cernopendata/templates/cernopendata_records_ui/records/macros/files_box.html
=> files: refactor file handling

cernopendata/modules/fixtures/data/records/cms-tools-higgsexample20112012.json
* Updates ROOT file list in CMS HiggsExample20112012 record. (closes #2184)
=> records: CMS HiggsExample20112012 ROOT file list update

cernopendata/modules/fixtures/data/docs/cms-guide-troubleshooting/cms-guide-troubleshooting.md
=> CMS: docs: small fix for trouble shooting

cernopendata/modules/fixtures/cli.py, scripts/populate-instance.sh
* Closes #2096.
***
- cernopendata fixtures docs -f /code/cernopendata/modules/fixtures/data/docs/alice-about/alice-about.json 
- cernopendata fixtures docs -f /code/cernopendata/modules/fixtures/data/docs/alice-about/alice-about.json --mode replace
***
=> cli: adds mode and file for docs

cernopendata/templates/cernopendata_records_ui/records/detail.html
=> records: fix wrong preview display

cernopendata/modules/theme/static/scss/visualise.scss, cernopendata/static/js/visualise/visualise_histograms.js
* Add a div for xlabel and use parameter description for content
* Closes #2177
=> Histogram xlabel

cernopendata/templates/cernopendata_records_ui/records/macros/links.html
=> ui: fix double links in records

cernopendata/templates/cernopendata_pages/front/main.html, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
=> UI: small ui updates

cernopendata/modules/fixtures/data/records/cms-condition-data-2012.json, cernopendata/modules/fixtures/data/records/cms-condition-data-Run2011A.json
=> records: updates for CMS condition records

cernopendata/modules/theme/static/scss/frontpage.scss, cernopendata/templates/cernopendata_pages/front/lva.html, cernopendata/templates/cernopendata_pages/front/main.html
=> front: add visible links

cernopendata/modules/theme/static/scss/styles.scss, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
=> ui: font size fixes

cernopendata/templates/cernopendata_pages/front/lva.html
=> homepage: adds links to more buttons

cernopendata/config.py
=> search: fix collections filter

cernopendata/templates/cernopendata_theme/header.html
=> templates: removal of DEMO logo

cernopendata/modules/fixtures/data/records/cms-tools-vm-image-Run2011A.json, cernopendata/modules/fixtures/data/records/lhcb-antimatter-matters-2017.json
=> records: minor cosmetic changes

cernopendata/modules/pages/views.py
=> pages: redirect research and education pages to search

cernopendata/modules/fixtures/data/records/cms-primary-datasets-Run2012B.json, cernopendata/modules/fixtures/data/records/cms-primary-datasets-Run2012C.json
=> records: addition of DOIs for CMS 2012 collision datasets

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2012.json
=> records: addition of DOIs for CMS 2012 simulated datasets

run-tests.sh
* Improves Travis CI tests by checking for the uniqueness of record DOIs and
docs slugs.
=> tests: check for DOI and slug uniqueness

cernopendata/modules/fixtures/data/docs/cms-getting-started-2011/cms-getting-started-2011.md, cernopendata/modules/fixtures/data/docs/cms-guide-troubleshooting/cms-guide-troubleshooting.md
=> docs: fix links to CMS guide to condition database

cernopendata/modules/fixtures/data/docs/observing-higgs-over-one-petabyte-new-cms-open-data/observing-higgs-over-one-petabyte-new-cms-open-data.md
=> docs: CMS 2012 release announcement fix

cernopendata/modules/fixtures/data/records/atlas-tools.json
=> records: fix for date_created in record 3850

setup.py, tests/locust/locustfile.py
=> tests: load tests using locust

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
=> docs: GitHub issue and PR templates

cernopendata/modules/records/utils.py
=> records: fix pagination issues

cernopendata/modules/fixtures/cli.py, cernopendata/modules/pages/views.py, cernopendata/templates/cernopendata_pages/front/lva.html, cernopendata/templates/cernopendata_pages/front/main.html, cernopendata/templates/cernopendata_pages/visualise_events.html, cernopendata/templates/cernopendata_theme/footer.html, cernopendata/templates/cernopendata_theme/header.html
=> global: unhides opera

cernopendata/modules/fixtures/data/records/cms-tools-ana-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-validation-code-Run2010B.json
* (closes #2260), (closes #2261)
=> records: update URLs in CMS records

cernopendata/config.py, cernopendata/modules/records/serializers/schemaorg.py, cernopendata/modules/records/serializers/schemas/__init__.py, cernopendata/modules/records/serializers/schemas/schemaorg_schemas.py, cernopendata/modules/records/utils.py, cernopendata/modules/theme/views.py, cernopendata/templates/cernopendata_pages/md_template.html, cernopendata/templates/cernopendata_records_ui/records/record_detail.html, cernopendata/templates/cernopendata_theme/page.html
* Add schema.org JSON-LD serializer
(closes #2273)
* Add schema.org JSON-LD description of Record to detail page of
Dataset and Software Records.
(closes #2275)
=> records: add schema.org json-ld serializer

cernopendata/modules/fixtures/data/records/cms-primary-datasets.json
=> records: change recommended sw release

cernopendata/modules/fixtures/data/datasets/cms-2011-collision-datasets.json, cernopendata/modules/fixtures/data/records/cms-primary-datasets-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2011A.json
=> records: change links with anchors

cernopendata/config.py, cernopendata/templates/cernopendata_theme/page.html, cernopendata/templates/cernopendata_theme/trackingcode.html
=> logs: plug piwik for live access logs monitoring

cernopendata/config.py, cernopendata/static/templates/cernopendata_search_ui/error.html, cernopendata/templates/cernopendata/search.html
=> search: nice error messages

cernopendata/config.py, cernopendata/modules/sitemap/__init__.py, cernopendata/modules/sitemap/config.py, cernopendata/modules/sitemap/ext.py, cernopendata/modules/sitemap/generators.py, cernopendata/modules/sitemap/templates/sitemap/sitemap.xml, cernopendata/modules/sitemap/views.py, setup.py
=> sitemap: add sitemap package

cernopendata/templates/cernopendata_records_ui/records/record_detail.html
=> template: show parent dataset only if present

cernopendata/modules/pages/views.py
Please start by choosing an appropriate base branch for your pull request.
- ``production`` branch: should not be used for pull requests; it is fast-forwarded to `qa` branch at chosen points in time for production deployments;
- ``qa`` branch: shorter-term rollout nature (think a few days); used for fixes and new features observed on the production service; should be a good default branch for most pull requests;
- ``master`` branch: longer-term rollout nature (think a few weeks); bigger developments that may need longer stabilisation periods and iterations with the experiments.
Please reference all issues that this PR addresses or closes. Do not forget to include ``(addresses #123)`` or ``(closes #123)`` in your commit log message. …
=> views: sanitise arguments

DEVELOPING.rst
=> docs: more developing tips

cernopendata/modules/fixtures/data/records/cms-validation-code-Run2010B.json
=> CMS: update github links in sw records

cernopendata/modules/fixtures/data/records/cms-raw-datasets-Run2011A.json, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
=> fixtures: remove additional text in description

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2011A.json, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
=> templates: display pile-up information

cernopendata/modules/fixtures/data/docs/cms-getting-started-2011/cms-getting-started-2011.md
Closes #2357
Changed the instructions as in #2318
=> CMS: small update in 2011 getting started

cernopendata/config.py, cernopendata/modules/records/serializers/__init__.py, cernopendata/modules/records/serializers/basic_json.py, cernopendata/modules/records/utils.py, docker-compose-dev.yml
This PR updates the 'BasicJSONSerializer' and effects can be seen in JSON export view of a record (```/record/NNN/export/json```). To be adopted and displayed thought our API, further steps are needed
* records: 'jsonify' JSON export
* records: update 'BasicJSONSerializer'
* dev: update 'docker-compose-dev'
=> records: file serialization

cernopendata/jsonschemas/records/docs-v1.0.0.json, cernopendata/modules/fixtures/data/docs/cms-physics-objects-2010/cms-physics-objects-2010.json, cernopendata/modules/fixtures/data/docs/cms-physics-objects-2011/cms-physics-objects-2011.json, cernopendata/modules/pages/views.py, cernopendata/modules/theme/static/scss/styles.scss, cernopendata/modules/theme/views.py, cernopendata/templates/cernopendata_records_ui/docs/detail.html
=> docs: add related field for docs

cernopendata/modules/fixtures/data/records/cms-tools-vm-image.json
=> records: updates cms-tools-vm-image

cernopendata/modules/pages/views.py
=> templates: fix old links

cernopendata/modules/pages/views.py
=> pages: add vm/validation/report link

cernopendata/modules/theme/static/scss/styles.scss, cernopendata/templates/cernopendata/search.html
Fixes problem with overlapping numbers and facets labels on some screens
=> search: better search page scaling

cernopendata/modules/fixtures/data/docs/cms-guide-troubleshooting/cms-guide-troubleshooting.md
=> docs: EOS support email address fix

cernopendata/modules/theme/bundles.py, cernopendata/templates/cernopendata_pages/visualise_events_opera.html
=> opera: updates opera previewer

cernopendata/modules/theme/bundles.py, cernopendata/templates/cernopendata_pages/visualise_events_opera.html
=> opera: bumps version in previewer

cernopendata/modules/fixtures/data/records/opera-ecc-datasets.json, cernopendata/modules/fixtures/data/records/opera-ed-datasets.json
* Adds information about attached tarball files.
* Enriches desciption with links to the ten individual events.
* Adds initial validation information for the tau candidate ED
dataset. (addresses #2378)
=> records: richer OPERA tau dataset description

cernopendata/modules/fixtures/data/records/opera-author-list-multiplicity.json, cernopendata/modules/fixtures/data/records/opera-author-list-tau.json
* Adds one file for the second OPERA author list
* Updates file information for the first author list
=> records: new author list file for OPERA

cernopendata/modules/fixtures/data/docs/opera-news-first-release/opera-news-first-release.json
* Updates OPERA release date to the tentative 24 May.
=> docs: OPERA release date

cernopendata/modules/fixtures/data/docs/opera-news-first-release/opera-news-first-release.json
* Updates OPERA release date to the final 22 May.
=> docs: final OPERA release date

cernopendata/modules/theme/bundles.py
=> opera: last update on previewer

cernopendata/modules/fixtures/data/records/data-policies.json
=> records: new CMS data policy

cernopendata/modules/fixtures/data/records/cms-learning-resources.json, cernopendata/modules/fixtures/data/records/cms-open-data-instructions-2017.json
* (closes #2422) (closes #2429)
=> records: fixes to urls

cernopendata/modules/fixtures/data/docs/cms-mc-production-overview/cms-mc-production-overview.md
Changes due to @katilp feedback
=> docs: improve cms-mc-production-overview

cernopendata/modules/fixtures/data/docs/cms-getting-started-2011/cms-getting-started-2011.md, cernopendata/modules/fixtures/data/docs/simulated-dataset-categories/simulated-dataset-categories.md
=> docs: markdown fixes in cms getting started 2011

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2012.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2011A.json
Co-authored-by: Heitor Pascoal de Bittencourt <heitor.bittencourt@cern.ch>
=> records: CMS 2012 MC dataset categories

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2011A.json
=> records: cms mc 2011 new dataset

cernopendata/templates/cernopendata_records_ui/records/record_detail.html
- Change "How were these data selected" to "How were these data generated" for MC. Fix #2470
- add "Recommended release for analysis:" to System details   for MC
- change display of "Characteristics" as in figure below (old to left, new to right):
=> record-template: changes to improve readability

cernopendata/modules/theme/static/scss/styles.scss, cernopendata/static/templates/search/briefs/record.html, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
* Displays category and subcategory badges in brief and detailed record output
formats. (closes #2487)
=> templates: category and subcategory badges

cernopendata/templates/cernopendata_records_ui/records/record_detail.html
* Fixes display of detailed record pages. (closes #2498)
=> templates: conditional display of category badges

cernopendata/modules/fixtures/data/docs/cms-guide-for-conddb/cms-guide-for-conddb.md
=> Add new GTs to condition data documentation

cernopendata/jsonschemas/records/record-v1.0.0.json
Adding dataset generation steps under methodology in data model (schema), closing #2529
=> models: add generation steps within methodology

cernopendata/modules/fixtures/data/docs/cms-getting-started-2011/cms-getting-started-2011.md, cernopendata/modules/fixtures/data/docs/cms-guide-for-conddb/cms-guide-for-conddb.md, cernopendata/modules/fixtures/data/docs/cms-virtual-machine-2011/cms-virtual-machine-2011.md
This addresses the changes in documentation due to addition of new VM version (#2426)
=> Update documentation files for the new VM version

cernopendata/modules/fixtures/data/docs/cms-guide-trigger-system/cms-guide-trigger-system.md
``(closes #2460)`` 
needs (FIXME) the record id for HLT listing for 2010 from PR  #2461
=> add explanation about the HLT path definition

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2-datascience.json
Releasing Run2 machine learning records (references #2525)
=> records: add Run2 machine learning samples

cernopendata/modules/theme/bundles.py, cernopendata/modules/theme/static/scss/styles.scss, cernopendata/static/templates/filePreviewModal.html, cernopendata/templates/cernopendata_records_ui/records/detail.html, cernopendata/templates/cernopendata_records_ui/records/record_detail.html, cernopendata/templates/cernopendata_theme/page.html, setup.py
=> records: adds filePreviewer for methodologies

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2012.json
=> records: CMS MC 2012 methodology steps fix

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2-datascience.json
=> records: CMS Run2 datascience methodology steps fix

cernopendata/modules/theme/static/scss/styles.scss, cernopendata/static/templates/cernopendata_search_ui/facets.html, cernopendata/templates/cernopendata/search.html
=> search: fixes facet sidebar for long names

cernopendata/modules/theme/bundles.py, cernopendata/modules/theme/static/scss/styles.scss, cernopendata/static/templates/filePreviewModal.html, cernopendata/templates/cernopendata_records_ui/records/detail.html
=> ui: file preview modal "copy to clipboard" button

cernopendata/jsonschemas/records/record-v1.0.0.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2012.json
=> records: add an example ondemand 2012 MC

cernopendata/static/templates/filePreviewModal.html, cernopendata/templates/cernopendata_records_ui/records/detail.html
=> records: codemirror - ablility to copy selected text

cernopendata/modules/theme/static/scss/styles.scss, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
=> templates: add disclaimer for "ondemand" records

cernopendata/modules/fixtures/data/records/cms-derived-Run2-datascience.json
=> records: add data science jettuples

cernopendata/templates/cernopendata_records_ui/records/record_detail.html
=> templates: add tabular semantic display

cernopendata/modules/theme/static/scss/styles.scss, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
* Display keyword badges after category badges. (Closes #2581) 
Signed-off-by: Jan Okraska <jan.okraska@cern.ch>
=> templates: display keywords badges

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2-datascience.json
=> records: amend Run2 datascience abstract description

cernopendata/config.py, cernopendata/mappings/records/record-v1.0.0.json, cernopendata/modules/records/search/facets.py, cernopendata/modules/records/search/query.py, cernopendata/static/templates/cernopendata_search_ui/facets.html
=> search: filter away on-demand datasets

cernopendata/modules/fixtures/data/records/cms-derived-Run2-datascience.json
=> records: fixes for record 12100

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2010.json
=> records: add methodology steps for 2010 simulated

cernopendata/modules/fixtures/data/records/cms-derived-Run2-datascience.json, cernopendata/templates/cernopendata_records_ui/records/record_detail.html, scripts/clean_json_file.py
WIP (addresses #2574)
needs:
- update of abstract
- fixes in dataset semantics 
- links in md format in descriptions
- special characters eta, delta (and > < ? ) in description
- quotes in variable
- files to be copied from eosfnal
- can isChildOf be a list?
=> Add record for Run2 Hbb ML files

cernopendata/modules/fixtures/data/records/atlas-higgs-challenge-2014.json, cernopendata/modules/fixtures/data/records/cms-tools-Run1-datascience.json, cernopendata/modules/fixtures/data/records/cms-tools-Run2-datascience.json, cernopendata/templates/cernopendata_pages/front/main.html
* records: ATLAS Higgs Challenge datascience keyword
* templates: focus on data science
=> templates: focus on data science

cernopendata/modules/fixtures/data/records/cms-tools-Phase2-datascience.json, cernopendata/modules/fixtures/data/records/cms-tools-Run1-datascience.json, cernopendata/modules/fixtures/data/records/cms-tools-Run2-datascience.json
(addresses #2589 )
Add SW record for the Phase2 (upgrade) ML producer example
Needs:
- fix latex in abstract description if needed (`$\eta$, $\phi$ and $r$`)
- recids for input datasets
- final github repo location and zip
- orcid's
=> Add SW record for upgrade ML example

cernopendata/modules/fixtures/data/records/cms-derived-Run2-datascience.json
(closes #2614 )
Two corrections in data semantics and an addition in the description
=> Fixes in jt tuple ML record

cernopendata/modules/fixtures/data/records/cms-derived-Phase2-datascience.json, cernopendata/modules/fixtures/data/records/cms-derived-Run2-datascience.json, cernopendata/modules/fixtures/data/records/cms-tools-Phase2-datascience.json
(closes #2625)
updates
- usage description for Hbb ML file record
- fixes typos in the description and wrong provenance for tracking ML file record
- update titles or Run2 ML file records
- updates CMSSW version, add output and fixes input data for tracking ML SW records
=> records: updates to ML records

cernopendata/modules/fixtures/data/records/cms-derived-Run2-datascience.json
=> records: update title in Run2 jet tuple ML file

cernopendata/templates/cernopendata_theme/header.html
=> templates: outage warning OTG0049024

cernopendata/templates/cernopendata_theme/header.html
=> templates: outage warning OTG0049024 ends

cernopendata/templates/cernopendata/search.html
=> search: fix collision type facet

cernopendata/modules/fixtures/data/docs/cms-guide-trigger-system/cms-guide-trigger-system.md
(closes #2460)
Adds the correct recid 1699 for the 2010 HLT information
=> docs: fixes recid for the HLT information

cernopendata/modules/fixtures/data/records/cms-validated-runs.json
(addresses #2648)
Updates the description with RunA run numbers
=> reocrds: update the description to include RunA

cernopendata/modules/fixtures/data/docs/cms-about/cms-about.md, cernopendata/modules/fixtures/data/docs/cms-getting-started-2010/cms-getting-started-2010.md, cernopendata/modules/fixtures/data/docs/cms-getting-started-2011/cms-getting-started-2011.md, cernopendata/modules/fixtures/data/docs/cms-guide-docker/cms-guide-docker.json, cernopendata/modules/fixtures/data/docs/cms-guide-docker/cms-guide-docker.md, cernopendata/modules/fixtures/data/docs/cms-guide-for-research/cms-guide-for-research.md
* Create a new docker instructions page
* Reference this page in the appropriate places
* Closes #2523
=> Instructions for using CMS code in a docker container

cernopendata/modules/fixtures/data/docs/cms-about/cms-about.md, cernopendata/modules/fixtures/data/docs/cms-guide-for-conddb/cms-guide-for-conddb.md, cernopendata/modules/fixtures/data/docs/cms-guide-for-research/cms-guide-for-research.md
Updates the policy link to the new versions and add a notion of 2010 MC and datasets on demand.
- (closes #2524)
Updates OpenData vs Open-Data in the condition db instructions
- (addresses #2426)
=> docs: update policy, add a mention of MC

cernopendata/modules/fixtures/data/records/cms-primary-datasets-Commissioning2010.json
(closes #2606)
Updates 
- the description of the datasets (taken into account https://github.com/cernopendata/opendata.cern.ch/issues/2606#issuecomment-499881646)
- updates the recid's for validated runs
=> records: updates to commisioning records

cernopendata/modules/fixtures/data/docs/cms-guide-event-production/cms-guide-event-production.json, cernopendata/modules/fixtures/data/docs/cms-guide-event-production/cms-guide-event-production.md, cernopendata/modules/fixtures/data/records/cms-tools-eventproduction-examples.json
Pull request for md and json file for cms-guide-event-production instructions and SW record cms-tools-eventproduction-examples.json for examples
=> Add cms event production documentation (addresses #2344)

cernopendata/modules/fixtures/data/records/cms-tools-vm-image-2012.json, cernopendata/modules/fixtures/data/records/cms-tools-vm-image-Run2011A.json
* Adds new CMS VM image 1.5.1 OVA file. (addresses #2426)
=> records: new CMS VM image 1.5.1

cernopendata/modules/fixtures/data/records/cms-raw-datasets-Run2010B.json, cernopendata/modules/fixtures/data/records/cms-raw-datasets-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-raw-datasets-Run2012B.json
Adds Run1 RAW - addresses #2439 
- needs recid's and DOIs for (4 new record 2010, 5 new records 2011, 6 new records 2012)
- needs config files added, (edit:) get them from the list in the comment below
- needs n of files and size
Adds also the methodology and a link to trigger configuration for 2010 RAW (in the same way as now in 2010 AOD)
=> Add Run1 RAW

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Phase2-datascience.json
(closes #2668)
Corrects categorization to Minimum Bias (like in all other MB records)
=> records: fix Minimum bias -> Minimum Bias

cernopendata/modules/fixtures/data/records/cms-condition-data-2012.json, cernopendata/modules/fixtures/data/records/cms-condition-data-Phase2-datascience.json, cernopendata/modules/fixtures/data/records/cms-condition-data-Run2-datascience.json, cernopendata/modules/fixtures/data/records/cms-condition-data-Run2010B.json, cernopendata/modules/fixtures/data/records/cms-condition-data-Run2011A.json
(closes #2456)
(closes #2443) 
- removes the attached files from the condition data records
- changes the text to reflect that the file are not in the record but available in /cvmfs
- adds a record for 2010 simulated data
- adds RunA of 2010 to records
=> records: update cond data description

cernopendata/modules/fixtures/data/records/cms-tools-vm-image-Run2011A.json
=> records: CMS VM image 1.5.1 file name fix

cernopendata/modules/fixtures/data/records/cms-derived-nanoaod-outreach-DoubleMuParked.json, cernopendata/modules/fixtures/data/records/cms-tools-nanoaod-outreach-dimuon-spectrum.json
Hi,
I've added records for the dimuon analysis, the used derived dataset and the tool for AOD to NanoAOD conversion in the context of education and outreach.
I couldn't figure out a few things:
1. How can I link this with a DOI?
2. How to I select the `recid` for the records?
3. Is it encouraged to put `https://...` path in the `files` sections?
Thanks!
=> records: Dimuon analysis with reduced NanoAOD dataset

cernopendata/modules/fixtures/data/records/cms-primary-datasets-Commissioning2010.json, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
* Fixes display of recommended release for reconstruction (RAW) and
analysis (everything else).  (closes #2660)
* Amends several metadata records to remove leading quote from global tag value.
=> templates: recommended release and global tag

cernopendata/modules/fixtures/data/records/cms-raw-datasets-Run2010B.json, cernopendata/modules/fixtures/data/records/cms-raw-datasets-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-raw-datasets-Run2012B.json
(closes #2439)
Adds the link to the RAWtoAOD config for all RAW records
=> records: add RAWtoAOD example config to usage for RAW records

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run1-datascience.json
=> records: CMS Run1 datascience QCD600to3000 underscore fix

cernopendata/modules/fixtures/data/records/cms-validated-runs-Commissioning2010-castor.json
=> records: CMS Commissioning10 validated runs file fix

cernopendata/modules/fixtures/data/records/cms-derived-csv-2012.json
* (closes #1410)
Signed-off-by: Artemis Lavasa <artemis.lavasa@cern.ch
=> records: add record for Higgs candidate events

cernopendata/modules/fixtures/data/records/cms-pileup-datasets-2011.json, cernopendata/modules/fixtures/data/records/cms-pileup-datasets-2012.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run1-datascience.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2-datascience.json
(addresses #2692)
Adds system details to Run2 datascience simulated data
=> records: add system details to MC

cernopendata/modules/fixtures/data/records/cms-derived-Phase2-datascience.json
(closes #2576 
Adds the link to the example repository
=> records: add example notebook link

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Phase2-datascience.json
(closes #2520)
Adds files indexes to upgrade MC records
Removes trailing` /` from a file name
=> records: add file indexes to ML MC

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2010-commissioning.json
Adds files indexes to CASTOR MC simulated dataset records
=> records: add file indexes to CASTOR MC

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2010-commissioning.json
(closes #2720)
Updates event number, file number and size for record 14100
- event number, see #2720 
- file number and size, see #2719
=> records: update events, files, size for record 14100

cernopendata/templates/cernopendata_pages/front/main.html
* We have just reached the two petabyte total size.
=> templates: more than two petabytes

cernopendata/jsonschemas/records/record-v1.0.0.json, cernopendata/modules/fixtures/data/records/cms-tools-Phase2-datascience.json, cernopendata/modules/fixtures/data/records/cms-tools-Run1-datascience.json, cernopendata/modules/fixtures/data/records/cms-tools-Run2-datascience.json, cernopendata/modules/fixtures/data/records/cms-tools-ana-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-tools-ana.json, cernopendata/modules/fixtures/data/records/cms-tools-cmssw-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-tools-cmssw.json, cernopendata/modules/fixtures/data/records/cms-tools-dimuon-filter.json, cernopendata/modules/fixtures/data/records/cms-tools-eventproduction-examples.json, cernopendata/modules/fixtures/data/records/cms-tools-higgsexample20112012.json, cernopendata/modules/fixtures/data/records/cms-tools-ispy-2012.json, cernopendata/modules/fixtures/data/records/cms-tools-ispy-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-tools-ispy.json, cernopendata/modules/fixtures/data/records/cms-tools-nanoaod-outreach-dimuon-spectrum.json, cernopendata/modules/fixtures/data/records/cms-tools-reco.json, cernopendata/modules/fixtures/data/records/cms-trigger-examples.json, cernopendata/modules/fixtures/data/records/cms-validation-code-Run2010B.json, cernopendata/modules/fixtures/data/records/cms-validation-code-jet-tuple.json, cernopendata/modules/fixtures/data/records/cms-validation-code-ttbar.json, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
(closes #2621)
- adds `source_code_repository` field to CMS tools/validation SW records
- removes `links` field in some records
- fixes a file path in a NanoAOD record
=> records: add source code repository json field

cernopendata/modules/fixtures/data/records/cms-hlt-configuration-files-2010.json
* Adds CMS 2010 HLT configuration file records. (addresses #2657)
=> records: CMS 2010 HLT configuration files

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2010.json
* Adds file indexes to CMS 2010 MC records. (closes #2339)
=> records: CMS 2010 MC file indexes

cernopendata/modules/fixtures/data/records/cms-derived-Run2-datascience.json
(closes #2739)
Adds number of entries to record 12100.
This is the number of entries in each of the two sets of files, root and h5.
=> records: add number of entries

MANIFEST.in, cernopendata/modules/pages/views.py, cernopendata/templates/cernopendata_pages/robots.txt
=> robots: introduces robots.txt

cernopendata/modules/fixtures/data/docs/cms-guide-docker/cms-guide-docker.md
Removing the pointers to my personal docker hub (the ones to my github repository will have to remain in place).
Closes #2734
=> Point to cmsopendata organisation in docker hub

scripts/clean_json_file.py
* Amends those CMS 2012 MC records that have already been transferred.
(addresses #2741)
* Simplifes JSON cleaning script.
=> records: CMS 2012 MC ondemand -> available

cernopendata/modules/fixtures/data/records/cms-primary-datasets.json
(closes #2753)
Corrects number of files in recid 13 to 138.
=> records: correct n of files recid 13

cernopendata/modules/fixtures/data/records/cms-derived-Phase2-datascience.json, cernopendata/modules/fixtures/data/records/cms-derived-Run1-datascience.json, cernopendata/modules/fixtures/data/records/cms-derived-Run2-datascience.json, cernopendata/modules/fixtures/data/records/cms-primary-datasets-Commissioning2010.json, cernopendata/modules/fixtures/data/records/cms-primary-datasets.json, cernopendata/modules/fixtures/data/records/cms-raw-datasets-Run2010B.json, cernopendata/modules/fixtures/data/records/cms-raw-datasets-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-raw-datasets-Run2012B.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2010-commissioning.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Phase2-datascience.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run1-datascience.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2-datascience.json, cernopendata/modules/fixtures/data/records/cms-tools-Phase2-datascience.json, cernopendata/modules/fixtures/data/records/cms-tools-Run1-datascience.json, cernopendata/modules/fixtures/data/records/cms-tools-Run2-datascience.json
=> records: DOIs for the new CMS release

cernopendata/modules/fixtures/data/records/cms-raw-datasets-Run2010B.json
(closes #2757)
Fixes the wrong data taking year for recid 44 (2010 RAW)
=> records: fixes data taking year for recid 44

cernopendata/modules/fixtures/data/docs/cms-guide-trigger-system/cms-guide-trigger-system.md
=> docs: fix typo

cernopendata/modules/fixtures/data/records/cms-derived-nanoaod-outreach-DoubleMuParked.json
(addresses #2763)
Adds data-taking year (2012) to derived data record 12341
=> records: adds data-taking year

scripts/check_fixtures.py
* Initial simple version of the record fixture checking script.
(addresses #2763)
=> scripts: check fixtures

cernopendata/modules/datacite/cli.py, cernopendata/modules/datacite/serializers.py
* Fixes detection of datasets and software for proper Datacite
serialisation. (closes #2762)
=> datacite: fix ResourceType serialisation

README.rst
- The service no longer works
- The domain is no longer controlled by the original developers
=> Remove issuestats badges from README

cernopendata/modules/fixtures/data/docs/cms-virtual-machine-2010/cms-virtual-machine-2010.md, cernopendata/modules/fixtures/data/docs/cms-virtual-machine-2011/cms-virtual-machine-2011.md
(closes #2630)
Adds instructions how to import VM on VirtualBox 6 versions
=> docs: update FAQ for VM

cernopendata/modules/fixtures/data/records/cms-derived-nanoaod-outreach-higgstautau.json, cernopendata/modules/fixtures/data/records/cms-tools-nanoaod-outreach-higgstautau.json
PR to include the outreach analysis of a Higgs boson decaying into two tau leptons
The issue for discussion is #2777.
=> CMS: Higgs boson to two tau leptons outreach analysis

cernopendata/modules/theme/bundles.py, cernopendata/templates/cernopendata_pages/visualise_events_opera.html
Closes #2804 
⚠️ We shouldn't forget to update the demobbded-viewer version at the end of the sprint as stated in https://github.com/cernopendata/opendata.cern.ch/issues/2813
=> OPERA: respect event parameter

cernopendata/modules/fixtures/data/records/opera-detector-events-charm.json, cernopendata/modules/fixtures/data/records/opera-detector-events-tau.json, cernopendata/modules/fixtures/data/records/opera-ecc-datasets.json, cernopendata/modules/fixtures/data/records/opera-ed-datasets.json
Adds records generated by cernopendata/data-curation#59
=> records: OPERA neutrino-induced charm production

cernopendata/modules/theme/bundles.py, cernopendata/templates/cernopendata_pages/visualise_events_opera.html
Related to https://github.com/cernopendata/demobbed-viewer/pull/6
Closes #2803
=> opera: adapt event display to newest version

cernopendata/templates/cernopendata_pages/visualise_events_opera.html
Related to https://github.com/cernopendata/demobbed-viewer/pull/7
=> opera: improve help

cernopendata/modules/fixtures/data/records/opera-detector-events-charm.json, cernopendata/modules/fixtures/data/records/opera-detector-events-electron.json, cernopendata/modules/fixtures/data/records/opera-ecc-datasets.json, cernopendata/modules/fixtures/data/records/opera-ed-datasets.json
=> records: OPERA nuE dataset descriptions

cernopendata/modules/fixtures/data/docs/atlas-13tev-open-data-release-2020/atlas-13tev-open-data-release-2020.json, cernopendata/modules/fixtures/data/docs/atlas-13tev-open-data-release-2020/atlas-13tev-open-data-release-2020.md, cernopendata/modules/fixtures/data/docs/cms-observing-higgs-2017/cms-observing-higgs-2017.json, cernopendata/modules/fixtures/data/docs/cms-releases-open-data-for-machine-learning-2019/cms-releases-open-data-for-machine-learning-2019.json, cernopendata/modules/fixtures/data/docs/opera-news-first-release/opera-news-first-release.json, cernopendata/modules/fixtures/data/records/atlas-2020-1largeRjet1lep.json, cernopendata/modules/fixtures/data/records/atlas-2020-1lep.json, cernopendata/modules/fixtures/data/records/atlas-2020-1lep1tau.json, cernopendata/modules/fixtures/data/records/atlas-2020-2lep.json, cernopendata/modules/fixtures/data/records/atlas-2020-3lep.json, cernopendata/modules/fixtures/data/records/atlas-2020-4lep.json, cernopendata/modules/fixtures/data/records/atlas-2020-GamGam.json, cernopendata/modules/fixtures/data/records/atlas-2020-exactly2lep.json, cernopendata/modules/fixtures/data/records/atlas-2020-vm.json
Co-authored-by: Tibor Šimko <tibor.simko@cern.ch>
=> records: new ATLAS 13TeV open data release

cernopendata/modules/fixtures/data/docs/opera-releases-charm-nue-samples-2020/opera-releases-charm-nue-samples-2020.md, cernopendata/modules/fixtures/data/records/opera-detector-events-charm.json, cernopendata/modules/fixtures/data/records/opera-detector-events-electron.json, cernopendata/modules/fixtures/data/records/opera-ecc-datasets.json, cernopendata/modules/fixtures/data/records/opera-ed-datasets.json, cernopendata/modules/fixtures/data/terms/terms.json
- docs: OPERA release statement updates
- terms: addition of OPERA-related terms
- records: DOIs for OPERA charm and nu_e data
=> OPERA charm and nu_e release updates

cernopendata/modules/fixtures/data/records/cms-primary-datasets-Run2011B.json
=> records: CMS 2011 RunB collision datasets

cernopendata/modules/fixtures/data/records/cms-primary-datasets.json
(closed #2857)
Fixes the wrong run period for 2010 ZeroBias
=> Fix run_period for zerobias

Dockerfile
=> Upgrade xroot version -> 4.12.3

cernopendata/modules/fixtures/data/records/cms-validated-runs.json
(closes #2862)
Updates validated runs description with RunB event range. No changes in the file needed.
=> Update 2011 validated run description

cernopendata/modules/fixtures/data/records/cms-tools-higgsexample20112012.json, cernopendata/modules/fixtures/data/records/cms-tools-nanoaod-outreach-dimuon-spectrum.json, cernopendata/modules/fixtures/data/records/cms-tools-nanoaod-outreach-higgstautau.json
(addresses #2867)
Add Workflow tags to 3 SW records. 
The CASTOR update goes to #2859
=> Add workflow tag

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2-datascience.json
=> Fix title in provenance

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2-datascience.json
fixes records 12301, 12303 provenance
=> Fix ML prov again

cernopendata/config.py, cernopendata/jsonschemas/records/record-v1.0.0.json, cernopendata/mappings/records/record-v1.0.0.json, cernopendata/modules/fixtures/data/records/cms-derived-csv-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-masterclass-files.json, cernopendata/templates/cernopendata/search.html
- Adds 'signature'-facet to Open Data Portal.
- Adds 'signature'-field to educational records
(closes cernopendata#2783)
Signed-off-by: Juha-Matti Teuho <juha.teuho@gmail.com>
=> facets: Add 'signature' -facet

cernopendata/modules/fixtures/data/docs/cod-about/cod-about.md, cernopendata/templates/cernopendata_theme/footer.html, cernopendata/templates/cernopendata_theme/header.html
- templates: advertise help and social channels in header/footer
- docs: refresh "About CERN Open Data" page content
Closes #2855.
=> templates: advertise help and social channels in header/footer

cernopendata/modules/fixtures/data/records/cms-trigger-examples.json
Closes #2878.  It still needs the proper new file checksum (included a FIXME note) and size (I gave the number I got with a manual tar balling).
=> Update triggerinfo records

cernopendata/modules/fixtures/data/docs/cms-guide-luminosity-calculation/cms-guide-luminosity-calculation.json, cernopendata/modules/fixtures/data/docs/cms-guide-luminosity-calculation/cms-guide-luminosity-calculation.md
* Instructions for calculating luminosity in the CMS open data environment
* closes #2845
=> CMS luminosity calculcation

cernopendata/jsonschemas/records/record-v1.0.0.json
=>  records: add support for ROR IDs in the schema

AUTHORS.rst, Dockerfile
=> docker: upgrade to xrootd 4.12.5

.github/workflows/ci.yml, Dockerfile, run-tests.sh
=> ci: added hadolint for Dockerfile linting, improved github actions workflow

cernopendata/modules/fixtures/data/records/cms-validated-runs-HIRun1.json
(closes #2908 and https://github.com/cernopendata/data-curation/issues/85)
Needs:
- files upload from  https://cernbox.cern.ch/index.php/s/D236HWZGuMOnSZB
=> CMS: HI validated runs

cernopendata/modules/fixtures/data/records/cms-primary-datasets-HIpp-Run2011A.json
(close #2916)
Adds 6 pp records from Run2011A, reference data for HI analysis
=> Run2011A pp HI ref datasets

cernopendata/modules/fixtures/data/records/cms-derived-Run2-datascience.json
- Small update to add descriptions of labels
- Fix to one of the data types
=> records: Update cms-derived-Run2-datascience

cernopendata/modules/fixtures/data/records/cms-primary-datasets-HIRun2011.json
(closes #2913 )
Add 4 2011 PbPb records + 1 interfill record
To fix: recids for the config files (see #2914), now 0000
=> CMS - HIRun2011 datasets

cernopendata/modules/fixtures/data/records/cms-primary-datasets-HIRun2010.json
(closes #2939)
Add HLT trigger paths to the 2010 HI records. No links, just listing
=> CMS: Add HLT paths

cernopendata/modules/fixtures/data/records/cms-tools-heavyion-examples.json
(addresses #2946 )
Adds two software records for HI data
To do after a review of the records on dev by the authors and once the code is ready:
- update links 
- add zip file from the repository
=> CMS: add HI sw records

cernopendata/modules/fixtures/data/records/cms-tools-heavyion-examples.json
Fixes the VM link for recid 467
closes #2949
=> CMS: Fix VM link in HI sw record

cernopendata/modules/fixtures/data/records/cms-tools-heavyion-examples.json
(closes #2956)
Fixes the VM link in recid 467
=> CMS: fix VM link

cernopendata/modules/fixtures/data/docs/cms-guide-for-conddb/cms-guide-for-conddb.md
(closes #2954 )
- adds subsection for pp and HI
- adds HI GTs
=> CMS: add HI GTs to cond data guide

cernopendata/modules/fixtures/data/records/cms-tools-heavyion-examples.json
(closes #2960 )
Updates links to the new branch names
=> CMS: update repository links

cernopendata/modules/fixtures/data/docs/cms-about/cms-about.md
closes #2951 
Adds a mention to RECO for data formats
=> CMS: add mention to RECO

cernopendata/modules/fixtures/data/records/data-policies.json
Contains minor changes. Attaching to the previous record after
discussion with LHCb. Closes #2927.
=> records: LHCb Data Policy update

cernopendata/modules/fixtures/data/docs/atlas-about/atlas-about.md
Dear developers,
This PR is related (and solve) issue #2937.
I hope I follow the contribution guidelines correctly.
Thanks and cheers,
Arturo
=> Update ATLAS about page

cernopendata/modules/fixtures/data/records/cms-validated-runs-HIRun1.json
=> records: fix CMS HI validated run files

cernopendata/modules/fixtures/data/docs/cern-open-data-policy-for-lhc-experiments/cern-open-data-policy-for-lhc-experiments.json, cernopendata/modules/fixtures/data/docs/cms-completes-2010-2011-pp-data/cms-completes-2010-2011-pp-data.json, cernopendata/modules/fixtures/data/docs/cms-releases-heavy-ion-data/cms-releases-heavy-ion-data.json, cernopendata/modules/fixtures/data/docs/cms-releases-heavy-ion-data/cms-releases-heavy-ion-data.md, cernopendata/modules/fixtures/data/docs/opera-releases-charm-nue-samples-2020/opera-releases-charm-nue-samples-2020.json
How does this look, @tiborsimko? I just realised that I authored it as one sentence on one line. Will this break the display? I can switch to making a single line for each paragraph if needed.
=> Add CMS HI release

cernopendata/modules/fixtures/data/docs/cms-releases-heavy-ion-data/cms-releases-heavy-ion-data.md
I caught a typo earlier and took the opportunity to also fix some typography in the original Markdown.
=> docs: Fix typo in CMS HI announcement

cernopendata/modules/fixtures/data/records/atlas-2020-1largeRjet1lep.json, cernopendata/modules/fixtures/data/records/atlas-2020-1lep.json, cernopendata/modules/fixtures/data/records/atlas-2020-1lep1tau.json, cernopendata/modules/fixtures/data/records/atlas-2020-2lep.json, cernopendata/modules/fixtures/data/records/atlas-2020-3lep.json, cernopendata/modules/fixtures/data/records/atlas-2020-4lep.json, cernopendata/modules/fixtures/data/records/atlas-2020-GamGam.json, cernopendata/modules/fixtures/data/records/atlas-2020-exactly2lep.json, cernopendata/modules/fixtures/data/records/atlas-2020-vm.json
Updates ATLAS 13TeV dataset files. Amends file information. Mints DOIs.
Closes #2926.
=> records: ATLAS 13TeV dataset updates

cernopendata/modules/fixtures/data/docs/cms-releases-heavy-ion-data/cms-releases-heavy-ion-data.md
=> docs: Update link to HI records in CMS news

Dockerfile
=> dockerfile: run application as Invenio user

DEVELOPING.rst
=> dev: enrich developing.rst with webpack commands

requirements-production.txt, setup.py
=> installation: upgrade Invenio-Records-UI

requirements-production.txt, setup.py
=> installation: upgrade Invenio-Previewer

cernopendata/modules/theme/bundles.py, cernopendata/templates/cernopendata_pages/visualise_events_opera.html, scripts/create-instance.sh
=> ui: migrate Opera visualiser bundle from using NpmBundle

cernopendata/modules/theme/assets/semantic-ui/less/cernopendata/site/globals/site.overrides, cernopendata/modules/theme/assets/semantic-ui/less/cernopendata/site/globals/site.variables, cernopendata/modules/theme/assets/semantic-ui/scss/footer.scss, cernopendata/modules/theme/assets/semantic-ui/scss/frontpage.scss, cernopendata/modules/theme/assets/semantic-ui/scss/header.scss, cernopendata/modules/theme/assets/semantic-ui/scss/styles.scss, cernopendata/modules/theme/assets/semantic-ui/scss/variables.scss, cernopendata/modules/theme/bundles.py, cernopendata/templates/cernopendata_pages/front/index.html, cernopendata/templates/cernopendata_pages/front/lva.html, cernopendata/templates/cernopendata_pages/front/main.html, cernopendata/templates/cernopendata_pages/front/news.html, cernopendata/templates/cernopendata_pages/index.html, cernopendata/templates/cernopendata_theme/footer.html, cernopendata/templates/cernopendata_theme/header.html, cernopendata/templates/cernopendata_theme/page.html, setup.py
- layout: adapt header to semantic-ui
- layout: adapt footer to semantic-ui
- layout: adapt main.html to semantic-ui
- layout: adapt LVA section to semantic-ui
- layout: adapt news section to semantic-ui
closes #3006
https://user-images.githubusercontent.com/8863238/105725170-eaf22380-5f28-11eb-9508-c8d21b328f88.mov
=> layout: migrate frontpage elements to semantic-ui

cernopendata/templates/cernopendata_records_ui/records/detail.html, cernopendata/templates/cernopendata_records_ui/records/record_detail.html, cernopendata/templates/cernopendata_records_ui/records/record_detail_Author-Lists.html
* Closes #3012
* Closes #3013 
Depends on https://github.com/cernopendata/opendata.cern.ch/pull/3017.
To be tested with any record and author lists such as http://opendata.cern.ch/record/454.
Note: this PR doesn't fix the file download boxes (will be handled as part of https://github.com/cernopendata/opendata.cern.ch/issues/3010).
=> frontend: migrate record details to Semantic UI

MANIFEST.in, cernopendata/config.py, cernopendata/modules/search_ui/__init__.py, cernopendata/modules/search_ui/helpers.py
- needed in particular for event number filter of type range
closes #3021
=> search-ui: support multiple aggregation types

cernopendata/modules/theme/assets/semantic-ui/js/visualise/visualise_histograms.js, cernopendata/modules/theme/assets/semantic-ui/scss/visualise.scss, cernopendata/modules/theme/bundles.py, cernopendata/modules/theme/webpack.py, cernopendata/templates/cernopendata_pages/histograms_howto.html, cernopendata/templates/cernopendata_pages/visualise_histograms.html, setup.py
* Closes #3005 
* Addresses https://github.com/cernopendata/opendata.cern.ch/issues/2997
To test locally:
```
$ docker-compose exec web cernopendata fixtures records -f /code/cernopendata/modules/fixtures/data/records/cms-masterclass-files.json --mode insert-or-replace
$ docker-compose exec web cernopendata fixtures records -f /code/cernopendata/modules/fixtures/data/records/cms-csv-files.json --mode insert-or-replace
$ firefox http://0.0.0.0:5000/visualise/histograms
$ # to compare with http://opendata.cern.ch/visualise/histograms
```
Note: you might have problems with downloading files due to https://github.com/cernopendata/opendata.cern.ch/issues/3035. Restart the web app if that happens `docker-compose restart web`.
=> frontend: histogram visualiser to Semantic UI

cernopendata/modules/theme/assets/semantic-ui/js/search/app.js, cernopendata/modules/theme/assets/semantic-ui/js/search/components/DefaultListItem.js, cernopendata/modules/theme/assets/semantic-ui/js/search/components/ResultsCount.js, cernopendata/modules/theme/assets/semantic-ui/scss/header.scss, cernopendata/modules/theme/assets/semantic-ui/scss/search.scss, cernopendata/modules/theme/webpack.py, cernopendata/templates/cernopendata_search_ui/search.html
closes #3029
Add small styling improvements to search page described [here](https://github.com/cernopendata/opendata.cern.ch/issues/3029#issue-795964768).
Edit:
- In addition removed underline hover effect on search items and dropdown list
=> ui: small improvements on search page styling

cernopendata/modules/fixtures/data/docs/cod-privacy-policy/cod-privacy-policy.md
addresses #2931
Modified custom table classes to be compatible with SUI.
=> docs: migrated privacy policy RoPO page to SUI

cernopendata/config.py
=> search: fix sorting by title

cernopendata/modules/theme/assets/semantic-ui/js/search/components/FacetItem.js, cernopendata/modules/theme/assets/semantic-ui/js/search/components/index.js, cernopendata/modules/theme/assets/semantic-ui/scss/search.scss, cernopendata/modules/theme/assets/semantic-ui/scss/styles.scss, cernopendata/modules/theme/assets/semantic-ui/scss/variables.scss, cernopendata/modules/theme/assets/semantic-ui/scss/visualise.scss
closes #3062
- Reduced facet name font size
- Added more indendation for subfacets
- Colored facet value counts in grey
New look:
=> ui: improve styling of facets

cernopendata/modules/records/serializers/schemaorg.py, cernopendata/modules/records/serializers/schemas/schemaorg_schemas.py
closes  #3065
- fixed Marshmallow v2 to v3 migration issues
- added custom JSONSerializer to dump it with indentation
=> records: fix schema.org JSON-LD export

cernopendata/mappings/v7/records/docs-v1.0.0.json, cernopendata/mappings/v7/records/glossary-term-v1.0.0.json
=> search: add title mappings for docs and glossary

cernopendata/modules/records/serializers/basic_json.py
closes  #3064
In order to test:
- populate some records with files (`/code/scripts/populate-instance.sh` without any parameters)
- open any record and add `/export/json` to url
- compare with production instance
=> records: fix JSON export

cernopendata/modules/theme/assets/semantic-ui/js/records/components/DownloadWarningModal.js
=> records-ui: close warning modal on click download

cernopendata/config.py, cernopendata/mappings/v7/records/docs-v1.0.0.json, cernopendata/mappings/v7/records/glossary-term-v1.0.0.json, cernopendata/mappings/v7/records/record-v1.0.0.json
Most recent is now based on record IDs that means high record IDs for new content
closes #2418
=> search: Update sort by most recent

cernopendata/modules/fixtures/data/records/atlas-ATL-PHYS-PUB-2021-002.json
Note: A draft PR for preview with ATLAS.
=> records: ATLAS-PHYS-PUB-2021-002 ML dataset

cernopendata/modules/fixtures/data/records/atlas-2020-1largeRjet1lep.json, cernopendata/modules/fixtures/data/records/atlas-2020-1lep.json, cernopendata/modules/fixtures/data/records/atlas-2020-1lep1tau.json, cernopendata/modules/fixtures/data/records/atlas-2020-2lep.json, cernopendata/modules/fixtures/data/records/atlas-2020-3lep.json, cernopendata/modules/fixtures/data/records/atlas-2020-4lep.json, cernopendata/modules/fixtures/data/records/atlas-2020-GamGam.json, cernopendata/modules/fixtures/data/records/atlas-2020-exactly2lep.json, cernopendata/modules/fixtures/data/records/atlas-2020-vm.json, cernopendata/modules/fixtures/data/records/atlas-all-samples.json
Dear developers,
This PR is related to (and solve) issue #2936.
I hope I follow the contribution guidelines correctly.
Thanks and cheers,
Arturo
=> Improve ATLAS records descriptions and reference texts

cernopendata/modules/fixtures/data/records/data-policies.json
Closes #3101.
@artfisica Here is how the updated page looks like:
=> records: ATLAS data policy update

cernopendata/modules/fixtures/data/records/atlas-2020-mc-jet-reconstruction.json
This PR is related to issue https://github.com/cernopendata/opendata.cern.ch/issues/3106
=> ATLA Open Data Jet MC samples - 2020

cernopendata/modules/fixtures/data/records/atlas-2020-mc-jet-reconstruction.json
A small update to the record description as discussed with @artfisica.
=> records: ATLAS 2020 MC jet description update

requirements-production.txt, setup.py
invenio-assets -> 1.2.6
invenio-base -> 1.2.4
=> global: upgrade invenio-assets and invenio-base

cernopendata/config.py
=> facets: order facets similar to PROD instance

cernopendata/modules/theme/assets/semantic-ui/js/search/app.js, cernopendata/modules/theme/assets/semantic-ui/js/search/components/SearchBarContainer.js, cernopendata/modules/theme/assets/semantic-ui/js/search/components/SearchBarElement.js, cernopendata/modules/theme/assets/semantic-ui/js/search/components/index.js, cernopendata/templates/cernopendata_pages/front/main.html, cernopendata/templates/cernopendata_theme/header.html
https://user-images.githubusercontent.com/24358501/128357555-25e5b989-d024-4699-8ea4-cf543b22a451.mov
https://user-images.githubusercontent.com/24358501/128518247-b28dea58-6585-474e-a477-4e2f24afa794.png
closes #3130 
closes #3133
=> search: use native search bar from react-searchkit

cernopendata/mappings/v7/records/record-v1.0.0.json, cernopendata/modules/records/search/query.py
=> es: map orcid using keyword

cernopendata/modules/datacite/utils.py
string.uppercase is no longer supported in python3
=> datacite: update method to support python 3

cernopendata/modules/fixtures/data/docs/cms-about/cms-about.md
(closes #3176 )
Updates About CMS for the 2015 release and fixes outdated links
=> About CMS 2015 updates

cernopendata/modules/fixtures/data/docs/cms-getting-started-2015/cms-getting-started-2015.md, cernopendata/modules/fixtures/data/docs/cms-guide-docker/cms-guide-docker.md, cernopendata/modules/fixtures/data/docs/cms-virtual-machine-2015/cms-virtual-machine-2015.md
(closes #3149 
Streamlines workflow between "getting started" and "docker instructions".
=> update to instructions

cernopendata/modules/fixtures/data/docs/cms-guide-docker/cms-guide-docker.md
=> CMS: improve table display in docker docs

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2015-pileup.json
(closes https://github.com/cernopendata/data-curation/issues/101)
Corrects the validation description (https://github.com/cernopendata/data-curation/issues/101#issuecomment-993466075)
=> fix the validation description

scripts/split_json_file.py
Addition of `split_json_file` helper script that takes one big JSON file
and splits it into several files by groups of say 100 records.
=> scripts: split JSON file

cernopendata/modules/fixtures/data/records/cms-derived-nanoaod-outreach-higgsfourleptons.json, cernopendata/modules/fixtures/data/records/cms-tools-nanoaod-outreach-dimuon-spectrum.json, cernopendata/modules/fixtures/data/records/cms-tools-nanoaod-outreach-higgsfourleptons.json
TODOs:
All places where something has to be changed are either marked by a `TODO`, a `999` or links to the staging directory on publiceos (`root://eospublic.cern.ch//eos/opendata/cms/upload/stefan/...`).
Fixes #3110
=> Records for the Higgs four leptons analysis

cernopendata/modules/fixtures/data/records/cms-validated-runs-ppRun2.json
=> records: CMS 2015 validated runs URI fix

cernopendata/modules/fixtures/data/records/cms-primary-datasets-Run2015D.json
(closes #3212 )
Updates the "usage" field in 2015 data records
=> update data usage

cernopendata/modules/fixtures/data/docs/cms-guide-luminosity-calculation/cms-guide-luminosity-calculation.md, cernopendata/modules/fixtures/data/records/cms-validated-runs-ppRun2.json
(closes #3219 &  addresses #3203)
- fixes the run range description of the 2015 validated run records
- makes a small update to the luminosity guide w.r.t. brilcalc container and 2015 data
@tpmccauley FYI
=> luminosity info

cernopendata/modules/fixtures/data/records/cms-validated-runs-ppRun2.json
(closes #3228 )
Updates validation text.
=> records: update description in CMS 2015 vali records

cernopendata/modules/theme/bundles.py
Fixes recent build failures by pinning codemirror dependency to v5.65.3.
=> theme: pin codemirror version

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2015-part_15.json
=> records: update CMS 2015 mc labels

docker-compose-dev.yml, docker-compose.yml
=> docker: move to PostgreSQL 12.10

cernopendata/modules/fixtures/data/records/lhcb-author-list-2011.json, cernopendata/modules/fixtures/data/records/lhcb-author-list-2012.json
=> Fixed authors lists

Dockerfile, docker-compose-dev.yml, docker-compose.yml, requirements-production.txt
Fixes build troubles caused by invenio-mail and Flask-Mail configuration setup with respect to the DEBUG option. Closes #3275.
Updates `requirements-production.txt` to include the Invenio packages updated in #3231 for clearer consistency.
=> docker: fix MAIL_DEBUG related build troubles

cernopendata/modules/fixtures/data/records/cms-tools-poet.json, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
(closes #3278)
- Adds three SW records for POET SW
- modifies record template to allow HTML in the description field of `system_details`
To do: 
- check if the 2015 branch is correct
- upload zip file of the repository branches
=> records: add CMS poet sw records

Dockerfile, cernopendata/config.py, docker-compose-dev.yml, docker-compose.yml, requirements-production.txt
Fixes static asset exposure by providing a better fix for MAIL_DEBUG related build trouble than e737489d965958896a8248055d39164d0c371cfc.
=> docker: fix static asset exposure

cernopendata/modules/fixtures/data/docs/cms-getting-started-2011/cms-getting-started-2011.md, cernopendata/modules/fixtures/data/docs/cms-getting-started-2015/cms-getting-started-2015.md
(closes #3312)
Small updates to the CMS getting started pages
=> docs: cms getting started updates

cernopendata/modules/fixtures/data/records/cms-condition-data-HIRun1.json
Adds the missing condition data records (https://github.com/cernopendata/opendata.cern.ch/issues/3225#issuecomment-1332117801) for HI data
=> records: add cms hi condition data records

cernopendata/modules/fixtures/data/docs/cms-virtual-machine-2011/cms-virtual-machine-2011.json, cernopendata/modules/fixtures/data/docs/cms-virtual-machine-2011/cms-virtual-machine-2011.md
WIP: checking VM, will update the latest VirtualBox version and output when done.
(closes #3322)
Updates titles for the 2012 VM
=> docs: update cms 2012 vm titles

cernopendata/modules/fixtures/data/records/cms-tools-poet.json
=> records: CMS POET software tarballs

cernopendata/modules/fixtures/data/records/cms-condition-data-2012.json, cernopendata/modules/fixtures/data/records/cms-condition-data-2015.json, cernopendata/modules/fixtures/data/records/cms-condition-data-HIRun1.json, cernopendata/modules/fixtures/data/records/cms-condition-data-Run2-datascience.json, cernopendata/modules/fixtures/data/records/cms-condition-data-Run2010B.json, cernopendata/modules/fixtures/data/records/cms-condition-data-Run2011A.json
=> records: CMS condition data files

Dockerfile, nginx/cernopendata.conf, requirements-production.txt, setup.py
Switches to xrootd 4.12.7 and xrootdpyfs 0.2.2. (Uses xrootd 5.5.1 system libraries, although xrootdpyfs does not support 5.5.1 yet.)
=> installation: xrootd 4.12.7 xrootdpyfs 0.2.2

docker-compose-dev.yml, docker-compose.yml
=> docker: move to PostgreSQL 12.13

cernopendata/templates/cernopendata_records_ui/records/detail.html, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
=> templates: improve file size output reporting

cernopendata/modules/fixtures/data/records/cms-tools-heavyion-examples.json
(closes #3351)
Updates the VM link to point to the correct VM instructions.
=> records: update CMS 2011 HI sw record

docker-compose-dev.yml, docker-compose.yml
for elasticsearch container, closes #3369
=> Removed duplicate restart policy in docker-compose-dev.yml closes #3369

docker-compose-dev.yml, docker-compose.yml
=> docker: move to PostgreSQL 14.8

cernopendata/modules/fixtures/data/docs/cms-guide-docker/cms-guide-docker.md
=> docs: add HI containers in CMS docker guide

cernopendata/modules/fixtures/data/docs/cms-guide-for-conddb/cms-guide-for-conddb.md
=> docs: fix typo in cms conddb guide

cernopendata/modules/fixtures/data/docs/cms-about/cms-about.md
=> docs: update about cms

cernopendata/modules/fixtures/data/records/cms-primary-datasets.json, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
closes #3386 
added Jinja code snippet to display the new metadata field 'container_images' as part of the record details
=> templates: display container_images in records

cernopendata/modules/fixtures/data/docs/cms-guide-trigger-system/cms-guide-trigger-system.md
closes #3413 
- Adds links to POET records for SW
- Adds links to HLT summary table for 2013 and 2015
=> docs: update guide with 2013 and 2015

cernopendata/modules/fixtures/data/records/cms-reco-configuration-files-2015.json
Fixes forgotten FIXME in the RECO configuration file records.
=> records: CMS 2015 reco config file run period fix

cernopendata/modules/fixtures/data/records/cms-pileup-datasets-2011.json, cernopendata/modules/fixtures/data/records/cms-pileup-datasets-2012.json, cernopendata/modules/fixtures/data/records/cms-primary-datasets-Commissioning2010.json, cernopendata/modules/fixtures/data/records/cms-primary-datasets-HIRun2010.json, cernopendata/modules/fixtures/data/records/cms-primary-datasets-HIRun2011.json, cernopendata/modules/fixtures/data/records/cms-primary-datasets-HIpp-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-primary-datasets-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-primary-datasets-Run2011B.json, cernopendata/modules/fixtures/data/records/cms-primary-datasets-Run2012A.json, cernopendata/modules/fixtures/data/records/cms-primary-datasets-Run2012B.json, cernopendata/modules/fixtures/data/records/cms-primary-datasets-Run2012C.json, cernopendata/modules/fixtures/data/records/cms-primary-datasets-Run2012D.json, cernopendata/modules/fixtures/data/records/cms-primary-datasets-Run2015D.json, cernopendata/modules/fixtures/data/records/cms-raw-datasets-Run2010B.json, cernopendata/modules/fixtures/data/records/cms-raw-datasets-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-raw-datasets-Run2012B.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2010-commissioning.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2010.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2012-added.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2015-pileup.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run1-datascience.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2011A.json
Enriches CMS dataset records with information about container image to use for analysis.
=> records: CMS dataset container information

DEVELOPING.rst, cernopendata/modules/fixtures/data/records/jade-logbooks.json
Add description for SELinux issue and add browser command to Podman.
=> Update DEVELOPING.rst and jade-logbooks.json

cernopendata/config.py, cernopendata/templates/cernopendata_pages/front/news.html
Addresses https://github.com/cernopendata/opendata.cern.ch/issues/3095
=> search: order most recent news by created field

cernopendata/config.py
=> config: set account_register_blueprint to false

cernopendata/config.py
=> search: escape /

setup.py
Set the version for the invenio dependencies as a range
Increase the minimum dependency on invenio-search-ui
Increase version number of xrootd to be compatible with the Dockerfile
=> dependencies: Set range versions for the dependencies

cernopendata/config.py, cernopendata/modules/theme/assets/semantic-ui/js/search/components/Facets.js
=> facets: rename the tag of the ondemand parameter

cernopendata/templates/cernopendata_records_ui/records/record_detail.html
Closes https://github.com/cernopendata/opendata.cern.ch/issues/3519
=> record_template: Remove duplicate message for the version release

cernopendata/modules/theme/assets/semantic-ui/templates/search/ResultsGrid.container.jsx
=> display: Fix issue with the grid layout of the results

cernopendata/config.py, cernopendata/jsonschemas/records/docs-v1.0.0.json, cernopendata/jsonschemas/records/glossary-term-v1.0.0.json, cernopendata/mappings/os-v2/records/docs-v1.0.0.json, cernopendata/mappings/os-v2/records/glossary-term-v1.0.0.json, cernopendata/mappings/os-v2/records/record-v1.0.0.json, cernopendata/modules/fixtures/data/docs/alice-releases-educational-datasets-2014/alice-releases-educational-datasets-2014.json, cernopendata/modules/fixtures/data/docs/atlas-13tev-open-data-release-2020/atlas-13tev-open-data-release-2020.json, cernopendata/modules/fixtures/data/docs/atlas-higgs-machine-learning-challenge-2015/atlas-higgs-machine-learning-challenge-2015.json, cernopendata/modules/fixtures/data/docs/atlas-open-data-resources-2016/atlas-open-data-resources-2016.json, cernopendata/modules/fixtures/data/docs/cern-open-data-policy-for-lhc-experiments/cern-open-data-policy-for-lhc-experiments.json, cernopendata/modules/fixtures/data/docs/cms-completes-2010-2011-pp-data/cms-completes-2010-2011-pp-data.json, cernopendata/modules/fixtures/data/docs/cms-completes-run1-heavy-ion-open-data-collection-2023/cms-completes-run1-heavy-ion-open-data-collection-2023.json, cernopendata/modules/fixtures/data/docs/cms-completes-run1-pp-data-release-2022/cms-completes-run1-pp-data-release-2022.json, cernopendata/modules/fixtures/data/docs/cms-observing-higgs-2017/cms-observing-higgs-2017.json, cernopendata/modules/fixtures/data/docs/cms-releases-first-batch-of-data-2014/cms-releases-first-batch-of-data-2014.json, cernopendata/modules/fixtures/data/docs/cms-releases-heavy-ion-data/cms-releases-heavy-ion-data.json, cernopendata/modules/fixtures/data/docs/cms-releases-new-batch-of-data-2016/cms-releases-new-batch-of-data-2016.json, cernopendata/modules/fixtures/data/docs/cms-releases-open-data-for-machine-learning-2019/cms-releases-open-data-for-machine-learning-2019.json, cernopendata/modules/fixtures/data/docs/cms-summer-student-report-2017/cms-summer-student-report-2017.json, cernopendata/modules/fixtures/data/docs/cms-the-future-is-open-2017/cms-the-future-is-open-2017.json, cernopendata/modules/fixtures/data/docs/cod-welcome/cod-welcome.json, cernopendata/modules/fixtures/data/docs/first-cms-open-data-from-lhc-run2-released/first-cms-open-data-from-lhc-run2-released.json, cernopendata/modules/fixtures/data/docs/lhcb-releases-entire-run1-dataset-2023/lhcb-releases-entire-run1-dataset-2023.json, cernopendata/modules/fixtures/data/docs/lhcb-releases-first-set-of-data-2022/lhcb-releases-first-set-of-data-2022.json, cernopendata/modules/fixtures/data/docs/opera-news-first-release/opera-news-first-release.json, cernopendata/modules/fixtures/data/docs/opera-releases-charm-nue-samples-2020/opera-releases-charm-nue-samples-2020.json
=> mappings: Store the title as tokens as well. Remove duplicate

cernopendata/modules/theme/assets/semantic-ui/scss/search.scss, cernopendata/templates/cernopendata_search_ui/search.html
=> style: Add a line between the header and the search bar

Dockerfile, cernopendata/modules/fixtures/data/records/jade-logbooks.json, requirements-production.txt, setup.py
Fix of double phrase and spelling errors
=> update logbook descriptions

cernopendata/config.py, docker-compose-dev.yml, setup.py
=> cli: Removing warning from the startup scripts

cernopendata/templates/cernopendata_theme/footer.html
Addresses [#3558](https://github.com/cernopendata/opendata.cern.ch/issues/3558)
=> footer: Add link to Invenio

Dockerfile, requirements-production.txt, setup.py
Updates XRootD version, fixing image building troubles.
=> build: XRootD 5.6.7

scripts/create-instance.sh, setup.py
=> favicon: Add the OpenData favicon instead of the invenio

cernopendata/modules/fixtures/data/records/cms-reco-configuration-files-2016.json
(closes #3536)
Corrects unit in CMS 2016 reco config files
=> records: updates Tev to TeV

cernopendata/modules/fixtures/data/docs/cms-about/cms-about.md
=> docs: add research guide link to about cms

cernopendata/modules/fixtures/data/docs/cms-getting-started-miniaod/cms-getting-started-miniaod.json, cernopendata/modules/fixtures/data/docs/cms-getting-started-miniaod/cms-getting-started-miniaod.md, cernopendata/modules/fixtures/data/docs/cms-guide-troubleshooting/cms-guide-troubleshooting.md
Closes #3618 
Small updates to the MiniAOD getting started page for the new CMSSW10 container.
Also added a few links to the troubleshooting page to point people to the Guide and Forum. (#3452)
=> tasks for issue 3618

AUTHORS.rst, cernopendata/modules/fixtures/data/records/data-policies.json
=> Delphi add open data policy

Dockerfile, cernopendata/modules/fixtures/data/docs/atlas-open-data-for-research-release-2024/atlas-open-data-for-research-release-2024.md, requirements-production.txt, setup.py
Data. Data data data. Data data.
=> Fixing a typo. Data data. Data data data. Data.

AUTHORS.rst, data/records/atlas-FTAG-2023-05.json
This MR acts as a draft for adding metadata for the atlas-FTAG-2023-05 open dataset.
Todo:
Related to #3735
Tagging @tiborsimko, @zlmarshall, @dguest, @bualust, @nhartman94, @afroch
=> feat(records): add ATLAS-FTAG-2023-05 open dataset
