cernopendata/opendata.cern.ch

invenio_opendata/base/fixtures/websearch.py
* Plugs collection "ATLAS Higgs Challenge 2014" into the visible
collection tree, now that it is ready for production.
=> fixtures: visibility of ATLAS Higgs Challenge

.dockerignore, DEVELOPING.rst, Dockerfile, docker-compose-dev.yml, docker-compose.yml
* Initial release of Docker and Docker-Compose configuration suitable
for local CERN Open Data Portal developments.  The demo site can now
be obtained via:
$ cd ~/private/src/invenio
$ git checkout maint-2.0
$ docker build -t invenio:2.0 .
$ cd ~/private/src/opendata.cern.ch
$ git checkout master
$ ./scripts/populate-fft-file-cache.sh
$ docker-compose -f docker-compose-dev.yml build
$ docker-compose -f docker-compose-dev.yml up
$ # now wait until all daemons are fully up and running
$ firefox http://127.0.0.1:28080/
$ # now populate demo site with some records
$ docker exec -i -t -u invenio opendatacernch_web_1 \
inveniomanage demosite populate --packages=invenio_opendata.base \
-f invenio_opendata/testsuite/data/lhcb/lhcb-derived-datasets.xml \
-e force-recids --yes-i-know
$ firefox …
=> docker: initial release

invenio_opendata/base/templates/footer.html
* Adds copyright year 2015 to the page footer, keeping CERN instead of
CERN Open Data there.  (closes #784)
=> templates: copyright years in page footer

invenio_opendata/base/templates/records/CMS-Simulated-Datasets_dedicated.html
* Changes heading from "data selected" to "data generated" for CMS
Simulated Datasets.  (closes #862)
=> templates: data generated" heading for AODSIM

invenio_opendata/testsuite/data/cms/cms-eventdisplay-files-Run2011A.xml, invenio_opendata/testsuite/data/cms/cms-validated-runs.xml
* Postpones release year to 2016 for CMS 2011 data. (closes #868)
=> CMS: release year 2016 for 2011 data

invenio_opendata/testsuite/data/cms/cms-trigger-information-Run2011A.xml
* Adds overview table to the CMS Trigger Information record for
Run2011A. (addresses #832)
=> CMS: trigger information overview table

invenio_opendata/base/templates/header.html
* Re-enables the DEMO stamp in the page header for the `master`
branch. (closes #884)
=> templates: page header DEMO stamp

invenio_opendata/testsuite/data/atlas/atlas-derived-datasets.xml
* Switches to the new canonical URL for
masterclasses (atlas.physicsmasterclasses.org). (addresses #790)
=> ATLAS: new canonical URL for masterclasses

DEVELOPING.rst, invenio_opendata/testsuite/data/cms/cms-pileup-configuration-files.xml, invenio_opendata/testsuite/data/cms/cms-pileup-configuration-files/mix_2011_FinalDist_OOTPU_cfi.py, scripts/populate-fft-file-cache.sh
* Adds CMS pileup configuration file for the 2011 data. (closes #935)
=> CMS: pileup configuration file

invenio_opendata/base/fixtures/websearch.py, invenio_opendata/base/templates/about_cms.html
* Amends the definitions of CMS Validation Utilities and CMS Validated
Runs so that the two collections can co-exist. (closes #951)
=> CMS: fix definition of Validated Runs

invenio_opendata/testsuite/data/alice/alice-derived-datasets.xml, invenio_opendata/testsuite/data/alice/alice-learning-resources.xml, invenio_opendata/testsuite/data/lhcb/lhcb-learning-resources.xml
* Fixes identical record IDs appearing in ALICE and LHCb
collections. (closes #946) (closes #947)
=> global: fix identical record IDs

invenio_opendata/testsuite/data/cms/cms-tools-ana-Run2011A.xml, invenio_opendata/testsuite/data/cms/cms-tools-cmssw-Run2011A.xml, invenio_opendata/testsuite/data/cms/cms-tools-cmssw.xml, invenio_opendata/testsuite/data/cms/cms-tools-dimuon-spectrum-2010.xml
* Fixes absolute OPENDATADEV links that would be invalid on the QA and
production sites.
=> CMS: fix absolute links

invenio_opendata/base/templates/helpers/text/vms_cms_page_2011.html, invenio_opendata/base/templates/helpers/text/vms_page_2010.html, invenio_opendata/base/templates/helpers/text/vms_page_2011.html
* Fixes CMS VM link targets and labels. (closes #974)
=> templates: CMS VM link fixes

invenio_opendata/base/templates/helpers/collections_educate.html, invenio_opendata/base/templates/helpers/collections_research.html, invenio_opendata/base/templates/search/collection.html
* Fixes year-based search links in CMS collections. Searches for
Run2010B and Run2011A in any field. (closes #904)
=> templates: fix CMS year-based search links

invenio_opendata/testsuite/data/cms/cms-configuration-files-Run2011A.xml, invenio_opendata/testsuite/data/cms/cms-configuration-files/b6ad4db04bcd6551c0d7907e7e3db18c.configFile, invenio_opendata/testsuite/data/cms/cms-configuration-files/b6ad4db04bcd6551c0d7907e7e40a16f.configFile, invenio_opendata/testsuite/data/cms/cms-configuration-files/b6ad4db04bcd6551c0d7907e7e463912.configFile, invenio_opendata/testsuite/data/cms/cms-configuration-files/b6ad4db04bcd6551c0d7907e7e91fbd4.configFile, invenio_opendata/testsuite/data/cms/cms-configuration-files/b6ad4db04bcd6551c0d7907e7e92401d.configFile, invenio_opendata/testsuite/data/cms/cms-configuration-files/b6ad4db04bcd6551c0d7907e7e927f5e.configFile, invenio_opendata/testsuite/data/cms/cms-configuration-files/b6ad4db04bcd6551c0d7907e7e936581.configFile, invenio_opendata/testsuite/data/cms/cms-configuration-files/b6ad4db04bcd6551c0d7907e7e9527d4.configFile, invenio_opendata/testsuite/data/cms/cms-configuration-files/b6ad4db04bcd6551c0d7907e7e958aa8.configFile, invenio_opendata/testsuite/data/cms/cms-configuration-files/b6ad4db04bcd6551c0d7907e7e95b846.configFile, invenio_opendata/testsuite/data/cms/cms-configuration-files/b6ad4db04bcd6551c0d7907e7e963393.configFile, invenio_opendata/testsuite/data/cms/cms-configuration-files/b6ad4db04bcd6551c0d7907e7e9675f4.configFile, invenio_opendata/testsuite/data/cms/cms-configuration-files/b6ad4db04bcd6551c0d7907e7e972c4b.configFile, invenio_opendata/testsuite/data/cms/cms-configuration-files/b6ad4db04bcd6551c0d7907e7e97b7c2.configFile, invenio_opendata/testsuite/data/cms/cms-configuration-files/b6ad4db04bcd6551c0d7907e7e983f2e.configFile, invenio_opendata/testsuite/data/cms/cms-configuration-files/b6ad4db04bcd6551c0d7907e7e992c09.configFile, invenio_opendata/testsuite/data/cms/cms-configuration-files/b6ad4db04bcd6551c0d7907e7e995804.configFile, invenio_opendata/testsuite/data/cms/cms-configuration-files/b6ad4db04bcd6551c0d7907e7e9a2f16.configFile, invenio_opendata/testsuite/data/cms/cms-configuration-files/b6ad4db04bcd6551c0d7907e7e9b3301.configFile, invenio_opendata/testsuite/data/cms/cms-configuration-files/b6ad4db04bcd6551c0d7907e7e9c2b96.configFile
* Adds new Run2011A configuration files extracted from primary datasets.
The collection so far included only those for simulated datasets.
(addresses #934)
=> CMS: new Run2011A configuration files

invenio_opendata/testsuite/data/cms/cms-derived-pattuples-ana-Run2011A.xml
* Updates IFCA Run2011A PAT tuple file information with event
counts. (addresses #1023)
=> CMS: IFCA Run2011A PAT tuple event counts

docker-compose-dev.yml
* Fixes $HOME/Local volume mounting that stopped working after upgrade
to Docker 1.11.0.
=> docker: $HOME/Local volume mounting fix

invenio_opendata/base/templates/records/metadata_base.html
* Updates templates regarding the `collision_energy` treatment, fixing
display of CMS trigger TOC record. (addresses PR #1024)
=> templates: fix for collision_energy display

invenio_opendata/testsuite/data/cms/cms-tools-ana.xml
* Amends text of the two-lepton/four-lepton analysis example record as
per newly attached example plots.  (addresses #557) (closes #916)
=> CMS: two-lepton/four-lepton analysis example text

invenio_opendata/base/templates/helpers/collections_educate.html
* Restricts some new CMS collections (triggers, configurations,
condition data) from appearing in the education view.
(closes #1037)
=> templates: education view collection list update

invenio_opendata/testsuite/data/cms/cms-l1-trigger-information-Run2011A.xml
* Fixes CMS L1 trigger information links in the table-of-contents
record. (addresses #907)
=> CMS: fix for L1 trigger information record links

invenio_opendata/testsuite/data/cms/cms-tools-vm-image-Run2011A.xml, invenio_opendata/testsuite/data/cms/cms-vm-contextualisation-scripts-Run2011A/cernvm-script
* Updates CMS VM 2011 image to the latest `CMS-Open-Data-1.2.0.ova`
version sent by Adam. It uses the latest CernVM release that includes
the fix for a reported logwatch issue. (closes #1113)
=> CMS: new VM 2011 image

invenio_opendata/testsuite/data/cms/cms-tools-dimuon-spectrum-2010/demoanalyzer_cfg.py
* Fixes `demoanalyzer_cfg.py` by a new version from
`/afs/desy.de/user/g/geiser/public/CMS/opendata/MUO-10-004demo/`.
(closes #1116)
=> CMS: fix for dimuon spectrum demo analyzer

CONTRIBUTING.rst, invenio_opendata/base/templates/about.html, setup.py
* Changes `invenio-software.org` to `inveniosoftware.org` to use the
same dashless canonical ID everywhere (GitHub, Twitter, Web).
=> global: inveniosoftware.org

invenio_opendata/testsuite/data/atlas/atlas-tools.xml
* Creates ATLAS Software record for 2016 open data release.
(addresses #1144) (closes #1145)
Signed-off-by: Anxhela Dani anxhela.dani@cern.ch
=> ATLAS: software record for 2016 open data release

DEVELOPING.rst, invenio_opendata/testsuite/data/atlas/atlas-all-samples.xml
* Creates new all samples record for 2016 open data release.
(addresses #1148) (closes #1149)
Signed-off-by: Anxhela Dani anxhela.dani@cern.ch
=> ATLAS: new all samples record for 2016

invenio_opendata/testsuite/data/atlas/atlas-derived-datasets.xml, invenio_opendata/testsuite/data/atlas/eos-file-indexes/DataEgamma_file_index.txt, invenio_opendata/testsuite/data/atlas/eos-file-indexes/DataMuons_file_index.txt
* Adds EOS files for Run2012D Data records. (closes #1140)
=> ATLAS: EOS files for Run2012D Data records

invenio_opendata/testsuite/data/atlas/atlas-simulated-datasets.xml
* Adds record IDs in `538__w` in ATLAS Simulated Datasets.
(closes #1160)
Signed-off-by: Anxhela Dani <anxhela.dani@cern.ch>
=> ATLAS: addition of record IDs in 538__w

invenio_opendata/testsuite/data/atlas/atlas-all-samples.xml, invenio_opendata/testsuite/data/atlas/eos-file-indexes/complete_set_of_ATLAS_open_data_samples_July_2016_file_index.txt
* Adds EOS files for Run2012D all samples record. (closes #1148)
=> ATLAS: EOS files for Run2012D all samples record

invenio_opendata/testsuite/data/atlas/atlas-tools.xml, invenio_opendata/testsuite/data/atlas/eos-file-indexes/ScientificLinux67_ATLAS_Outreach_DataAndTools_July_2016-size_M_file_index.txt, invenio_opendata/testsuite/data/atlas/eos-file-indexes/ScientificLinux67_ATLAS_Outreach_DataAndTools_July_2016-size_N_file_index.txt, invenio_opendata/testsuite/data/atlas/eos-file-indexes/ScientificLinux67_ATLAS_Outreach_DataAndTools_July_2016-size_S_file_index.txt
* Adds EOS files for Run2012D VM records. (closes #1146)
=> ATLAS: EOS files for Run2012D VM records

invenio_opendata/base/recordext/fields/opendata.cfg
* Adds `786__a` & `786__w` to the data model.
(closes #1179) (PR #1180)
Signed-off-by: Anxhela Dani <anxhela.dani@cern.ch>
=> records: data model field update (786)

invenio_opendata/testsuite/data/cms/cms-open-data-instructions.xml
* Fixes metadata of CMS visualisation tool records 57 and 58, resolving Internal
Server Error issues at the same time. (closes #1199)
=> CMS: fix for visualisation tool records

invenio_opendata/testsuite/data/cms/cms-learning-resources.xml
* Fixes record 50 that was catalogued as CMS Open Data Instructions,
not as CMS Learning Resources. (closes #1198)
=> CMS: fix record 50 as learning resource

invenio_opendata/testsuite/data/atlas/atlas-derived-datasets.xml
* Updates EOS file listings (e.g. file sizes) for ATLAS ZPath 2015 datasets,
following up the data file update done with Felix Socher. (closes #917)
=> ATLAS: updated EOS file listings for ZPath 2015

invenio_opendata/base/fixtures/websearch.py
* Introduces new experiment OPERA and its two dataset collections.
(closes #1244)
=> fixtures: new OPERA collections

DEVELOPING.rst, invenio_opendata/testsuite/data/opera/opera-ecc-datasets.xml, invenio_opendata/testsuite/data/opera/opera-ed-datasets.xml
* Adds new OPERA ED and ECC dataset records for the forthcoming 2017 open data
release. Most of information is illustrative and will be filled later by the
collaboration. (addresses #1242)
=> OPERA: new datasets for forthcoming 2017 open data release

invenio_opendata/base/fixtures/websearch.py
* Introduces two more OPERA collections for individual events. (closes #1258)
=> fixtures: two more OPERA collections for events

invenio_opendata/base/fixtures/websearch.py
* Introduces new collection holding CMS luminosity information. (closes #1265)
=> fixtures: new collection CMS Luminosity Information

invenio_opendata/base/templates/helpers/collections_educate.html
* Fixes /educate page not to display the CMS Luminosity Information collection.
The collection is now displayed under /research only.
=> templates: no CMS Luminosity Information under /educate

invenio_opendata/testsuite/data/cms/cms-tools-ana-Run2011A.xml, invenio_opendata/testsuite/data/cms/cms-tools-ana.xml
* Fixes vertex distance typo (0.02cm -> 0.2cm). (closes #1264)
=> CMS: vertex distance fix

invenio_opendata/base/templates/get_started_CMS_2011.html
* Clarifies text regarding CMS VM for 2010 or 2011 data. (closes #1239)
=> templates: CMS VM 2011 clarifications

invenio_opendata/base/templates/helpers/text/cms_learning_resources.html
* Adds EGI FedCloud record to CMS Learning Resources collection page.
(closes #1214)
=> templates: EGI FedCloud for CMS Learning Resources

invenio_opendata/testsuite/data/cms/cms-luminosity-information.xml
* Assigns DOIs.
* Corrects field 264 in record 1050. (addresses #1138) (PR #1277)
=> CMS: DOI for CMS luminosity information records

DEVELOPING.rst, invenio_opendata/testsuite/data/cms/cms-derived-csv-Run2011A.xml, scripts/populate-fft-file-cache.sh
```
commit 043f286c1c10e3f2ac4afa5d8f08239bcafb4c75 (HEAD -> pr-1283, origin/pr-1283)
Author: Tibor Simko <tibor.simko@cern.ch>
Date:   Wed Jul 5 14:29:42 2017 +0200
CMS: updates to CSV Run2011A files
* Removes unused DOI field, adds record ID, adds necessary CDATA wrapper, and
corrects SingleMu to DoubleMu for two input files. Plugs the new MARCXML file
into installation documentation. (closes #1139) (PR #1283)
commit 18e430f40ffbdfb138151db4a0c6507e13018813
Author: Thomas McCauley <thomas.mccauley@cern.ch>
Date:   Wed Jun 7 12:26:10 2017 +0100
CMS: CSV files for Run2011A
* Adds XML file for CSV file records.
* Adds dimuon CSV file reference in MARCXML and download script.
* Adds dimuon CSV from DoubleMu dataset.
* Adds descriptions for …
```
=> CMS: updates to CSV Run2011A files

cernopendata/jsonschemas/records/data-policies-v1.0.0.json, cernopendata/mappings/records/data-policies-v1.0.0.json, cernopendata/modules/fixtures/data/data-policies-v1.0.0.json
* Introduces EOS file information for Data Policies demo records using the
`files.{uri,size,checksum}` technique. Amends data model, mappings and
fixtures.
=> fixtures: EOS files for Data Policy records

docker-compose.yml, scripts/instance.cfg
* Adds CELERY_BROKER_URL config variable for Celery 4. (closes #1340)
=> celery: add Celery 4 config variable

.inveniorc, DEVELOPING.rst, docker-compose.yml
* Fixes exposure of static assets in the `nginx` container by mounting
cernopendata source code volume, similarly to the `web` container. This is
necessary after the change in the asset storage configuration policy from
`file` to `link` that was done around
5bd4955c2a986f9de08574083c56578effaf8795.
=> docker: nginx static asset exposure fix

cernopendata/jsonschemas/records/datasets-v1.0.0.json, cernopendata/jsonschemas/records/software-v1.0.0.json, cernopendata/modules/fixtures/cli.py, cernopendata/modules/fixtures/data/datasets/cms-2011-collision-datasets.json, cernopendata/modules/fixtures/data/datasets/opera-multiplicity-datasets.json, cernopendata/modules/fixtures/data/software/cms-2010-software-validation.json, cernopendata/modules/records/minters/recid.py, scripts/populate-instance.sh
- c83f8314d9382dcb3e7a374d660c07d765c03479 fixtures: datasets and software
- 1cce4883639866239170872e3860d2d2e5eb6fad records: JSON schemas for datasets and software
- 62ceb9a4ba7859503e563b4ca02c13aee273545c records: CMS datasets and software
- cf73f096834863de3acbebad2883c4a0269b2438 records: OPERA datasets and events
=> records: datasets and software

cernopendata/jsonschemas/records/article-v1.0.0.json, cernopendata/jsonschemas/records/data-policies-v1.0.0.json, cernopendata/jsonschemas/records/term-v1.0.0.json, cernopendata/modules/fixtures/data/articles/about/cms.json, cernopendata/modules/fixtures/data/articles/getting_started/cms.json, cernopendata/modules/fixtures/data/articles/news/news.json, cernopendata/modules/fixtures/data/articles/vms/cms.json, cernopendata/modules/fixtures/data/data-policies-v1.0.0.json, cernopendata/modules/fixtures/data/terms/terms.json
* Adds `type` and `subtype` fields to all the data model schemas and fixtures.
(closes #1424)
=> records: more type/subtype fields

Dockerfile, docker-compose.yml, scripts/create-instance.sh, scripts/provision-web.sh
* Installs pyxrootd inside Python virtual environment instead of using CentOS7
system package. Amends Python paths as per the change of the base image to
CentOS7. (closes #1414)
=> installation: pyxrootd inside venv

cernopendata/config.py, cernopendata/modules/theme/static/scss/styles.scss, cernopendata/static/templates/cernopendata_search_ui/results.html, cernopendata/static/templates/faceted_results.html, cernopendata/static/templates/search/briefs/articles.html, cernopendata/static/templates/search/briefs/dataset.html, cernopendata/static/templates/search/briefs/default.html, cernopendata/static/templates/search/briefs/software.html, cernopendata/static/templates/search/briefs/terms.html, cernopendata/templates/cernopendata_pages/index.html
* Closes #1452 (tags will be clickable)
* Removes 'Show source' from results on search page
* Display labels for all kind of briefs in search results
=> templates: fix labels

Dockerfile
* Change default user-id used in Dockerfile to 1000 (typical UID of
first non-root user used in many Linux distributions) in order to
fix permission errors that sometimes arise after making changes to
files or folder mounted to web- and worker-containers.
=> docker: fix user-id related permission errors

scripts/clean-instance.sh
* Changes the command used to clean the indeces since the `curl` call
does not work currently on OpenShift. Moreover it follows latest
Invenio-App-ILS documentation.
=> scripts: use invenio command to delete ES indeces

cernopendata/modules/fixtures/data/datasets/cms-2011-collision-datasets.json, cernopendata/modules/fixtures/data/software/cms-2010-software-validation.json
* Removes a leftover OPERA selection description in CMS records. (closes #1467)
=> records: removed extra selection description

cernopendata/modules/fixtures/cli.py, scripts/populate-instance.sh
* Adds a new option to skip loading of files when loading fixtures.
Example: `cernopendata fixtures datasets --skip-files`.
Example: `./scripts/populate-instance.sh --skip-files`.
(closes #1561)
=> fixtures: new option `--skip-files`

cernopendata/config.py, cernopendata/static/templates/faceted_results.html, cernopendata/static/templates/search/briefs/articles.html, cernopendata/static/templates/search/briefs/record.html, cernopendata/static/templates/search/briefs/terms.html, cernopendata/templates/cernopendata_pages/index.html, cernopendata/templates/cernopendata_records_ui/records/detail.html, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
* Updates record display templates to catch up with the basic issues such as
type/subtype changes and labels, the abstract summary display, the additional
title display, the optional collaboration field, the better completeness of
information in the detailed record pages, etc.
* Note: the fully complete and fully prettified detailed record information
display is out of the scope of the current focus on record files. This will be
tackled later.
=> templates: basic record display updates

cernopendata/jsonschemas/records/record-v1.0.0.json
* Enriches `links` properties in various `record` data model schema fields in
order to contain `url`, `title`, `recid`, `description` consistently
everywhere. (closes #1570)
=> records: richer `links` property in `record` data model schema

cernopendata/modules/fixtures/data/records/opera-ecc-datasets.json, cernopendata/modules/fixtures/data/records/opera-ed-datasets.json
* Centralises local files on EOS for OPERA datasets. Enriches record metadata
correspondingly. (closes #1725) (closes #1726) (closes #1727)
=> records: centralise local files on EOS for OPERA datasets

cernopendata/modules/fixtures/data/records/cms-author-list-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-author-list.json, cernopendata/modules/fixtures/data/records/opera-author-list.json
* Centralises local files on EOS for Author-Lists. Enriches record metadata
correspondingly. (closes #1694) (closes #1695) (closes #1724)
=> records: centralise local files on EOS for Author-Lists

cernopendata/modules/fixtures/data/records/data-policies.json
* Centralises local files on EOS for Data-Policies. Enriches record metadata
correspondingly. (closes #1722)
=> records: centralise local files on EOS for Data-Policies

cernopendata/modules/fixtures/data/records/cms-eventdisplay-files.json
* Centralises local files on EOS for cms-eventdisplay-files records.
Enriches record metadata correspondingly. (closes #1703)
=> records: centralise local files on EOS for cms-eventdisplay-files

cernopendata/modules/fixtures/data/records/cms-eventdisplay-files-Run2011A.json
* Centralises local files on EOS for cms-eventdisplay-files-Run2011A records.
Enriches record metadata correspondingly. (closes #1702)
=> records: centralise local files on EOS for cms-eventdisplay Run2011A

cernopendata/modules/fixtures/data/records/cms-derived-csv-Run2011A.json
* Centralises local files on EOS for cms-derived-csv-Run2011A records.
Enriches record metadata correspondingly. (closes #1699)
=> records: centralise local files on EOS for cms-derived-csv-Run2011A

cernopendata/modules/fixtures/data/records/cms-configuration-files-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-hlt-2011-configuration-files.json, cernopendata/modules/fixtures/data/records/cms-pileup-configuration-files.json
* Centralises local files on EOS for CMS configuration files records. Enriches
record metadata correspondingly. (closes #1697) (closes #1705) (closes #1711)
=> records: centralise local files on EOS for CMS configuration files

cernopendata/modules/fixtures/data/records/lhcb-derived-datasets.json
* Centralises local files on EOS for LHCb Derived Datasets records.
Enriches record metadata correspondingly. (closes #1723)
=> records: centralise local files on EOS for LHCb Derived Datasets

cernopendata/modules/fixtures/data/records/alice-derived-datasets.json
* Centralises local files on EOS for ALICE-Derived-Datasets records.
Enriches record metadata correspondingly. (closes #1686)
=> records: centralise local files on EOS for ALICE-Derived-Datasets

cernopendata/modules/fixtures/data/records/cms-validated-runs.json
* Centralises local files on EOS for CMS-Validated-Runs records.
Enriches record metadata correspondingly. (closes #1720)
=> records: centralise local files on EOS for CMS-Validated-Runs

cernopendata/modules/fixtures/data/records/cms-tools-vm-image.json
* Centralises local files on EOS for cms-tools-vm-image records.
Enriches record metadata correspondingly. (closes #1719)
=> records: centralise local files on EOS for cms-tools-vm-image

cernopendata/modules/fixtures/data/records/cms-tools-vm-image-Run2011A.json
* Centralises local files on EOS for cms-tools-vm-image-Run2011A records.
Enriches record metadata correspondingly. (closes #1718)
=> records: centralise local files on EOS for cms-tools-vm-image 2011

cernopendata/modules/fixtures/data/records/cms-open-data-instructions.json
* Centralises local files on EOS for CMS-Open-Data-Instructions records.
Enriches record metadata correspondingly. (closes #1710)
=> records: centralise local files on EOS for Open Data Instructions

cernopendata/modules/fixtures/data/records/cms-luminosity-information.json
* Centralises local files on EOS for CMS-Luminosity-Information records.
Enriches record metadata correspondingly. (closes #1708)
=> records: centralise local files on EOS for CMS Luminosity Info

cernopendata/modules/fixtures/data/records/cms-l1-trigger-information-Run2011A.json
* Centralises local files on EOS for CMS-Trigger-Information records.
Enriches record metadata correspondingly. (closes #1706)
=> records: centralise local files on EOS for CMS L1 Trigger Info

cernopendata/modules/fixtures/data/records/cms-derived-pattuples-ana.json
* Centralises local files on EOS for cms-derived-pattuples-ana records.
Enriches record metadata correspondingly. (closes #1701)
=> records: centralise local files on EOS for CMS Derived PATtuples

cernopendata/modules/fixtures/data/records/cms-derived-pattuples-ana-Run2011A.json
* Centralises local files on EOS for cms-derived-pattuples-ana-Run2011A records.
Enriches record metadata correspondingly. (closes #1700)
=> records: centralise local files on EOS for CMS Derived PATtuples 11

cernopendata/modules/fixtures/data/records/cms-hamburg-files.json
* Centralises local files on EOS for cms-hamburg-files records.
Enriches record metadata correspondingly. (closes #1704)
=> records: centralise local files on EOS for cms-hamburg-files

cernopendata/modules/fixtures/data/records/atlas-all-samples.json
* Centralises local files on EOS for atlas-all-samples records.
Enriches record metadata correspondingly. (closes #1689)
=> records: centralise local files on EOS for atlas-all-samples

cernopendata/modules/fixtures/data/records/atlas-derived-datasets.json
* Centralises local files on EOS for atlas-derived-datasets records.
Enriches record metadata correspondingly. (closes #1690)
=> records: centralise local files on EOS for atlas-derived-datasets

cernopendata/modules/fixtures/data/records/alice-learning-resources.json
* Centralises local files on EOS for ALICE-Learning-Resources records.
Enriches record metadata correspondingly. (closes #1687)
=> records: centralise local files on EOS for ALICE-Learning-Resources

cernopendata/modules/fixtures/data/records/atlas-simulated-datasets.json
* Centralises local files on EOS for atlas-simulated-datasets records.
Enriches record metadata correspondingly. (closes #1692)
=> records: centralise local files on EOS for atlas-simulated-datasets

cernopendata/modules/fixtures/data/records/cms-condition-data-Run2011A.json
* Centralises local files on EOS for CMS condition data 2011 records.
Enriches record metadata correspondingly. (closes #1696)
=> records: centralise local files on EOS for CMS condition data 2011

cernopendata/modules/fixtures/data/records/atlas-higgs-challenge-2014.json
* Centralises local files on EOS for ATLAS-Higgs-Challenge-2014 records.
Enriches record metadata correspondingly. (closes #1691)
=> records: centralise local files on EOS for ATLAS-Higgs-Challenge-2014

cernopendata/modules/fixtures/data/records/cms-learning-resources.json
* Centralises local files on EOS for CMS-Learning-Resources records.
Enriches record metadata correspondingly. (closes #1707)
=> records: centralise local files on EOS for CMS-Learning-Resources

cernopendata/modules/fixtures/data/records/atlas-tools.json
* Centralises local files on EOS for ATLAS-Tools records.
Enriches record metadata correspondingly. (closes #1693)
=> records: centralise local files on EOS for ATLAS-Tools

cernopendata/modules/fixtures/data/records/cms-tools-dimuon-spectrum-2010.json
* Centralises local files on EOS for cms-tools-dimuon-spectrum-2010 records.
Enriches record metadata correspondingly. (closes #1717)
=> records: centralise local files on EOS for CMS dimuon-spectrum-2010

cernopendata/modules/fixtures/data/records/cms-tools-dimuon-filter.json
* Centralises local files on EOS for cms-tools-dimuon-filter records.
Enriches record metadata correspondingly. (closes #1716)
=> records: centralise local files on EOS for cms-tools-dimuon-filter

cernopendata/modules/fixtures/data/records/cms-validation-code-Run2010B.json
* Centralises local files on EOS for cms-validation-code-Run2010B records.
Enriches record metadata correspondingly. (closes #1721)
=> records: centralise local files on EOS for CMS Validation 2010

cernopendata/modules/fixtures/data/records/cms-csv-files.json
* Centralises local files on EOS for cms-csv-files records.
Enriches record metadata correspondingly. (closes #1698)
=> records: centralise local files on EOS for cms-csv-files

cernopendata/modules/theme/bundles.py, cernopendata/static/js/components/resultsBrief.js, cernopendata/static/templates/search/briefs/record.html
* Fixes Internal Server Error of `/search` page and the empty search page
results related to resultsBrief loweecasing.
=> static: resultsbrief case fix

cernopendata/modules/fixtures/data/records/cms-learning-resources.json
* Fixes PPP link in CMS-Learning-Resources. (closes #1784)
=> records: PPP link fix

cernopendata/modules/fixtures/data/records/cms-masterclass-files.json
* Centralises local files on EOS for CMS Masterclass records.
Enriches record metadata correspondingly. (closes #1709)
=> records: centralise local files on EOS for CMS Masterclass files

cernopendata/modules/pages/views.py
redirects:
`getting-started/alice` ->`/articles/getting-started-with-alice-open-data`
`getting-started/cms` -> `/articles/getting-started-with-cms-open-data`
`getting-started/lhcb` -> `/articles/getting-started-with-lhcb-open-data`
=> templates: redirect for getting-started

scripts/populate-instance.sh
* Adds a new populate option to skip loading of records when populating the
site. Useful when working on articles. Usage example:
`$ ./scripts/clean-instance.sh`
`$ vim cernopendata/modules/fixtures/data/articles/my-article/my-article.json`
`$ ./scripts/populate-instance.sh --skip-records`.
=> scripts: new populate option `--skip-records`

scripts/populate-instance.sh
* Amends `populate-instance.sh` script in order to upload the small files first.
This alleviates the symptoms of the "big file" loading issues until they are
properly addressed. (see #1826)
=> scripts: populate small files first

cernopendata/modules/theme/bundles.py, cernopendata/templates/cernopendata_theme/page.html
=> global: removes ui-bootstrap from cdn

cernopendata/modules/fixtures/data/records/atlas-tools.json, cernopendata/modules/fixtures/data/records/cms-raw-datasets-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-tools-reco.json
* Introduces new record for 2011 RAW data sample. (closes #1202)
* Introduces two new software records for the RAW data sample. (closes #1525)
* Note: PR prepared from COD2 PR #1546.
* Also fixes distribution.formats for other `tar.gz` files.
Co-authored-by: Tibor Simko <tibor.simko@cern.ch>
=> CMS: new 2011 RAW dataset sample and rereco software records

cernopendata/modules/fixtures/data/articles/cms-guide-for-education/education.md
Fixes links and other points in https://github.com/cernopendata/opendata.cern.ch/issues/1518#issuecomment-347027796.
Needs records from #1789, #1760, #1761 and #1762 to fix rest of the links.
The title and the link has two times CMS : CMS Guide to education use of CMS Open Data . The first should be removed.
Signed-off-by: Kati Lassila-Perini <Katri.Lassila-Perini@cern.ch>
=> templates: CMS: updates to education guides

cernopendata/modules/fixtures/data/records/cms-tools-ana-Run2011A.json
* Fixes GitHub link for the pattuples2011 software record 233.
(closes #1296) (PR #1302)
Co-authored-by: Tibor Simko <tibor.simko@cern.ch>
=> CMS: fixes for GitHub pattuples2011 link

cernopendata/modules/fixtures/data/records/cms-open-data-instructions-2017.json
* Adds four new records for 2017 CMS educational activities. (closes #1760) (closes #1761) (closes #1762) (closes #1789)
=> CMS: Adds educational materials

cernopendata/templates/cernopendata_records_ui/records/record_detail.html
* Interpret HTML in record validation descriptions. (closes #1932)
=> templates: HTML in record validation description

cernopendata/modules/fixtures/data/records/cms-hlt-configuration-files-2012.json
* Adds CMS HLT configuration files for 2012. (closes #1961)
=> records: CMS 2012 HLT configuration files

cernopendata/modules/fixtures/cli.py, scripts/populate-instance.sh
=> cli: adds replace option

cernopendata/modules/fixtures/data/records/cms-trigger-examples.json
* Fixes links to VM records for CMS trigger examples records. (closes #1984)
=> records: CMS trigger examples VM link fixes

cernopendata/modules/fixtures/data/records/cms-reco-configuration-files-2012.json
* Adds RECO configuration files for CMS 2012 collision datasets.
(closes #1988)
=> records: CMS 2012 collision dataset RECO configuration files

cernopendata/modules/fixtures/data/records/cms-eventdisplay-files-Run2012B.json, cernopendata/modules/fixtures/data/records/cms-eventdisplay-files-Run2012C.json
* Adds CMS 2012 event display files. (closes #1404)
=> records: CMS 2012 event display files

cernopendata/modules/fixtures/data/docs/opera-news-first-release/opera-news-first-release.json
* Changes the experiment name from Opera --> OPERA, so that it is not
displayed twice in the facet.
=> templates: capitalisation fix for OPERA .json

cernopendata/modules/fixtures/data/records/atlas-tools.json, cernopendata/modules/fixtures/data/records/cms-author-list-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-author-list.json, cernopendata/modules/fixtures/data/records/cms-open-data-instructions-2017.json, cernopendata/modules/fixtures/data/records/cms-open-data-instructions.json, cernopendata/modules/fixtures/data/records/cms-tools-ana-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-tools-cmssw-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-tools-dimuon-filter.json, cernopendata/modules/fixtures/data/records/cms-tools-dimuon-spectrum-2010.json, cernopendata/modules/fixtures/data/records/cms-tools-ispy-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-tools-reco.json, cernopendata/modules/fixtures/data/records/cms-validation-code-Run2010B.json, cernopendata/modules/fixtures/data/records/opera-author-list.json
* Fixes dates in records where the `date_created` property did not indicate the
data-taking year and introduces dates where this property was missing
completely. (closes #1891) (addresses #1944)
=> records: dates in date_created -> data-taking year

cernopendata/modules/fixtures/data/records/cms-tools-vm-image-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-tools-vm-image.json
* Fixes links in the 2010 and 2011 CMS VM image records. (closes #1883)
=> records: CMS VM records link fix

cernopendata/modules/markdown/__init__.py, cernopendata/modules/markdown/ext.py, cernopendata/modules/mistune/ext.py, cernopendata/modules/pages/views.py, cernopendata/static/test_data/debug.md, cernopendata/templates/cernopendata_theme/page.html, scripts/create-instance.sh, setup.py
* Add MathJax.js to render content in TeX-syntax
* Make Mistune (markdown parser) and Python-Markdown compatible with TeX-syntax (`$ ... $`, `$$ ... $$`, `\begin ... \end`). Otherwise characters matching markdown control characters (e.g. `__ ... __` or `** ... **`) that reside inside TeX-content, might mess up the TeX-content.
=> Support for math content in TeX-syntax for HTML and Markdown (Mistune)

cernopendata/modules/fixtures/data/docs/cms-simulated-dataset-names/cms-simulated-dataset-names.json
* Fixes installation issue related to ABout CMS Simulated Dataset Names docs.
=> docs: about CMS simulated dataset names

cernopendata/templates/cernopendata_records_ui/records/record_detail_Author-Lists.html
* Fixes traceback when displaying author lists records.
=> templates: fix traceback for author list records

cernopendata/modules/fixtures/data/records/cms-condition-data-2012.json
* Adds two new records for 2012 CMS condition data for
collision and simulated data from RunB and RunC. (closes #1263)
=> CMS: adds 2012 condition data

cernopendata/modules/fixtures/data/records/cms-eventdisplay-files-Run2012B.json, cernopendata/modules/fixtures/data/records/cms-eventdisplay-files-Run2012C.json, cernopendata/modules/fixtures/data/records/cms-hlt-configuration-files-2012.json, cernopendata/modules/fixtures/data/records/cms-reco-configuration-files-2012.json
* Fixes checksum information for several CMS files. (closes #2064)
=> records: sha1 checksum fix for files

cernopendata/modules/fixtures/data/docs/cms-about/cms-about.md
* Amends spacing in the About CMS page in order to prettify the output.
Co-authored-by: Kati Lassila-Perini <k.lassila-perini@cern.ch>
=> docs: spacing in About CMS page

cernopendata/modules/fixtures/data/records/cms-tools-ispy-2012.json
* Adds one new software record for CMS 2012 event display files.
(closes #2025)
=> CMS: adds software record for event display files

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2011A.json
* Remoes invalid `isChildOf` relations for CMS 2011 MC datasets.
(addresses #2048)
=> records: CMS 2011 MC isChildOf relation fix

nginx/cernopendata.conf
* Add caching layer in nginx.
Quite aggressive caching policy, as everything that is not available
on EOS or under '/files' is cached.
Note that path '/files' should be cached in the future.
(addresses #1728)
=> nginx: add caching layer

cernopendata/modules/fixtures/data/records/cms-primary-datasets-Run2012B.json, cernopendata/modules/fixtures/data/records/cms-primary-datasets-Run2012C.json
* Adds rich index files (in TXT and JSON formats) for CMS 2012 collision
datasets. (addresses #2093)
=> records: rich index files for CMS 2012 collision datasets

cernopendata/modules/fixtures/data/records/cms-tools-higgsexample11-12.json, cernopendata/modules/fixtures/data/records/cms-tools-higgsexample20112012.json
* Adds one file that was accidentally left out to the H4L analysis example
software record. (addresses #1966)
=> records: addition of missing file for CMS HiggsExample11-12

cernopendata/modules/fixtures/data/records/cms-tools-vm-image-2012.json, cernopendata/modules/fixtures/data/records/cms-tools-vm-image-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-tools-vm-image.json
* Adds one record for the new contextualization script and makes
modifications to the previous contextualization script records. (closes #2045)
* Updates the 2011 VM record, so that it is appropriate for 2012 data as well. (closes #2044)
=> CMS: adds contextualization script, fixes for VMs

cernopendata/modules/fixtures/cli.py
=> cli: fixes replace method

cernopendata/modules/fixtures/data/records/cms-dimuon-spectrum-2011.json
* Adds new release of DimuonSpectrum2011 v1.0.3 and attaches individual files
for the CMS 2011 dimuon spectrum record. (closes #2132)
=> records: CMS 2011 dimuon spectrum file updates

cernopendata/modules/fixtures/data/records/cms-derived-csv-Run2011A.json
* Renames `Dimuon.csv` files in record 545 to `Dimuon_SingleMu.csv` and
`Dimuon_DoubleMu.csv` following up EOS file name updates. (closes #1299)
=> records: renaming of Dimuon SingleMu/DoubleMu files

docker-compose-dev.yml, docker-compose.yml, nginx/cernopendata.conf
* Introduces web-files service that is dedicated to serving `*/files/*` pages.
Amends nginx proxy forwarding accordingly. (closes #2130)
* Note that this commit adds a minimal working example tested on both DEV snd
PROD deployment scenarios. The proxy parameters will be tuned later based on
wider performance tests.
Co-authored-by: Tibor Simko <tibor.simko@cern.ch>
=> installation: addition of web-files service

cernopendata/modules/fixtures/data/docs/cms-about/cms-about.md
* Fixes a grammar issue in the About CMS page. (closes #1463)
=> docs: About CMS page grammar issue fix

cernopendata/modules/fixtures/data/records/cms-dimuon-spectrum-2011.json
* Removes tarball for the CMS dimuon spectrum 2011 record. (closes #2174)
=> docs: CMS dimuon spectrum 2011 file removal

cernopendata/modules/fixtures/cli.py, cernopendata/templates/cernopendata_records_ui/records/detail.html
* Fixes traceback in fixture loading in the `--skip-files` mode following up the
PR #2108.
* Fixes traceback in the detailed record page view on case there are no files
attached to the record.
=> fixtures: fix for `--skip-files` mode

cernopendata/modules/fixtures/data/records/cms-configuration-files-2012.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2012.json
* Adds generation information to CMS 2012 simulated datasets. (closes #2151)
* Adds new configuration files accordingly. (Beware, record IDs may have
changed.)
=> records: CMS 2012 simulated dataset generation information

docker-compose.yml
* We are not using last elsticsearch python packages which causes
some deprecation warnings. Since we can not update the packages
right now, we disable them for production environment.
* Closes #2087.
=> elasticsearch: disable deprecation warnings

invenio_opendata/testsuite/data/opera/opera-ed-datasets.xml
* This completes the OPERA multiplicity studies records in COD2-based
installations. Committing for the sake completeness if we ever need to get
back to MARC-based records.
=> OPERA: record updates related to raw vs filtered events

DEVELOPING.rst, Dockerfile, docker-compose-dev.yml, nginx/cernopendata.conf
* Increass maximum size of web-app service cache and web-files serving cache to
fit typical OPenShift deployment conditions. (closes #2126)
* Increases web-files service caching threshold to 10M. Files less than this
size are cached, files larger than this size are served synchronously without
caching.
* Improves nginx proxy ocnfiguration with respect to stale request sending in
case of cache updates.
* Improves nginx proxy ocnfiguration to use uwsgi-dedicated protocol between
nginx proxy and web application. Removes the nginx proxy service in
development-style deployments in order to avoid possible confusion related to
protocols. Keeps the nginx proxy service with uwsgi-dedicated protocol only in
production-level deployments.
* Amends docker-oriented documentation to bring down the …
=> nginx: larger cache, better stale serving, uwsgi protocol

DEVELOPING.rst, Dockerfile, docker-compose-dev.yml, nginx/cernopendata.conf
* Allows only GET and HEAD request methods. This disables unnecessary methods
such as CONNECT, DELETE, OPTIONS, PATCH, POST, PUT, TRACE for improved
safety. (closes #2199)
=> nginx: allow only GET and HEAD requests

cernopendata/modules/theme/bundles.py
* Use newer ispy-webgl from npm in bundles
* New version fetches correct ig file name from url
* Closes 2211
=> CMS event display file name

cernopendata/templates/cernopendata_pages/front/lva.html, cernopendata/templates/cernopendata_pages/front/main.html
* Renames next page link labels `Get started ..` and `News ..` to remove
trailing dots.
=> templates: next page link labels

nginx/cernopendata.conf
* Adds basic access and error log configuration. Suitable for use with `ngxtop`.
Example: `docker logs -f opendatacernch_nginx_1 | ngxtop`. (closes #2127)
=> nginx: basic access and error log configuration

nginx/cernopendata.conf
* Does not lowercase glossary URLs such as `/glossary/AOD`, fixing "not found"
problems for several terms that contain uppercase characters.
=> nginx: respecing case for glossary URLs

cernopendata/modules/fixtures/data/docs/cms-summer-student-report-2017/cms-summer-student-report-2017.json, cernopendata/modules/fixtures/data/docs/cms-the-future-is-open-2017/cms-the-future-is-open-2017.json, cernopendata/modules/fixtures/data/docs/cod-welcome/cod-welcome.json
* Updates some news items and reorders the featured stories for the home page.
(addresses #2207)
=> docs: order of news items

cernopendata/modules/fixtures/data/records/cms-tools-vm-image.json
* Fixes corrupted `CMS-OpenData-1.0.0-rc7.ova` and updates file size and
checksum information accordingly. (closes #2255)
=> CMS: fix corrupted CMS-OpenData-1.0.0-rc7.ova

Dockerfile
* Pins xrootd 4.7.1 versions due to a bug encountered with xrootd 4.8.0
upgrade. (addresses #2258)
=> installation: xrootd 4.7.1

nginx/cernopendata.conf
* Adds the old reverse proxy to EOSPUBLIC that was used in COD2 times for
backward compliance.  (closes #2279)
=> nginx: reverse proxy to EOSPUBLIC

Dockerfile, docker-compose-dev.yml
* Postpones user creation in Dockerfile to avoid permission denied
when installing `requirements-dev.txt`.
=> docker: add debug flag for dev build

setup.py
* Declares Python-2.7 version only in ``setup.py`` classifiers. We cannot use
Python-3.6 because of XRootD connectivity.
* Removes top-level ``__init__.py`` that is not part of the package.
=> installation: Python version support

.github/PULL_REQUEST_TEMPLATE.md
* Documents the new pull request policy. Basically, `qa` for production fixes
and for quick rollout features, `master` for slower rollout features,
`production` never.
=> docs: new pull request policy

cernopendata/modules/fixtures/data/records/cms-condition-data-Run2011A.json
* Changes `cms-condition-data-Run2011A` records by removing the index files and
attaching the asset files directly. This is sufficient for this collection
containing low number of files. (addresses #2093)
=> records: CMS condition data direct files

cernopendata/modules/fixtures/data/records/lhcb-derived-datasets.json
* Changes `lhcb-derived-datasets` records by removing the index files and
attaching the asset files directly. This is sufficient for this collection
containing relatively low number of files. (addresses #2093)
=> records: LHCb derived dataset direct files

cernopendata/modules/pages/views.py
* Closes: #2250
Redirects:
`/getting-started/cms` to `/docs/cms-getting-started-2011` and
`/vm/cms` to `/docs/cms-virtual-machine-2011`
=> views: small changes to fix cms links

cernopendata/modules/fixtures/data/records/cms-csv-files.json, cernopendata/modules/fixtures/data/records/cms-derived-pattuples-ana.json, cernopendata/modules/fixtures/data/records/cms-eventdisplay-files.json, cernopendata/modules/fixtures/data/records/cms-primary-datasets.json
* Fixes CMS dataset titles that were using `Run-2010B` instead of `Run2010B`.
=> records: fix Run2010B run period in CMS dataset titles

cernopendata/modules/fixtures/data/records/cms-raw-datasets-Run2011A.json
* Adds rich index files (TXT, JSON) to `cms-raw-datasets-Run2011A`
records. (addresses #2093)
=> records: CMS raw dataset rich index files

cernopendata/modules/fixtures/data/records/atlas-derived-datasets.json
* Changes `atlas-derived-datasets` records by removing the index files and
attaching the asset files directly. This is sufficient for this collection
containing relatively low number of files. (addresses #2093)
=> records: ATLAS derived dataset direct files

cernopendata/modules/fixtures/data/records/cms-primary-datasets.json
* Adds rich index files (TXT, JSON) to `cms-primary-datasets` records.
(addresses #2093)
* Adds previously forgotten 10000 and 10001 volumes to the MuOnia dataset.
=> records: CMS 2010 collision datasets rich index files

cernopendata/modules/fixtures/data/records/atlas-simulated-datasets.json
* Changes `atlas-simulated-dataset` records by removing the index files and
attaching the asset files directly. This is sufficient for this collection
containing low number of files. (addresses #2093)
=> records: ATLAS simulated dataset direct files

cernopendata/modules/fixtures/data/records/cms-derived-pattuples-ana.json
* Adds rich index files (TXT, JSON) to `cms-derived-pattuples-ana`
records. (addresses #2093)
=> records: CMS PAT tuples rich index files

cernopendata/modules/fixtures/data/records/cms-derived-pattuples-ana-Run2011A.json
* Adds rich index files (TXT, JSON) to `cms-derived-pattuples-ana-Run2011A`
records. (addresses #2093)
=> records: CMS 2011 PAT tuples rich index files

cernopendata/modules/fixtures/data/records/cms-primary-datasets-Run2011A.json
* Adds rich index files (TXT, JSON) to `cms-primary-datasets-Run2011A`
records. (addresses #2093)
* Removes empty record (coming from a conversion of a deleted dataset that was
never officially released).
=> records: CMS 2011 collision datasets rich index files

cernopendata/modules/fixtures/data/records/cms-primary-datasets-Run2011A.json
* Amends fixtures for the CMS 2011 HT collision dataset following up the
recovery of a missing file. (closes #2324)
=> records: CMS 2011 HT file addition

cernopendata/modules/fixtures/data/records/opera-detector-events-tau-neutrino.json, cernopendata/modules/fixtures/data/records/opera-ecc-datasets.json, cernopendata/modules/fixtures/data/records/opera-ed-datasets.json
* Adds first example OPERA tau appearance event 9234119599 record, useful for
working on event display and the rest of the sample release. The other events
will follow shortly. (closes #2351)
=> records: OPERA tau appearance event 9234119599

cernopendata/modules/fixtures/data/records/opera-detector-events-tau-neutrino.json
* Adds nine more OPERA tau neutrino candidate events with basic record and file
information. The detailed TeX descriptions still to follow. (addresses #2382)
=> records: more OPERA tau neutrino candidate events

cernopendata/templates/cernopendata_theme/footer.html
* Updates the ATLAS Public URL in the page footer.
(closes #2387)
=> templates: update of the ATLAS Public URL

Dockerfile, cernopendata/modules/fixtures/data/docs/atlas-about/atlas-about.md
installation: ca-certificates
* Update ``ca-certificates`` package in order to fix Travis CI installation
issues with some repository mirrors ("Cannot retrieve metalink for repository:
epel/x86_64") that I am not observing locally.
=> docs: updates to the About ATLAS page

nginx/cernopendata.conf
* uwsgi nginx module sets a buffer by default see
http://nginx.org/en/docs/http/ngx_http_uwsgi_module.html#uwsgi_request_buffering.
For a client takes normally a lot of time to consume it, so in certain
occassions the uwsgi process would time out and only a chunk of the
file would be downloaded (the chunk that corresponds with the default
size of the buffer) (closes #2427).
=> nginx: disable uwsgi mod buffering for nginx

.dockerignore, .travis.yml, Dockerfile, MANIFEST.in, cernopendata/modules/fixtures/cli.py, cernopendata/modules/pages/views.py, cernopendata/modules/records/utils.py, cernopendata/modules/theme/config.py, cernopendata/modules/theme/views.py, run-tests.sh, setup.cfg, setup.py
* Enables to run run-test.sh inside of the container.
* Adds pycodestyle to the testing procedure and amends
codebase to comply. (closes #2433)
* Enriches ``run-tests.sh`` with manifest check.
Signed-off-by: Jan Okraska <jan.okraska@cern.ch>
=> tests: addition of pycodestyle

cernopendata/modules/fixtures/data/docs/cod-privacy-policy/cod-privacy-policy.json, cernopendata/modules/fixtures/data/records/cms-open-data-instructions.json, cernopendata/modules/fixtures/data/records/lhcb-antimatter-matters-2017.json, run-tests.sh
Fix #2442
- Dataset:
- `Matter Antimatter Differences (B meson decays to three hadrons) - Data Files `
http://opendata.cern.ch/record/4900
-> Collision
- Documentation:
- `CERN Open Data Privacy Policy `
http://opendata.cern.ch/docs/privacy-policy
-> Policy
- `CMS Pile-up Simulation`
http://opendata.cern.ch/record/70
-> Guide
- `CMS Simulated Dataset Names`
http://opendata.cern.ch/record/71
-> Guide
=> Fixtures: enrich json with secondary category

cernopendata/modules/fixtures/data/terms/terms.json
Add more items to glossary.
Some of the entries start with upper case letter, some with lower case letter. Should we uniformise this? The alphabetical ordering of the portal is case sensitive.
Do we need more items there as well?
Fix #1920
=> Glossary: more terms

cernopendata/modules/fixtures/data/docs/simulated-dataset-categories/simulated-dataset-categories.json, cernopendata/modules/fixtures/data/docs/simulated-dataset-categories/simulated-dataset-categories.md
New page with description of the categories for MC datasets.
Latest categorisation results for CMS datasets:
- https://hpascoal.web.cern.ch/hpascoal/tmp/2018-11-29-results/
- https://hpascoal.web.cern.ch/hpascoal/tmp/2018-11-29-categorisation/
=> docs: categorisation of MC datasets

cernopendata/modules/fixtures/data/records/cms-condition-data-2012.json, cernopendata/modules/fixtures/data/records/cms-condition-data-Run2011A.json
=> Fixes typo in the description of record 1802

DEVELOPING.rst, cernopendata/modules/fixtures/data/docs/cms-guide-for-education/cms-guide-for-education.md, cernopendata/modules/markdown/ext.py, requirements-production.txt
- python-markdown 2.6.11 -> 3.0.1
- pymdown-extensions 5.0.0 -> 6.0.0
Add extensions:
- markdown.extensions.attr_list
- markdown.extensions.toc
fix #1842
Update DEVELOPING.rst with markdown and latex tips
To add a Table Of Contents to a document place the identifier `[TOC]`  where you want it to be. It will translate all the headers into a Table Of Contents with the appropriate links.
=> Installation: bump markdown engines version.

cernopendata/config.py, cernopendata/jsonschemas/records/record-v1.0.0.json, cernopendata/mappings/records/record-v1.0.0.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2011A.json, cernopendata/templates/cernopendata/search.html
* Changes record structure from `topic` to `categories` with a possibility of
having one primary and several secondary categories.  Amends JSON data model
and Elasticsearch mappings and indexes accordingly.  (closes #2475)
=> records: topic becomes categories

cernopendata/modules/fixtures/data/terms/terms.json
PR #2483 changed all entries to start with uppercase, but the references
in "see also" were not updated. This commit fixes it.
Adds a new 'term' for Monte Carlo: "MC". Improves MC definition
=> glossary: fix "see also" terms

cernopendata/modules/fixtures/data/records/cms-pileup-datasets-2012.json
* Adds new CMS 2012 pileup dataset and corrects CMS 2011 pileup dataset
information.  Note that some parts e.g. number of ffiles and bytes are still
to be amended.  (addresses #2331)
=> records: CMS 2011 and 2012 pileup datasets

scripts/clean-instance.sh
* Introduces ``--drop`` option for ``clean-instance.sh`` script.  Useful for
running on CERN OpenShift deployments.
=> scripts: drop DB option in clean-instance.sh

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2012.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2011A.json, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
* Updates global tag information in CMS simulated dataset records.
(closes #2499)
=> records: global tag update in CMS simulated datasets

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2010.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2012.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2011A.json, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
* Fixes CMS MC pileup record information and links. (closes #2497)
=> records: fix CMS MC pileup links

cernopendata/modules/fixtures/data/docs/cms-getting-started-2010/cms-getting-started-2010.md, cernopendata/modules/fixtures/data/docs/cms-getting-started-2011/cms-getting-started-2011.md
Closes #2510, some grammatical errors found in CMS getting started 2010 and 2011 docs.
=> Fix grammatical getting started

cernopendata/modules/fixtures/data/records/cms-validation-code-Run2010B.json
* Fixes sizes for several CMS validation software files, solving the truncated
file display over HTTP protocol access. The XRootD protocol access was
working fine. (closes #2509)
=> records: CMS validation software file size fix

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2012.json
* Adds a record example 7682 with the full `methodology.steps` fixture
structure. Note that output dataset information of old might be
missing. (addresses #2506)
=> records: example of methodology.steps fixtures

cernopendata/modules/fixtures/data/records/alice-analysis-modules.json, cernopendata/modules/fixtures/data/records/alice-learning-resources.json
* Verifies all ALICE file sizes and sets file checksums to Adler32.
(addresses #2528)
=> records: ALICE file sizes and checksums

cernopendata/modules/fixtures/data/records/alice-analysis-modules.json, cernopendata/modules/fixtures/data/records/alice-learning-resources.json, cernopendata/modules/fixtures/data/records/atlas-higgs-challenge-2014.json
* Verifies all OPERA file sizes and sets file checksums to Adler32.
(addresses #2528)
=> records: OPERA file sizes and checksums

cernopendata/modules/fixtures/data/records/alice-analysis-modules.json, cernopendata/modules/fixtures/data/records/alice-learning-resources.json, cernopendata/modules/fixtures/data/records/atlas-higgs-challenge-2014.json
* Verifies all ATLAS file sizes and sets file checksums to Adler32.
(addresses #2528)
=> records: ATLAS file sizes and checksums

cernopendata/modules/fixtures/data/records/alice-analysis-modules.json, cernopendata/modules/fixtures/data/records/alice-learning-resources.json, cernopendata/modules/fixtures/data/records/atlas-higgs-challenge-2014.json, cernopendata/modules/fixtures/data/records/data-policies.json, cernopendata/modules/fixtures/data/records/lhcb-antimatter-matters-2017.json
* Verifies all LHCb file sizes and sets file checksums to Adler32. (addresses #2528)
=> records: LHCb file sizes and checksums

cernopendata/jsonschemas/records/record-v1.0.0.json
* Enriches `dataset_semantics` to support `type` and `unit` (addresses #2447).
=> records: enrich record schema

cernopendata/modules/fixtures/data/records/cms-primary-datasets.json
- Adds 12 Run2010A primary data records, addresses #2451 
- Adds a methodology description for BTau Run2010A sample, addresses #2450 
- needs a link to the record from PR #2461
- if it shows OK, the same text can be added to all RunA and  RunB of 2010 in this files
=> Adds Run2010A records

cernopendata/modules/fixtures/data/records/cms-tools-Run2-datascience.json
=> records: adds new CMS ML software records

cernopendata/modules/fixtures/data/records/cms-derived-Run1-datascience.json, cernopendata/modules/fixtures/data/records/cms-derived-Run2-datascience.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run1-datascience.json, cernopendata/modules/fixtures/data/records/cms-tools-Run1-datascience.json
(addresses #2526 & #2575 & #2588)
Adds 4 records for tracker-hit-enriched Run1 AOD, related  records 9582 (for the 1st record), 8882 (for the 3 others)
Adds records for the resulting ML files
Adds record for the SW
For AODSIM, needs:
- modified config files from the github repo (see also  #2588 ) either as records of their own or as files attached to their own record (now links are after FIXME in the config title field
- size of filese
- file indexes: files to be moved from the `/eospublic/cms/upload/emanuele`
- `step2_ttbarOD_0*` for the 1st record
- `step2_QCD300to600` for the 2nd record
- `step2_QCD400to600` for the 3rd record
- `step2_QCD_600to3000_0*` for the 4th record
For ML files, needs:
- remove end-of-lines in table html
- remove quotes if needed for type field in the dataset …
=> Add records for tracker-hit-enriched Run1 AOD and ML files, and SW

cernopendata/modules/fixtures/data/records/cms-tools-Run2-datascience.json
(addresses #2585)
Adds SW record for Run2 Hbb tagging
Needs:
- recids output ML samples
- list of datasets on which this code is run (use_with) is the same as in recid 12102
=> Add SW record for Run2 Hbb tagging studies

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Phase2-datascience.json
Adds 3 data records for upgrade MC samples (addresses #2520)
- ttbar GEN-SIM
- ttbar GEN-SIM-RAW-DIGI
- pileup GEN-SIM
Assumes that the production script and parameters show in previewer as for example in http://opendata-dev.web.cern.ch/record/7728
Needs
- recid's for the records (also in FIXMEs  in cross references in the file)
- 3 config file records (https://github.com/cernopendata/opendata.cern.ch/issues/2520#issuecomment-482808564)
- recid for SW record from #2589
=> Adds data records for upgrade MC samples

cernopendata/modules/fixtures/data/records/cms-derived-Phase2-datascience.json, cernopendata/modules/fixtures/data/records/cms-derived-Run1-datascience.json, cernopendata/modules/fixtures/data/records/cms-derived-Run2-datascience.json
(addresses #2576)
Adds record for the upgrade (phase2) ML files.
Needs:
- indenting in part of the dataset symantics description
- recid & DOI
- recids for the SW to produce the files (from PR #2603) and MC from where it is derived (from PR #2599)
- proper link for the example usage (
The variable description table is very long with many similar entries which differ only by an index number. For any eventual APIs we keep the variables separately in json on purpose, but it would be good to see if they could be hidden/expanded somehow in the record display
=> Add record for ML  files (upgrade pixel seeds)

cernopendata/modules/fixtures/data/records/cms-derived-Run2-datascience.json
* Adds file information for CMS Run2 Hbb derived record. (addresses #2574)
=> records: CMS Run2 Hbb derived files

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Phase2-datascience.json
(addresses #2520)
Adds the dataset in FEVTDEBUGHLT format which is needed for upgrade ML example.
Fixes the provenance for GEN-SIM-DIGI-RAW which comes after FEVTDEBUGHLT in the production chain and maybe not needed. Does no harm to keep it either.
Needs:
- recid for the new record
=> Add FEVTDEBUGHLT dataset to Phase2 MC

cernopendata/modules/fixtures/data/records/cms-pileup-datasets-2011.json, cernopendata/modules/fixtures/data/records/cms-pileup-datasets-2012.json
(addresses and closes #2331 and #2446) 
Updates 2011 and 2012 pileup records with the provenance information
Needs
- config file record for SIM steps:
- https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/af4431aa75037618429e3164db9f3415/configFile
- https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/e75da0ef8a4c51a102040e9de55704a4/configFile
=> Updates CMS pile-up GEN-SIM records

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2010.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2011A.json, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
- Fixes provenance information for CMS 2010 simulated datasets. (addresses #2613)
=> records: CMS 2010 MC provenance fixes

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2010.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2-datascience.json
* Updates configuration file extraction by consulting McM first and DAS second.
Sorts configuration files alphabetically. (closes #2641)
=> records: CMS MC provenance configuration file updates

cernopendata/modules/fixtures/data/docs/cms-getting-started-2011/cms-getting-started-2011.md, cernopendata/modules/fixtures/data/docs/cms-guide-for-conddb/cms-guide-for-conddb.md, cernopendata/modules/fixtures/data/docs/cms-virtual-machine-2011/cms-virtual-machine-2011.md
(closes #2638 )
Updates the VM version to 1.5.1 in the instructions texts. (not in the VM record itself, it can be updated when the files are added: #2426)
=> docs: update VM version to 1.5.1

cernopendata/modules/fixtures/data/records/cms-primary-datasets-Commissioning2010.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2010-commissioning.json, cernopendata/modules/fixtures/data/records/cms-validated-runs-Commissioning2010-castor.json
(addresses #2606 & #2608 )
Adds 
- 3 records for Commissioning 2010 primary datasets
- corresponding lists of validated runs
- one of the 6 MC records (for the 1st check)
Needs:
- check if the Castor ref in abstract description is OK
- check why parent datasets for MinimumBias appear as ...skim../RAW (not available)
- complete the data selection description
- recid reference of json
- recid for the records
- files listings 
- files are in the upload area for data records
- the validated run lists
- https://twiki.cern.ch/twiki/pub/CMSPublic/CASTOROpenData2010/Commissioning10-May19ReReco_900GeV.json 
- https://twiki.cern.ch/twiki/pub/CMSPublic/CASTOROpenData2010/Commissioning10-May19ReReco_7TeV.json 
- see if the CASTOR instruction twiki (referred to in the usage) should be written as a …
=> Add data records related to castor

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2010-commissioning.json
Adds the remaining MC files, to check with Hans (when on dev)
- beam spot definition in the production script (all 7TeV, probably not correct)
- run period (not shown in record but is in json) Commissioning2010
=> records: updates to castor files

nginx/cernopendata.conf
* Accepts more file types when using the EOS HTTP gateway. (closes #2658)
=> nginx: more file types for EOS HTTP gateway

cernopendata/modules/fixtures/data/records/cms-condition-data-2012.json, cernopendata/modules/fixtures/data/records/cms-condition-data-Phase2-datascience.json, cernopendata/modules/fixtures/data/records/cms-condition-data-Run2-datascience.json
(closes #2456)
(closes #2443)
Adds:
- the record for run-dependent 2012 GT START53_V7N - New recid 1805
- the record for Run2 MC GT - recid 1806
- the record for Phase2 MC GT - recid 1807
NB: "date created" for Phase2 GT : "Phase2"
Needs:
- file attachements in a similar way as for 1804?
=> records: Add  GTs for 2012, 2016 and upgrade MC

cernopendata/modules/fixtures/data/records/cms-primary-datasets-Commissioning2010.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2010-commissioning.json
(closes #2665)
Fixes:
In data records:
- links to 2010 VM
- add energy in the name (otherwise two equal)
- add 0.9 and 7 TeV for ZeroBias 
- links to validated run as list
- energies as list
In MC records:
- links to 2010 VM (adds a special mention of it for 2011 MC)
- changes the 2.76 Tev MC to Run2011A (in titles and in `data_created`)
- fixes the cmsDriver input parameters
- adds config files, with url links
=> records: fixes to CASTOR records

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2010-commissioning.json
(closes #2677)
Removes cmsdriver script from the CASTOR MC provenance (conflicts with the config files) as agreed with Hans
=> records: remove cmsdriver script from CASTOR MC provenance

cernopendata/modules/fixtures/data/records/cms-pileup-datasets-2011.json, cernopendata/modules/fixtures/data/records/cms-pileup-datasets-2012.json
(closes #2675)
Corrects the MC categories for 2011 and 2012 pile-up samples
=> Records: Add categories to pileup samples

cernopendata/modules/fixtures/data/records/cms-derived-Run1-datascience.json, cernopendata/modules/fixtures/data/records/cms-derived-Run2-datascience.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Phase2-datascience.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run1-datascience.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2-datascience.json, cernopendata/modules/fixtures/data/records/cms-tools-Run1-datascience.json
(addresses #2655)
(closes #2654)
Fixes to Phase2 MC records:
- date_created Phase2 (2019 makes no sense to indicate the year data taking)
- text improvements in the description
Fixes to Run1 SW record:
- add workflow figure
- add links to usage examples in cernopendata-datascience repositories
Fixes to Run1 MC records
- abstract text
- add url to configs (fixes legacydata -> opendata, and master -> v12.0.0 in config links)
Fixes to Run2 MiniAODSIM
- abstract text (plural/singular)
- add mention of pileup events
=> records: final fixes to ML records

cernopendata/modules/fixtures/data/records/cms-derived-Phase2-datascience.json, cernopendata/modules/fixtures/data/records/cms-derived-Run1-datascience.json, cernopendata/modules/fixtures/data/records/cms-derived-Run2-datascience.json
* Adds file indexes to CMS datascience samples. (closes #2671)
=> records: CMS data science file indexes

cernopendata/templates/cernopendata_records_ui/records/macros/links.html
* Fixes display of pileup links and other related lists using ``recid`` for
linking. (closes #2616)
=> templates: fix display of pileup links

cernopendata/modules/fixtures/data/records/cms-derived-Run1-datascience.json, cernopendata/modules/fixtures/data/records/cms-raw-datasets-Run2010B.json, cernopendata/modules/fixtures/data/records/cms-raw-datasets-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-raw-datasets-Run2012B.json
* Adds file indexes for all CMS RAW samples. (addresses #2439)
* Fixes number of events information for CMS Run1 data science derived dataset.
=> records: CMS RAW samples file indexes

cernopendata/modules/fixtures/data/records/cms-derived-Run1-datascience.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run1-datascience.json
* Fixes CMS Run1 datascience records to split file indexes to given datasets.
Fixes number of events in each dataset. (addresses #2575)
=> records: CMS Run1 datascience file index fixes

cernopendata/modules/fixtures/data/records/cms-validated-runs-Commissioning2010-castor.json
(closes #2608)
Adds files and file sizes to Commissioning validated run records
=> records: adds files to commissioning validated runs

cernopendata/templates/cernopendata_records_ui/records/record_detail.html
* In CMS MC provenance block, link to CMS configuration files if we know CMS
ConfDB ID.  (closes #2642)
=> templates: CMS MC configuration file links

cernopendata/modules/fixtures/data/docs/cms-guide-docker/cms-guide-docker.json
(closes #2695)
Add text to be shown in the search view without md
=> docs: add a non-md short_description to docker guide

cernopendata/templates/cernopendata_records_ui/records/macros/links.html
* Fixes link label for references linked via recids only. (addresses #2616)
=> templates: fix for recid-based link label

cernopendata/modules/fixtures/data/records/cms-tools-Phase2-datascience.json, cernopendata/modules/fixtures/data/records/cms-tools-Run1-datascience.json, cernopendata/modules/fixtures/data/records/cms-tools-Run2-datascience.json, cernopendata/modules/fixtures/data/records/cms-tools-eventproduction-examples.json
(closes #2344)
(closes #2588 )
(closes #2585)
(closes #2589)
Adds` files` and `distribution` to SW tools
- 3 EventProductionExamplesTool records
- 1 Run1 datascience record
- 2 Run2 datascience record
- 1 Phase datascience record
Fixes the github link in `usage` for 2 records
=> records: add files to SW records

cernopendata/templates/cernopendata_records_ui/records/detail.html
* Makes file index modal window larger, fixing display problems for files with
long filenames. (closes #2572)
=> templates: larger file index modal window

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run1-datascience.json
(closes #2526)
- cleans the config file link text
- points the link to raw.githubusercontent.com
=> records:. clean config file links

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2-datascience.json
* Fixes incorrect file sizes and checksums for CMS MC datasets that were added
in 524cf69a8 and 9063ee1e7. The incorrect file sizes made the file index
download to be terminated prematurely, causing troubles in "List of files"
display facility. (closes #2689)
* Checked complete ALICE, ATLAS, CMS, LHCb fixtures for rich index files to
ensure there are no other similar troubles of this kind.
=> records: CMS MC file size and checksum fixes

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2011A.json
* Amends record fixtures after recovering missing file for CMS 2011 MC
WJetsToLNu dataset. (closes #2531)
=> records: CMS 2011 MC WJetsToLNu missing file fix

cernopendata/jsonschemas/records/record-v1.0.0.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2011A.json
* Updates CMS 2011 MC records generator information by moving it to the SIM
step as for 2010 2012 etc records. (closes #2700)
* Amends data model to remove the ``generator`` field now that it is no longer
used by any record.
=> records: CMS 2011 MC generator information

cernopendata/modules/fixtures/data/records/cms-primary-datasets.json
(closes #2451)
Adds files indexes to Run2010A primary dataset
=> records: add file indexes to Run2010A

cernopendata/modules/fixtures/data/records/cms-primary-datasets-Commissioning2010.json
(closes #2343)
Adds files indexes to 2010 Commissioning primary datasets
=> records: add file indexes to 2010 Commissioning

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2011A.json
* Amends record fixtures after recovering missing file for CMS 2011 MC
BuToKstarMuMuV2 dataset. (addresses #2710)
=> records: CMS 2011 MC BuToKstarMuMuV2 missing files

cernopendata/jsonschemas/records/record-v1.0.0.json, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
* Introduces ``number_entries`` into the data model and the templates. Useful
for datasets not containing events. (closes #2622)
=> models: number of entries

cernopendata/modules/fixtures/data/docs/cms-getting-started-2011/cms-getting-started-2011.md, cernopendata/modules/fixtures/data/docs/cms-virtual-machine-2011/cms-virtual-machine-2011.md
(closes #2729)
Adds the explanation for the common error when using double shell VM to install VM and getting started. just after the cmsrel command.
=> docs: add mention about the wrong shell

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2011A.json
* Amends record fixtures after recovering missing file for CMS 2011 MC
GluGluToHToZZTo2L2Nu simulated dataset. (closes #2710)
=> records: CMS 2011 MC GluGluToHToZZTo2L2Nu missing file

cernopendata/modules/fixtures/data/docs/cms-guide-pileup-simulation/cms-guide-pileup-simulation.md
(closes #2743)
Updates link to the twiki page which is now in CMSPublic domain
=> docs: update link

cernopendata/modules/fixtures/data/records/cms-derived-nanoaod-outreach-DoubleMuParked.json, cernopendata/modules/fixtures/data/records/cms-tools-nanoaod-outreach-dimuon-spectrum.json
* Adds DOIs to the three CMS NanoAOD records. (closes #2636)
=> records: DOIs for CMS NanoAOD examples

cernopendata/modules/fixtures/data/records/cms-csv-files.json, cernopendata/modules/fixtures/data/records/cms-derived-csv-2012.json, cernopendata/modules/fixtures/data/records/cms-derived-csv-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-masterclass-files.json
*  Adds education keyword and dataset semantics to outreach records.
(addresses #2774)
Co-authored-by: Juha-Matti Teuho <juha.teuho@gmail.com>
Signed-off-by: Linda Hemmann <linda.hemmann@gmail.com>
=> records: CMS educational data updates

cernopendata/modules/fixtures/data/docs/cms-guide-docker/cms-guide-docker.md
* Fix link to dockerhub in http://opendata.cern.ch/docs/cms-guide-docker
* Closes #2786
=> Docker hub link in instructions

cernopendata/modules/fixtures/data/records/cms-primary-datasets-Run2012B.json, cernopendata/modules/fixtures/data/records/cms-primary-datasets-Run2012C.json, cernopendata/modules/fixtures/data/records/cms-raw-datasets-Run2012B.json
(closes #2790)
Corrects GT to be used in analysis in system_details
To do while merging:
- change all records as now the first one in the file (FT_53_LV5_AN1 -> FT53_V21A_AN6)
=> records: correct GT for CMS 2012 primary datasets

cernopendata/modules/fixtures/data/docs/cms-observing-higgs-2017/cms-observing-higgs-2017.json, cernopendata/modules/fixtures/data/docs/cms-releases-open-data-for-machine-learning-2019/cms-releases-open-data-for-machine-learning-2019.json, cernopendata/modules/fixtures/data/docs/opera-event-reconstruction/opera-event-reconstruction.json, cernopendata/modules/fixtures/data/docs/opera-event-reconstruction/opera-event-reconstruction.md, cernopendata/modules/fixtures/data/docs/opera-news-first-release/opera-news-first-release.json, cernopendata/modules/fixtures/data/docs/opera-releases-charm-nue-samples-2019/opera-releases-charm-nue-samples-2019.json, cernopendata/modules/fixtures/data/docs/opera-releases-charm-nue-samples-2019/opera-releases-charm-nue-samples-2019.md, cernopendata/modules/fixtures/data/records/opera-detector-events-charm.json, cernopendata/modules/fixtures/data/records/opera-detector-events-electron.json, cernopendata/modules/fixtures/data/records/opera-ecc-datasets.json, cernopendata/modules/fixtures/data/records/opera-ed-datasets.json
Adds records generated by cernopendata/data-curation#58
=> records: OPERA electron neutrino events

Dockerfile
* Adds more dependency packages in order to fix the build failures that
started to appear with new CentOS 7 related updates.
=> docker: more dependency packages

Dockerfile, requirements-production.txt
Upgrades XRootD to the latest stable 4.12.2 version. This fixes recent
Docker building troubles, and will also help in the stability of
downloading big files as per the latest xrootdpyfs improvements.
Note: the commit uses xrootdpyfs from GitHub, as the new stable
version was not released on PyPI yet.
Closes #2258.
=> installation: xrootd 4.12.2

cernopendata/modules/fixtures/data/docs/cms-guide-for-conddb/cms-guide-for-conddb.md, cernopendata/modules/fixtures/data/docs/cms-virtual-machine-2010/cms-virtual-machine-2010.md, cernopendata/modules/fixtures/data/docs/cms-virtual-machine-2011/cms-virtual-machine-2011.md, cernopendata/modules/fixtures/data/records/cms-tools-vm-image-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-tools-vm-image.json
(closes #2847) 
To do at merge:
- vm file for record 252 from  https://cernvm.cern.ch/releases/CMS-OpenData-1.5.3.ova
- the 3 context files for the **new record 257** from root://eospublic.cern.ch//eos/opendata/cms/environment/1.5.2/
- vm file for record 250 from https://cernvm.cern.ch/releases/CMS-OpenData-1.1.4.ova
- the context file cms-user-data.txt for the **new record 248** from https://raw.githubusercontent.com/cernvm/public-contexts/master/cms-opendata.context , the two others scripts the same as 1.5.2 (see above)
=> Update VMs to 1.5.3 and 1.1.4

cernopendata/modules/fixtures/data/records/cms-luminosity-information.json
(closes #2864)
Updates the description wording to take into account that all 2011 data is public.
@caredg  Is there something we should add w.r.t  #2737 ?
=> Update luminosity description

cernopendata/modules/fixtures/data/records/cms-derived-nanoaod-outreach-higgstautau.json
(closes #2822)
Adds nanoaod tag to the Htautau example files so that they appear in search
=> CMS: update nanoaod tag

cernopendata/modules/fixtures/data/records/cms-validation-code-Castor2010.json
(addresses #2854 )
Adds the Castor validation SW record, to do:
- when the repository has been moved from cms-legacydata-validation to cms-opendata-validation, add the zip file
- DOI
=> Add Castor validation sw record

cernopendata/modules/fixtures/data/records/cms-raw-datasets-Run2010B.json, cernopendata/modules/fixtures/data/records/cms-raw-datasets-Run2011A.json
For 2010 and 2011 records, use "Configuration file..." leading text,
since the files are precise.
For 2012 records, keep using "Example configuration file..." leading
text.
Closes #2799.
=> records: CMS raw sample leading text

cernopendata/config.py, cernopendata/mappings/records/record-v1.0.0.json, cernopendata/templates/cernopendata/search.html
- Adds 'event_number'-facet to Open Data Portal.
- NOTE! Implementation for the range_filter is still required. At the moment, filter is missing and therefore the facet doesn't work correctly.
(addresses #2785)
Signed-off-by: Juha-Matti Teuho <juha.teuho@gmail.com>
=> facets: Add event_number facet

cernopendata/modules/fixtures/data/docs/cms-guide-docker/cms-guide-docker.md
(closes #2849)
- Adds WSL2 instructions
- Adds mention of the  lowpupatch container for castor
- X11 forwarding
- fixes link to docker hub 
- add cvmfs instructions
=> update docker instructions

cernopendata/modules/fixtures/data/records/cms-primary-datasets-Commissioning2010.json
(closes #2854 )
Updates the commissioning record to refer to castor sw for "How to use"
=> Update castor record

cernopendata/modules/fixtures/data/records/atlas-higgs-challenge-2014.json, cernopendata/modules/fixtures/data/records/cms-learning-resources.json, cernopendata/modules/fixtures/data/records/cms-open-data-instructions.json, cernopendata/modules/fixtures/data/records/cms-tools-ana-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-tools-reco.json, cernopendata/modules/fixtures/data/records/data-policies.json
* Adds ROR IDs to any records that had affiliation information
* Standardises affiliations in accordance with the INSPIRE institutions
database (not possible for Lapland University, ChaLearn ~~and INRIA~~,
those were added in approximation)
* (closes #2894)
=>  records: mvp for ror ids

cernopendata/templates/cernopendata_records_ui/records/record_detail.html
Fixes ROR links for authors with multiple affiliations where values
were not properly trimmed regarding whitespace.
=> templates: fix ROR links

cernopendata/modules/fixtures/data/records/cms-primary-datasets-HIRun2010.json
(closes #2910 )
These records have very limited provenance information as it is not recorded in DAS. Some generic information could possibly be added.
=> CMS - 2020 HI records

cernopendata/modules/fixtures/data/records/cms-primary-datasets-HIpp-Run2011A.json
Adds file information for CMS Run2011A pp HI reference datasets.
Closes #2938.
=> records: CMS Run2011A pp HI file information

cernopendata/modules/fixtures/data/records/cms-primary-datasets-HIRun2010.json, cernopendata/modules/fixtures/data/records/cms-primary-datasets-HIRun2011.json, cernopendata/modules/fixtures/data/records/cms-primary-datasets-HIpp-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-validated-runs-HIRun1.json
(closes #2943 )
- Adds keyword "heavy-ion physics" to all new data records and lists of validated runs
- Changes the description for the reference pp data
=> CMS: add a keyword and change the pp  description

cernopendata/modules/fixtures/data/records/cms-tools-heavyion-examples.json
(closes #2958)
Adds heavy-ion physics keyword to the new HI SW records 466 and 467
=> CMS: Add keyword to HI sw records

cernopendata/modules/fixtures/data/docs/cms-guide-docker/cms-guide-docker.md
(closes #2953)
Adds the minimal changes to the docker guide for the HI images. At a certain point, the rest of the links should be updated to the CMS gitlab registry as well.
=> CMS - add a mention on HI images in docker guide

cernopendata/modules/fixtures/data/records/cms-tools-heavyion-examples.json
(closes #2946)
Updates the HI example repository links.
To-do:
- add the respective zip files from https://github.com/cms-opendata-analyses/HiForestProducerTool/tags
=> CMS: update HI sw repository

Dockerfile, setup.py
- Upgraded `node` version from 6 to 14
- Upgraded `npm` version from `3.10.10` to `6.14.5`
- Upgraded `node-sass` and `d3` npm packages to make it compatible with the newer `node` version
- Added `--unsafe-perm` param for installing npm packages to suppress permission error
- Temporary commented `opera` bundles
closes #2981
=> docker: upgrade node version

cernopendata/modules/fixtures/data/records/alice-analysis-modules.json, cernopendata/modules/fixtures/data/records/alice-reconstructed-data.json
Adds "heavy-ion physics" keyword to ALICE records. Only PbPb datasets,
since the published pp dataset samples are not of the heavy-ion
reference run nature. Checked with Mihaela Gheata and Stefano Piano.
=> records: ALICE heavy-ion physics keywords

cernopendata/modules/theme/bundles.py, setup.py
This PR was developed with [angular packages removed](https://github.com/cernopendata/opendata.cern.ch/pull/2987) from npm bundles
closes #2925
=> ui: made opera to work with the latest node version

cernopendata/modules/theme/bundles.py
- commented out all `angular` dependencies so that it would be visible which ones was used while working on the `react` migration
- tested this PR on [upgraded `node` version](https://github.com/cernopendata/opendata.cern.ch/pull/2985)
- compiled a list of pages which still work and which broke after removing the `angular` packages
- in summary all the pages which are using `jinja` templates only seems to work as expected
- all the other ones which uses: `(i) search, (ii) file download box, (iii) visualise events (opera), (iv) visualise histograms` were broken and could be tackled individually
List of pages which are working as expected:
- "/visualise/events" 
- "/visualise/events/cms" 
- "/glossary/json" 
- "/sitemap.xml"
- "/ping"
- "/"
- "/docs/<pid_value>"
- 404 page
List of pages …
=> frontend: removed all angular packages from npm bundles

cernopendata/modules/fixtures/data/docs/cod-privacy-policy/cod-privacy-policy.md
Here's what it looks like after the changes:
closes #2931
=> docs: updated privacy policy page with RoPO

cernopendata/modules/theme/assets/semantic-ui/js/glossary/jquery.zglossary.css, cernopendata/modules/theme/assets/semantic-ui/js/glossary/jquery.zglossary.js, cernopendata/modules/theme/bundles.py, cernopendata/modules/theme/webpack.py, cernopendata/templates/cernopendata_theme/page.html, setup.py
The glossary can be tested, among others, with the following records:
- Docs: prod - http://opendata.cern.ch/docs/about-opera, local - http://0.0.0.0:5000/docs/about-opera
- Record: prod - http://opendata.cern.ch/record/48, local - http://0.0.0.0:5000/record/48
E.g.:
* Addresses #2997.
=> frontend: migrates glossary bundle to webpack

cernopendata/config.py, cernopendata/modules/theme/assets/semantic-ui/scss/styles.scss, cernopendata/templates/cernopendata_records_ui/docs/detail.html
Closes #3004
This can be tested with any of the records [listed here](http://opendata.cern.ch/search?page=1&size=20&q=&type=Documentation&subtype=About&subtype=Activities&subtype=Authors&subtype=Guide&subtype=Help&subtype=Policy&subtype=Report). To populate them locally:
```
$ docker exec -i -t opendatacernch_web_1 /code/scripts/populate-instance.sh --skip-records
```
Special case with related records:  http://opendata.cern.ch/docs/cms-physics-objects-2010
=> frontend: migrate docs record view to Semantic UI

cernopendata/config.py, cernopendata/modules/theme/assets/semantic-ui/scss/styles.scss, cernopendata/templates/cernopendata_records_ui/docs/detail.html, cernopendata/templates/cernopendata_records_ui/terms/detail.html, cernopendata/templates/cernopendata_theme/page.html
* Closes #3003.
Depends on (and includes) https://github.com/cernopendata/opendata.cern.ch/issues/3004.
This can be tested with any of the records [listed here](http://opendata.cern.ch/search?page=1&size=20&type=Glossary&sort=title). To populate them locally:
```
$ docker exec -i -t opendatacernch_web_1 /code/scripts/populate-instance.sh --skip-records
```
=> frontend: migrate glossary to Semantic UI

cernopendata/templates/cernopendata_theme/header.html
@mvidalgarcia Noticed ALICE typo, probably happened due to `li -> div` element automated editor replacements. Perhaps you can recall (and check) other parts of the code base where `<li>` vs `li` replacements (when moving to Semantic UI) could have caused similar typos?
=> templates: fix ALICE

cernopendata/modules/fixtures/data/docs/cms-simulated-dataset-names/cms-simulated-dataset-names.md, cernopendata/modules/fixtures/data/docs/cms-virtual-machine-2010/cms-virtual-machine-2010.md, cernopendata/modules/theme/assets/semantic-ui/scss/styles.scss, cernopendata/templates/cernopendata_pages/md_template.html
* Fixes horizontal scrolling for code blocks.
* Removes code background color coming in new versions of Python
markdown package.
Used `find ./ -name "*.md" | xargs grep -e "</.*>" ` to find markdown files using HTML
Closes #3007
=> frontend: fix markdown rendered pages

DEVELOPING.rst, cernopendata/modules/theme/assets/semantic-ui/js/app.js, cernopendata/modules/theme/assets/semantic-ui/scss/styles.scss, cernopendata/modules/theme/bundles.py, cernopendata/modules/theme/static/assets/ispy/bootstrap-prefixed.css, cernopendata/modules/theme/static/assets/ispy/ispy-prefixed.css, cernopendata/templates/cernopendata_ispy/ispy_css.html, cernopendata/templates/cernopendata_ispy/ispy_js.html, cernopendata/templates/cernopendata_pages/visualise_events.html, cernopendata/templates/cernopendata_pages/visualise_events_cms.html, cernopendata/templates/cernopendata_pages/visualise_events_cms_standalone.html, cernopendata/templates/cernopendata_records_ui/records/detail.html, cernopendata/templates/cernopendata_records_ui/records/record_detail.html, cernopendata/templates/cernopendata_theme/page.html, scripts/create-instance.sh
addresses #3008
Covers:
- http://opendata.cern.ch/visualise/events
- http://opendata.cern.ch/visualise/events/cms (main CMS visualizer entry)
- http://opendata.cern.ch/record/632 (embedded visualizer example)
Steps to test `record/632`:
- `docker exec -i -t opendatacernch_web_1 /code/scripts/populate-instance.sh --skip-files`
- `docker exec -i -t opendatacernch_web_1 bash -c "cernopendata fixtures records -f /code/cernopendata/modules/fixtures/data/records/cms-eventdisplay-files-Run2011A.json --mode insert-or-replace"`
~~Right now there is still a big problem with conflicting Bootstrap and Semantic UI styles, especially visible on embedded view.
It can be solved in a separate issue by limiting the scope of `Bootstrap` styles or use some different techniques to resolve these conflicts.~~ …
=> ui: make CMS visualizer compatible with Webpack

cernopendata/mappings/v7/records/record-v1.0.0.json
=> search: add analyzer for title search

cernopendata/modules/theme/assets/semantic-ui/js/glossary/jquery.zglossary.js, cernopendata/templates/cernopendata_theme/page.html
* Avoids that strings like `\tau` get rendered as a glossary
term tooltips, instead of a MathJax expressions.
* Closes #3043.
=> glossary: ignore terms inside MathJax expressions

cernopendata/modules/theme/assets/semantic-ui/js/search/app.js, cernopendata/modules/theme/assets/semantic-ui/scss/search.scss, cernopendata/modules/theme/assets/semantic-ui/scss/styles.scss, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
closes #3045
closes #3057
- increased general font size in the records page to unify it across the application
- fixed pagination bug
- removed additional search box
- pushed facets to the top and aligned to `results found`
Screenshot:
- also fixed styling of "availability" box (https://github.com/cernopendata/opendata.cern.ch/issues/3057)
To test, please use:
```
docker-compose exec web cernopendata fixtures records -f /code/cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2012.json --mode insert-or-replace
```
and check `http://localhost:5000/record/13072`
For comparison on the left side is the new style, on the right is what we currently have:
=> ui: small improvements on search page styling

cernopendata/modules/theme/assets/semantic-ui/js/visualise/visualise_histograms.js, cernopendata/modules/theme/assets/semantic-ui/scss/visualise.scss, cernopendata/templates/cernopendata_pages/visualise_histograms.html
closes #3052
This fix loads first plot by default once a new event type is selected and on initial page load. It solves the race condition described [here](https://github.com/cernopendata/opendata.cern.ch/issues/3052#issuecomment-777310981).
Also, some styling improvements are done. Here is how it looks like now:
To test please see the instructions [here](https://github.com/cernopendata/opendata.cern.ch/pull/3032)
=> histograms: load first plot by default

cernopendata/modules/theme/assets/semantic-ui/scss/styles.scss, cernopendata/modules/theme/static/assets/ispy/ispy.css, cernopendata/templates/cernopendata_ispy/ispy_css.html, cernopendata/templates/cernopendata_ispy/ispy_help.html
closes #3069
- Removed some css leftovers from global styles and created a separate file for custom ispy css
Result:
=> ui: fix CMS visualiser documentation arrangement

cernopendata/config.py, cernopendata/mappings/v7/records/record-v1.0.0.json, cernopendata/modules/records/search/query.py, tests/test_cernopendata_query_parser.py
=> search: configure query parser for handling special characters

cernopendata/modules/theme/assets/semantic-ui/scss/search.scss
addresses #3080
Fixed:
- When some item is selected from the facet list the whole facet box bounces up for fraction of a second
- On `No results found!` state facet box is rendered incorrectly
- Footer images are off on search page
- Added some space between footer and facets/search results
=> ui: improved styling of search page

.github/workflows/ci.yml, cernopendata/modules/fixtures/data/records/cms-pileup-datasets-2012.json
Fixes records to point to proper CMS VM 2011 link also for 2012 records.
Closes #3088.
=> records: fix CMS VM 2011 link

cernopendata/modules/theme/assets/semantic-ui/js/search/components/ListItemLabels.js
- root cause: `metadata.experiment` is an array of objects for
glossary records whereas it's an string for the rest of records.
closes #3082
=> ui: fix react children problem

cernopendata/modules/fixtures/data/records/data-policies.json
(closes #2892 )
Created a new record for the 2020 update of the CMS data policy. Adds links to the updated policy in the older versions.
Needs:
=> Record for 2020 CMS data policy 

cernopendata/modules/fixtures/data/docs/cms-guide-pileup-simulation/cms-guide-pileup-simulation.md
Closes #3162 
Adds a description of the 2015 pileup profile to `docs/cms-guide-pileup-simulation`
=> CMS 2015 pileup info

cernopendata/modules/fixtures/data/docs/cms-getting-started-2015/cms-getting-started-2015.md, cernopendata/modules/fixtures/data/docs/cms-guide-docker/cms-guide-docker.md
closes #3163 
Updates the CMS docker guide page for 2015 data. 
Adds a link to it from the CMS getting started 2015.
=> Update for CMS docker guide

cernopendata/modules/fixtures/data/docs/cms-about/cms-about.md, cernopendata/modules/fixtures/data/docs/cms-physics-objects-2010/cms-physics-objects-2010.json, cernopendata/modules/fixtures/data/docs/cms-physics-objects-2015/cms-physics-objects-2015.json, cernopendata/modules/fixtures/data/docs/cms-physics-objects-2015/cms-physics-objects-2015.md
(closes #3178)
- new physics object page for 2015
- add related field to old pages
- small modification to about CMS
=> CMS 2015 physics object page

cernopendata/modules/fixtures/data/docs/cms-guide-for-conddb/cms-guide-for-conddb.md, cernopendata/modules/fixtures/data/records/cms-condition-data-2015.json
(closes #3172)
(closes #3173) 
- Updates condition database guide for 2015 GTs
- Adds two records for condition data
-  (we should think of making them better, now they just tell that they are available on /cvmfs but nothing more)
=> update conddb guide

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2015-pileup.json
(closes https://github.com/cernopendata/data-curation/issues/101)
Adds the record for the 2015 pileup
To do:
- file indexes from `/eos/opendata/cms/mc/RunIISummer15GS/MinBias_TuneCUETP8M1_13TeV-pythia8/GEN-SIM/MCRUN2_71_V1-v2/`
- configuration file can be copied from `/eos/opendata/cms/upload/kati/eb761610a546849c590da9904d70c385.configFile.py`
=> CMS 2015 pileup gensim

cernopendata/modules/fixtures/data/records/data-policies.json
Adds CERN Open Data policy for LHC Experiments document to the
existing ALICE data policy document. Closes #3168.
=> docs: ALICE data policy update

cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2012-added.json
(closes #3150)
Adds a simulated 2012 minbias dataset
To do:
- change recid from 100000 to a number in 2012 simulated data range
- copy config files to upload (I'll take care)
- build file indexes (file are in `/eos/opendata/cms/mc/Summer12_DR53X/MinBias_TuneZ2star_8TeV-pythia6/AODSIM/PU_S10_START53_V7A-v1/`)
=> CMS: add a 2012 minbias dataset

cernopendata/modules/fixtures/data/records/cms-tools-nanoaod-outreach-dimuon-spectrum-julia.json
(closes #3167 )
Adds the record for the Julia implementation of the di-muon example.
To do
- add zip of https://github.com/cms-opendata-analyses/DimuonSpectrumNanoAODOutreachAnalysisJulia/releases/tag/v1.0.0
=> Add julia example

docker-compose-dev.yml, docker-compose.yml
Updates elasticsearch docker image to 7.16.1 which is fixing the
possible Log4Shell CVE vulnerability.
=> docker: elasticsearch 7.16.1

docker-compose-dev.yml, docker-compose.yml
Adds JVM log4j option to protect against RCE vulnerability.
=> docker: set JVM log4j option

cernopendata/modules/fixtures/data/records/cms-pileup-datasets-2011.json, cernopendata/modules/fixtures/data/records/cms-pileup-datasets-2012.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2015-pileup.json, cernopendata/modules/fixtures/data/records/data-policies.json
Adds DOI to the CMS 2015 pile-up record. Closes #3199.
=> records: CMS 2015 pile-up DOI 

cernopendata/modules/fixtures/data/records/cms-pileup-datasets-2012.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2012-added.json, cernopendata/modules/fixtures/data/records/cms-tools-nanoaod-outreach-dimuon-spectrum-julia.json
Adds DOIs for CMS 2015 analysis example and CMS 2012 added dataset
records.
Fixes DOI for CMS 2012 pile-up record.  (Not released yet.)
Closes #3214.
=> records: more DOIs for CMS 2012 and 2015 records

cernopendata/modules/fixtures/data/records/cms-tools-vm-image-Run2011A.json
(closes #3236 )
Adds 2015 in the VM record title and description.
Adds a link to the 2015 VM install instructions
=> CMS VM 2015 updates

cernopendata/modules/fixtures/data/records/cms-validation-code-Castor2010.json
(closes #2911)
Fixes the link to the docker instructions
=> records: fix link in CMS rec 465

cernopendata/modules/fixtures/cli.py, scripts/populate-instance.sh
Adds CLI options `--file` and `--mode` when loading glossary terms.
Allows to update selectively some terms without touching others. Useful
for fast production updates. This change makes the glossary term loading
process on par with docs loading and record loading.
=> cli: fixtures glossary --file and --mode options

AUTHORS.rst, cernopendata/modules/records/serializers/basic_json.py
Added a conditional to check and remove empty buckets in the event_number dictionary of the aggregations part of search results.
=> fixes filter event_number auto hide closes #3263

cernopendata/modules/theme/static/scss/frontpage.scss, cernopendata/templates/cernopendata_pages/front/news.html
Added spaces between badges in the news and updates section to keep in line with the general site theme.
Requesting a PR directly into production as the master branch has a lot of diff with the production branch
=> added spaces between badges in news and updates closes #3232

cernopendata/modules/fixtures/data/records/cms-primary-datasets-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-primary-datasets-Run2011B.json, cernopendata/modules/fixtures/data/records/cms-primary-datasets-Run2012B.json, cernopendata/modules/fixtures/data/records/cms-primary-datasets-Run2012C.json, cernopendata/modules/fixtures/data/records/cms-primary-datasets-Run2015D.json, cernopendata/modules/fixtures/data/records/cms-primary-datasets.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2012-added.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2015-part_15.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2015-pileup.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2-datascience.json, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2011A.json
Amends CMS file index descriptions (which are not visible on the web interface) to remove the mention of CMS VM based access, because users now have a choice to use also the CMS Container based access.
=> records: fix CMS file index descriptions

cernopendata/modules/fixtures/data/records/cms-validated-runs-Run2012B.json
(closes #3285)
- Updates the description of recid 1002 with run ranges of RunA and RunD
- Adds a new record for json file for analyses with muons only with recid 2005 (leaving 2003 and 2004 to the muons-only json for 2010 and 2011, respectively)
To do:
- @tiborsimko Please copy https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions12/8TeV/Reprocessing/Cert_190456-208686_8TeV_22Jan2013ReReco_Collisions12_JSON_MuonPhys.txt to `/eos/opendata/cms/validated-runs/2012/` and add the corresponding `files` json field
=> records: update 2012 cms validated runs

cernopendata/modules/fixtures/data/docs/cms-getting-started-2011/cms-getting-started-2011.md, cernopendata/modules/fixtures/data/docs/cms-getting-started-2015/cms-getting-started-2015.md, cernopendata/modules/fixtures/data/docs/cms-guide-docker/cms-guide-docker.md
(closes #3309)
- adds html anchors to the docker guide and fixes those of getting started 2015
- updates docker docs structure slightly
- updates vnc instructions in docker docs and getting started 2011-2012
=> docs: update docker docs

cernopendata/templates/cernopendata_records_ui/records/record_detail.html
(closes #3158)
Changes the title for the `validation` field to "How was the validation done?" for the validated data records.
=> templates: validation title update

cernopendata/modules/fixtures/data/docs/cms-virtual-machine-2011/cms-virtual-machine-2011.md, cernopendata/modules/fixtures/data/docs/cms-virtual-machine-2015/cms-virtual-machine-2015.md
(closes #3325 )
- updates the 2011/2012 VM instructions after testing
- fixes typos in the 2015 VM instructions
=> docs: update cms 2012 vm instructions

elasticsearch-proxy/Dockerfile, nginx/Dockerfile
Pins nginx perl version to an older release, fixing some reverse-proxy file streaming issues, such as upstream sending invalid "Content-Length: None" response.
=> nginx: 1.22-perl

.github/workflows/ci.yml, Dockerfile, requirements-production.txt, setup.py
Upgrades ipython and downgrades jedi, fixing development setup. Closes #3339.
Solves remaining `pip check` warnings and introduces several `pip check` commands alongside the container image building process in order to catch any possible Python dependency troubles early.
=> docker: clean `pip check` friendly setup

cernopendata/modules/fixtures/data/docs/cms-about/cms-about.md
(closes #3350)
Updates the link to the limited authorship document
=> docs: update CMS internal OD usage link

cernopendata/modules/fixtures/data/records/cms-validated-runs-HIRun1.json
Creates records for validated runs for 2013 HI-related records using
https://github.com/cernopendata/data-curation/tree/master/cms-YYYY-validated-runs
My docker-compose build has trouble so I could not view the records locally.
=> cms-validated-runs_HIRun1.json: add HI2013 related records

cernopendata/templates/cernopendata_records_ui/records/record_detail.html
Adds new collision type badge and fixes collision energy badge links to search in the appropriate facet only. Closes #3378.
=> templates: collision type badge

cernopendata/modules/fixtures/data/records/cms-luminosity-information-HIRun1.json
closes https://github.com/cernopendata/data-curation/issues/171
Adds the json file containing HI related lumi info
The related files to be attached to the records are in the output of
- 1056: 2013 pPb - https://github.com/cernopendata/data-curation/actions/runs/5335970974
- 1057: 2013 ppref - https://github.com/cernopendata/data-curation/actions/runs/5335791862
- 1058: 2015 ppref - https://github.com/cernopendata/data-curation/actions/runs/5335296288
This PR combines `lumi_records` of those outputs in the single file, the remaining files are those to be attached to the respective records
=> records: add CMS Run1 HI related lumi info

DEVELOPING.rst
Closes [#3388](https://github.com/cernopendata/opendata.cern.ch/issues/3388)
updates developing guide to indicate use of docker compose v2 everywhere
=> docs: developing guide using docker compose v2

DEVELOPING.rst, Dockerfile, docker-compose-dev.yml, docker-compose.yml, elasticsearch-proxy/Dockerfile, nginx/Dockerfile, sentry/Dockerfile
Adds container image tags for each dependency, avoiding the use of "latest" tag, for better dependency management.
Adds fully qualified canonical locations of all dependent container images, making the installation and the development processes podman-friendly.
Enriches DEVELOPING guide accordingly.
=> docker: podman-friendly image dependencies

cernopendata/jsonschemas/records/record-v1.0.0.json
fixes [#3386](https://github.com/cernopendata/opendata.cern.ch/issues/3386)
updated records' JSON schema to include container images metadata fields
=> records: update json schema to include container images

cernopendata/modules/fixtures/data/records/cms-hlt-trigger-paths-2012.json, cernopendata/modules/fixtures/data/records/cms-trigger-path-Run2011A.json
Removes collision information and run period information from CMS 2011 2012 HLT trigger path records. Closes cernopendata/opendata.cern.ch#3425.
=> records: CMS HLT 2011 2012 trigger path updates

AUTHORS.rst
Adds my name to the `AUTHORS.rst` file.
=> docs: add missing author

cernopendata/modules/fixtures/data/records/cms-primary-datasets-HIRun2013A.json
Use "real" DOI prefix instead of the "test" one.
=> records: CMS 2013 HI fix DOI prefix

cernopendata/modules/fixtures/data/records/cms-condition-data-HIRun1.json
closes #3399 
Files to upload:
```
$ ls -l /cvmfs/cms-opendata-conddb.cern.ch | grep hi
drwxr-xr-x. 2 cvmfs cvmfs       12288 Jul 28 19:45 hi_53_add_ons
drwxr-xr-x. 2 cvmfs cvmfs        4096 Jul 30 17:31 hi_75_add_ons
$ ls -l /cvmfs/cms-opendata-conddb.cern.ch | grep HI53_V
drwxr-xr-x. 2 cvmfs cvmfs       16384 Jun 21 16:48 STARTHI53_V27
-rw-r--r--. 1 cvmfs cvmfs      114688 Sep  6 08:30 STARTHI53_V27.db
drwxr-xr-x. 2 cvmfs cvmfs       16384 Jun 21 16:49 STARTHI53_V28
-rw-r--r--. 1 cvmfs cvmfs      114688 Sep  6 08:30 STARTHI53_V28.db
drwxr-xr-x. 2 cvmfs cvmfs       16384 Nov 30  2022 GR_P_V43D
-rw-r--r--. 1 cvmfs cvmfs       75776 Nov 30  2022 GR_P_V43D.db
-rw-r--r--. 1 cvmfs cvmfs 34763472896 Nov 30  2022 75X_dataRun2_v13.db
```
`run_period` for simulated data left out on purpose
=> records: add HI conddb records

cernopendata/templates/cernopendata_records_ui/records/record_detail.html
Fixes the display of the collision energy badge and the collision type badge in detailed record pages that broke during the recent "qa" to "master" merge.
=> templates: fix display of collision info badges

cernopendata/modules/fixtures/data/records/cms-validated-runs-ppRun2.json
(closes #3446)
Add 2016 validated run records, reicd 14220 and 14221
To-do:
copy the actual json files from
14220: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions16/13TeV/Legacy_2016/Cert_271036-284044_13TeV_Legacy2016_Collisions16_JSON.txt
14221: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions16/13TeV/Legacy_2016/Cert_271036-284044_13TeV_Legacy2016_Collisions16_JSON_MuonPhys.txt
=> records: add cms 2016 validated runs record

cernopendata/modules/fixtures/data/records/cms-luminosity-information-detailed.json
(closes #3448 )
Adds CMS 2016 lumi records.
FIles to be attached to the record are in  `/eos/opendata/cms/upload/kati/lumi` from which they should be moved to a new `/eos/opendata/cms/luminosity/2016`
=> records: add cms 2016 luminosity record

cernopendata/config.py
After the addition of old JADE records, we have much larger year span, and so have to show more year values in the facet. Closes #3480.
=> search: show more year values in the year facet

cernopendata/config.py
Invenio offers the possibility to use a prefix for the indices. This is very important if the cluster is used for other things, for example having dashboards. This prefix will be used to restrict the queries.
The current opendata config is not compatible with this setup, since it uses things like `_all` that will be appended to the prefix, and then it ends up creating index names that do not exist
=> search: allow the usage of INVENIO_SEARCH_PREFIX

cernopendata/config.py, setup.py
Change the default parser of invenio-records-rest to use an AND of the terms instead of the OR
=> query: use an AND parser instead of OR

Dockerfile
Upgrades XRootD version, fixing build troubles related to recent update of the XRootD package in the Alma Linux 9 ecosystem.
Closes #3509.
=> docker: XRootD 5.6.4

cernopendata/modules/theme/assets/semantic-ui/scss/search.scss
Right now, the button to display the facets on a mobile display cannot be clicked. There is a ` div` overlapping. This PR ensures that there is no overlap between the different elements
=> facets: display the facets on the mobile application

cernopendata/modules/fixtures/data/records/cms-tools-Run1-nano.json, cernopendata/modules/fixtures/data/records/cms-tools-pfnano.json, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
Closes #3281
Unifies descriptions etc of recid 12504 accordingly.
To do when the github repo README gets updated:
- tag the repo
- add the zip file to this record
=> records: CMS nano sw updates

cernopendata/modules/fixtures/data/records/cms-condition-data-2012.json, cernopendata/modules/fixtures/data/records/cms-condition-data-2015.json, cernopendata/modules/fixtures/data/records/cms-condition-data-2016.json, cernopendata/modules/fixtures/data/records/cms-condition-data-HIRun1.json, cernopendata/modules/fixtures/data/records/cms-condition-data-Run2010B.json, cernopendata/modules/fixtures/data/records/cms-condition-data-Run2011A.json
(Closes #3538)
Adds the two 2016 condition data records
Updates the titles with old condition data records with collision type and energy
To do for 2016:
- add the db files from /eos/opendata/cms/conddb/106X_dataRun2_v37.db and /eos/opendata/cms/conddb/106X_mcRun2_asymptotic_v17.db
=> records: cms 2016 conddb records and updates to old record titles

cernopendata/jsonschemas/records/record-v1.0.0.json, cernopendata/templates/cernopendata_records_ui/records/record_detail.html
Addresses #3454 
- adds cross-section values to 2015 MC records from MC2015 in  https://cernbox.cern.ch/s/EHpyrdJet939vGy 
- modifies the record template `templates/cernopendata_records_ui/records/record_detail.html` so that the values get displayed with the text suggested in #3454
=> records: add xsec values for 2015 MC and update record template

cernopendata/modules/fixtures/data/records/cms-tools-vm-image-2016-2018.json, cernopendata/modules/fixtures/data/records/cms-tools-vm-image-Run2011A.json, cernopendata/modules/fixtures/data/records/cms-tools-vm-image.json
(Closes #3537 )
Add records for
- the new VM image
- the contextualization scripts to build it
To do:
Copy from `/eos/opendata/cms/upload/vm160:`
For the VM record 258
```
CMS-OpenData-1.6.0.ova
```
For the contextualization scripts
```
ucernvm-v4prod.2020.07-1.cernvm.x86_64.hdd
cernvm-script
cms-user-data.txt
opendata-desktop-settings
```
=> records: cms 2016 vm

setup.py
Pins invenio-app to less than 1.5.0, fixing the issue with Flask-Limiter and the detailed record page display.
Closes #3593
=> setup: pin invenio-app to 1.4.0

cernopendata/modules/fixtures/data/records/cms-reco-configuration-files-2015.json, cernopendata/modules/fixtures/data/records/cms-reco-configuration-files-2016.json
Fixes the checksum information for CMS 2016 RECO configuration files to Adler32 that is being used on EOSPUBLIC.
Closes #3591
=> records: CMS 2016 collision datasets RECO checksums

Dockerfile, cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2016-pileup.json, requirements-production.txt, setup.py
(closes #3569)
Adds the record for the 2016 pileup sample.
To-do:
- check the actual size from eos (it is not taken from DAS as this is a 10% fraction of the original 500 TB dataset)
- ~~modify the template so that the related dataset field won't appear for PREMIX~~
The related dataset field might have come from some local cache, does not appear anymore.
=> records: add 2016 pileup record

cernopendata/modules/fixtures/data/docs/cms-guide-for-conddb/cms-guide-for-conddb.md
(closes #3608)
- Adds the 2016 data and MC GTs
- Adds intermediate titles for Run-1 and Run-2 for a better readability
=> docs: updates the CMS conddb guide with 2016 GTs

Dockerfile, cernopendata/modules/fixtures/data/docs/cms-getting-started-nanoaod/cms-getting-started-nanoaod.md, cernopendata/modules/fixtures/data/records/cms-tools-Run1-nano-examples.json, cernopendata/modules/fixtures/data/records/cms-tools-nanoaodtools-skimmer.json, requirements-production.txt, setup.py
Adding records for the NanoAODRun1Examples (12506) and nanoAOD-tools (12507) code repositories. 
Corresponding link changes in the NanoAOD getting started page. 
The zip files are in /eos/opendata/cms/upload/: 
NanoAODRun1Examples-1.0.zip
nanoAOD-tools-1.0.zip
=> CMS: 2 new tools records

cernopendata/modules/fixtures/data/docs/cms-guide-docker/cms-guide-docker.md
(closes #3617 )
- adds the new image to the list
- changes the example commands to 2016 pp
- fixes some links
=> docs:  update CMS docker guide for 2016

docker-compose-dev.yml, docker-compose.yml, setup.py
Fixes OpenSearch starting troubles by pinning the OpenSearch version to the last one not requiring to set the
`OPENSEARCH_INITIAL_ADMIN_PASSWORD` environment variable.
Closes #3634
=> docker: pin OpenSearch version

AUTHORS.rst
Co-authored-by: Mohammad Doleh @d0leh
=> feat: added cross_section field to MC2015 records with non-zero total_value

cernopendata/modules/fixtures/data/docs/cms-getting-started-nanoaod/cms-getting-started-nanoaod.md, cernopendata/modules/fixtures/data/records/cms-corrections-run2.json
Adding record 12508 (appears unused) for CMS Run 2 corrections files. There are two items in the upload folder that would be needed for this record:
* opendata/cms/upload/jsonpog-integration-2016postVFP.tar --> this is the actual file to be attached
* opendata/cms/upload/commonJSONSFs/index.html --> this is a web page that will show the contents of the file. It's linked in one of the description segments. 
We would like to make a new folder and put both the .tar file and the directory of html files there: opendata/cms/corrections/
=> CMS: add record for corrections

cernopendata/modules/fixtures/data/records/jade-data.json
Preliminary jade-data record file.
=> Add jade-data entry

data/docs/jade-getting-started/jade-getting-started.md
First real instructions on how to install the JADE software.
=> Rework jade getting started

AUTHORS.rst, data/records/atlas-2020-1largeRjet1lep.json, data/records/atlas-2020-1lep.json, data/records/atlas-2020-1lep1tau.json, data/records/atlas-2020-2lep.json, data/records/atlas-2020-3lep.json, data/records/atlas-2020-4lep.json, data/records/atlas-2020-GamGam.json, data/records/atlas-2020-exactly2lep.json, data/records/atlas-2020-mc-jet-reconstruction.json, data/records/atlas-ATL-PHYS-PUB-2021-002.json, data/records/atlas-CERN-EP-2023-174.json, data/records/atlas-CERN-EP-2024-159.json, data/records/atlas-SIMU-2018-04.json
Several records belonging to the 2020 release were not including the proper flag for `Simulated` samples.
Updated flags according to the content of the records.
=> Update flags for the ATLAS 2020 Open Data records

data/records/atlas-hi-2024-hi-2015-data.json, data/records/atlas-hi-2024-mc-hi-minbias.json, data/records/atlas-hi-2024-summary.json
For the two new HI records, we should make sure the Heavy Ion tag is included :)
=> Adding Heavy Ion Physics tag to HI records

CONTRIBUTING.rst, DEVELOPING.rst, README.rst, docker-compose-override.yml, scripts/check_fixtures.py
Adapts documentation for data curators following up the split of the 
portal's infrastructure code from the content in two repositories.
Implements comments from the #3590 pull request review.
Closes #3678.
=> docs(developing): adapt documentation after infrastructure code split

run-tests.sh, scripts/clean_json_file.py
Fixes a problem with the CI data JSON checker that was not reporting proper error code when checking multiple files.
=> ci(run-tests): fix data JSON checker error reporting

data/docs/delphi-getting-started/delphi-getting-started.md, data/docs/delphi-guide-docker/delphi-guide-docker.md
Some work has been done on supporting remote reading of the data. This is supported by the containers. 
In addition, some hints are added on how to run the container image on MacOS.
=> Adapt documentation for DELPHI containers to the latest version

DEVELOPING.rst
fixed a typo in DEVELOPING.rst : a missing t in 'documenation' (documentation)
=> docs(developing): fix "documentation" typos

data/records/atlas-2020-1largeRjet1lep.json, data/records/atlas-2020-1lep.json, data/records/atlas-2020-1lep1tau.json, data/records/atlas-2020-2lep.json, data/records/atlas-2020-3lep.json, data/records/atlas-2020-4lep.json, data/records/atlas-2020-GamGam.json, data/records/atlas-2020-exactly2lep.json
Offer individual ROOT files for ATLAS 2020 education datasets to make the access easier, all the while keeping the original zip tarball.
Closes cernopendata/data-curation#257
=> feat(records): add individual ATLAS 2020 ROOT files

data/records/atlas-FTAG-2023-05.json
The first person I pointed this record to immediately asked for an arXiv link. I don't blame him: the link is buried within a CERN page which is linked with minimal description at the bottom of the page.
I also cleaned up the language a bit.
=> fix(records): List paper arXiv link more prominently
